In [1]:
import os
import json
import sys
import argparse
import datetime
import pandas as pd
import numpy as np
from kp_info_loader_core import InitCore
# from exchange_plugin.common_info import InitCommonInfo
# from monitor_engine.kimp_core_monitor import InitKimpCoreMonitor
from etc.db_handler.create_schema_tables import InitDBClient
# from trigger_engine.snatcher import InitSnatcher
from etc.register_monitor_msg import RegisterMonitorMsg
import _pickle as pickle
import time
import datetime
from etc.redis_connector.redis_connector import InitRedis
from multiprocessing import Process

# for jupyter notebook
import nest_asyncio
nest_asyncio.apply()

[WARNING] upbit-client is currently a newer version: 1.3.4.1
Please update to the latest version using the pip command:`pip install --upgrade upbit-client`

In [2]:
logging_dir = "/home/kp_info_loader/"
with open("/home/kp_info_loader/kp_info_loader_config.json") as f:
    config = json.load(f)
proc_n = 6
# node = config['node']
node = 'kp_info_loader'
monitor_bot_name = config['monitor_setting']['monitor_bot']
monitor_bot_token = config['telegram_bot_setting'][monitor_bot_name]
monitor_bot_api_url = config['monitor_setting']['monitor_bot_api_url']
admin_id = config['telegram_admin_id']['charlie1155']

register_monitor_msg = RegisterMonitorMsg(monitor_bot_token, monitor_bot_api_url, admin_id)
# Read api keys
exchange_api_key_dict = config['exchange_api_key']
# Exchange market settings
enabled_markets_dict = config['enabled_markets']

my_okx_demo_api_key = "bbb8a09a-6ea2-4686-add5-1095c918b7f4"
my_okx_demo_secret_key = "FBEAD86057449BAEC3FFA8A80CE76E4F"
my_okx_demo_passphrase = "121431Rn!!"

In [3]:
core = InitCore(logging_dir, proc_n, node, admin_id, register_monitor_msg, exchange_api_key_dict, enabled_markets_dict)

2023-09-13 16:25:29,337 - kimp_bot_core - INFO - InitCore|InitCore initiated with proc_n=6
[INFO] InitCore|InitCore initiated with proc_n=6
2023-09-13 16:25:29,453 - okx_plug - INFO - okx_plug_logger started.
[INFO] okx_plug_logger started.
2023-09-13 16:25:35,509 - upbit_plug - INFO - upbit_plug_logger started.
[INFO] upbit_plug_logger started.
2023-09-13 16:25:35,725 - binance_plug - INFO - binance_plug_logger started.
[INFO] binance_plug_logger started.
2023-09-13 16:25:35,728 - kimp_bot_core - INFO - InitCore|update_upbit_spot_ticker_df thread has started.
[INFO] InitCore|update_upbit_spot_ticker_df thread has started.
2023-09-13 16:25:35,732 - kimp_bot_core - INFO - InitCore|update_upbit_wallet_status_df thread has started.
[INFO] InitCore|update_upbit_wallet_status_df thread has started.
2023-09-13 16:25:35,737 - kimp_bot_core - INFO - InitCore|update_binance_spot_ticker_df thread has started.
[INFO] InitCore|update_binance_spot_ticker_df thread has started.
2023-09-13 16:25:35,740 - kimp_bot_core - INFO - InitCore|update_binance_spot_info_df thread has started.
[INFO] InitCore|update_binance_spot_info_df thread has started.
2023-09-13 16:25:35,742 - kimp_bot_core - INFO - InitCore|update_binance_usd_m_ticker_df thread has started.
[INFO] InitCore|update_binance_usd_m_ticker_df thread has started.
2023-09-13 16:25:35,744 - kimp_bot_core - INFO - InitCore|update_binance_usd_m_info_df thread has started.
[INFO] InitCore|update_binance_usd_m_info_df thread has started.
2023-09-13 16:25:35,747 - kimp_bot_core - INFO - InitCore|update_binance_coin_m_ticker_df thread has started.
[INFO] InitCore|update_binance_coin_m_ticker_df thread has started.
2023-09-13 16:25:35,749 - kimp_bot_core - INFO - InitCore|update_binance_coin_m_info_df thread has started.
[INFO] InitCore|update_binance_coin_m_info_df thread has started.
2023-09-13 16:25:35,751 - kimp_bot_core - INFO - InitCore|Waiting for all info to be updated.
[INFO] InitCore|Waiting for all info to be updated.
2023-09-13 16:25:36,525 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-09-13 16:25:37,760 - kimp_bot_core - INFO - InitCore|Waiting for all info to be updated.
2023-09-13 16:25:37,775 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] InitCore|Waiting for all info to be updated.
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-13 16:25:37,969 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-09-13 16:25:39,834 - kimp_bot_core - INFO - InitCore|All info df has been updated.
[INFO] InitCore|All info df has been updated.
2023-09-13 16:25:39,965 - upbit_websocket - INFO - 1th Upbit ticker websocket does not exist. starting..
2023-09-13 16:25:39,966 - upbit_websocket - INFO - [UPBIT SPOT]started monitor_shared_symbol_change..
[INFO] 1th Upbit ticker websocket does not exist. starting..
[INFO] [UPBIT SPOT]started monitor_shared_symbol_change..
2023-09-13 16:25:39,987 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2023-09-13 16:25:40,084 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:40,261 - upbit_websocket - INFO - 1th Upbit orderbook websocket does not exist. starting..
[INFO] 1th Upbit orderbook websocket does not exist. starting..
2023-09-13 16:25:40,359 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-09-13 16:25:40,438 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:40,513 - binance_websocket - INFO - [BINANCE SPOT]1th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]1th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:40,515 - binance_websocket - INFO - [BINANCE SPOT]started monitor_shared_symbol_change..
[INFO] [BINANCE SPOT]started monitor_shared_symbol_change..
2023-09-13 16:25:40,530 - binance_websocket - INFO - [BINANCE SPOT]started 1th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 1th_price_proc websocket proc..
2023-09-13 16:25:40,695 - binance_websocket - INFO - [BINANCE SPOT]2th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]2th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:40,723 - binance_websocket - INFO - [BINANCE SPOT]started 2th_price_proc websocket proc..
2023-09-13 16:25:40,727 - upbit_websocket - INFO - 2th Upbit ticker websocket does not exist. starting..
[INFO] 2th Upbit ticker websocket does not exist. starting..
[INFO] [BINANCE SPOT]started 2th_price_proc websocket proc..
2023-09-13 16:25:40,750 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
2023-09-13 16:25:40,815 - binance_usdm_websocket - INFO - [BINANCE USD-M]1th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]1th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:40,816 - binance_usdm_websocket - INFO - [BINANCE USD-M]started monitor_shared_symbol_change..
[INFO] [BINANCE USD-M]started monitor_shared_symbol_change..
2023-09-13 16:25:40,842 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 1th_price_proc websocket..
[INFO] [BINANCE USD-M]started 1th_price_proc websocket..
2023-09-13 16:25:40,855 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:40,886 - binance_websocket - INFO - [BINANCE SPOT]3th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]3th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:40,909 - binance_websocket - INFO - [BINANCE SPOT]started 3th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 3th_price_proc websocket proc..
2023-09-13 16:25:40,996 - binance_usdm_websocket - INFO - [BINANCE USD-M]2th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]2th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,013 - upbit_websocket - INFO - 2th Upbit orderbook websocket does not exist. starting..
2023-09-13 16:25:41,016 - binance_coinm_websocket - INFO - [BINANCE COIN-M]1th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,017 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started monitor_shared_symbol_change..
[INFO] [BINANCE COIN-M]1th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] 2th Upbit orderbook websocket does not exist. starting..
[INFO] [BINANCE COIN-M]started monitor_shared_symbol_change..
2023-09-13 16:25:41,037 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 2th_price_proc websocket..
[INFO] [BINANCE USD-M]started 2th_price_proc websocket..
2023-09-13 16:25:41,052 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 1th_price_proc websocket proc..
2023-09-13 16:25:41,063 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
[INFO] [BINANCE COIN-M]started 1th_price_proc websocket proc..
[INFO] upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
2023-09-13 16:25:41,078 - binance_websocket - INFO - [BINANCE SPOT]4th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,121 - binance_websocket - INFO - [BINANCE SPOT]started 4th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 4th_price_proc websocket proc..
2023-09-13 16:25:41,052 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 1th_price_proc websocket proc..
2023-09-13 16:25:41,175 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:41,193 - binance_usdm_websocket - INFO - [BINANCE USD-M]3th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]3th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,212 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 3th_price_proc websocket..
[INFO] [BINANCE USD-M]started 3th_price_proc websocket..
2023-09-13 16:25:41,217 - binance_coinm_websocket - INFO - [BINANCE COIN-M]2th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]2th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,233 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 2th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 2th_price_proc websocket proc..
2023-09-13 16:25:41,281 - binance_websocket - INFO - [BINANCE SPOT]5th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]5th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,297 - binance_websocket - INFO - [BINANCE SPOT]started 5th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 5th_price_proc websocket proc..
2023-09-13 16:25:41,366 - binance_usdm_websocket - INFO - [BINANCE USD-M]4th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,380 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 4th_price_proc websocket..
[INFO] [BINANCE USD-M]started 4th_price_proc websocket..
2023-09-13 16:25:41,386 - binance_coinm_websocket - INFO - [BINANCE COIN-M]3th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]3th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,401 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 3th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 3th_price_proc websocket proc..
2023-09-13 16:25:41,418 - upbit_websocket - INFO - 3th Upbit ticker websocket does not exist. starting..
[INFO] 3th Upbit ticker websocket does not exist. starting..
2023-09-13 16:25:41,429 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-09-13 16:25:41,450 - binance_websocket - INFO - [BINANCE SPOT]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE SPOT]6th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,467 - binance_websocket - INFO - [BINANCE SPOT]started 6th_price_proc websocket proc..
[INFO] [BINANCE SPOT]started 6th_price_proc websocket proc..
2023-09-13 16:25:41,533 - binance_usdm_websocket - INFO - [BINANCE USD-M]5th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]5th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,553 - binance_coinm_websocket - INFO - [BINANCE COIN-M]4th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]4th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,573 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 5th_price_proc websocket..
[INFO] [BINANCE USD-M]started 5th_price_proc websocket..
2023-09-13 16:25:41,589 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 4th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 4th_price_proc websocket proc..
2023-09-13 16:25:41,682 - upbit_websocket - INFO - 3th Upbit orderbook websocket does not exist. starting..
[INFO] 3th Upbit orderbook websocket does not exist. starting..
2023-09-13 16:25:41,699 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
2023-09-13 16:25:41,728 - binance_usdm_websocket - INFO - [BINANCE USD-M]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]6th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,744 - binance_usdm_websocket - INFO - [BINANCE USD-M]started 6th_price_proc websocket..
2023-09-13 16:25:41,746 - binance_coinm_websocket - INFO - [BINANCE COIN-M]5th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]started 6th_price_proc websocket..
[INFO] [BINANCE COIN-M]5th_price_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,762 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 5th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 5th_price_proc websocket proc..
2023-09-13 16:25:41,745 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:41,899 - binance_usdm_websocket - INFO - [BINANCE USD-M]liquidation_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]liquidation_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:41,913 - binance_usdm_websocket - INFO - [BINANCE USD-M]started liquidation_proc websocket proc..
2023-09-13 16:25:41,914 - binance_coinm_websocket - INFO - [BINANCE COIN-M]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]6th_price_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE USD-M]started liquidation_proc websocket proc..
2023-09-13 16:25:41,931 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started 6th_price_proc websocket proc..
[INFO] [BINANCE COIN-M]started 6th_price_proc websocket proc..
2023-09-13 16:25:41,932 - binance_usdm_websocket - INFO - started liquidation_websocket for USD-M..
[INFO] started liquidation_websocket for USD-M..
2023-09-13 16:25:42,028 - update_dollar - INFO - fetch_dollar|Dollar price (1329.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1329.5 KRW) has been updated.
2023-09-13 16:25:42,052 - upbit_websocket - INFO - 4th Upbit ticker websocket does not exist. starting..
[INFO] 4th Upbit ticker websocket does not exist. starting..
2023-09-13 16:25:42,064 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|4th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|4th upbit_ticker_proc started.
2023-09-13 16:25:42,083 - binance_coinm_websocket - INFO - [BINANCE COIN-M]liquidation_proc is not in self.websocket_proc_dict. starting..
[INFO] [BINANCE COIN-M]liquidation_proc is not in self.websocket_proc_dict. starting..
2023-09-13 16:25:42,097 - binance_coinm_websocket - INFO - [BINANCE COIN-M]started liquidation_proc websocket proc..
[INFO] [BINANCE COIN-M]started liquidation_proc websocket proc..
2023-09-13 16:25:42,119 - binance_coinm_websocket - INFO - started liquidation_websocket for COIN-M..
[INFO] started liquidation_websocket for COIN-M..
2023-09-13 16:25:42,320 - upbit_websocket - INFO - 4th Upbit orderbook websocket does not exist. starting..
[INFO] 4th Upbit orderbook websocket does not exist. starting..
2023-09-13 16:25:42,336 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|4th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|4th upbit_orderbook_proc started.
2023-09-13 16:25:42,690 - upbit_websocket - INFO - 5th Upbit ticker websocket does not exist. starting..
[INFO] 5th Upbit ticker websocket does not exist. starting..
2023-09-13 16:25:42,703 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|5th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|5th upbit_ticker_proc started.
2023-09-13 16:25:42,957 - upbit_websocket - INFO - 5th Upbit orderbook websocket does not exist. starting..
[INFO] 5th Upbit orderbook websocket does not exist. starting..
2023-09-13 16:25:42,970 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|5th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|5th upbit_orderbook_proc started.

2023-09-13 16:25:43,324 - upbit_websocket - INFO - 6th Upbit ticker websocket does not exist. starting..
[INFO] 6th Upbit ticker websocket does not exist. starting..
2023-09-13 16:25:43,340 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|6th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|6th upbit_ticker_proc started.
2023-09-13 16:25:43,594 - upbit_websocket - INFO - 6th Upbit orderbook websocket does not exist. starting..
[INFO] 6th Upbit orderbook websocket does not exist. starting..
2023-09-13 16:25:43,607 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|6th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|6th upbit_orderbook_proc started.
2023-09-13 16:25:51,810 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-09-13 16:25:51,811 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-09-13 16:25:51,811 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:52,024 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:52,031 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-09-13 16:25:52,031 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started
2023-09-13 16:25:52,050 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
[INFO] upbit_websocket|upbit_websocket started

In [7]:
core.get_market_code_list()

In [8]:
core.exchange_websocket_dict['UPBIT_SPOT'].get_price_df()['quote_asset'].unique()

array(['KRW', 'BTC'], dtype=object)

2023-09-13 16:26:13,296 - update_dollar - INFO - fetch_dollar|Dollar price (1329.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1329.5 KRW) has been updated.
2023-09-13 16:26:44,210 - update_dollar - INFO - fetch_dollar|Dollar price (1329.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1329.5 KRW) has been updated.

In [240]:
test_appended_premium_df[test_appended_premium_df['datetime_now']<'2023-08-31 00:00:00.000000']

       symbol   tp_kimp      tp_usdt                datetime_now
0     BTCUSDT  0.009003  1281.434055  2023-07-18 20:07:29.453044
1     BCHUSDT  0.008457  1280.739844  2023-07-18 20:07:29.453044
2    KAVAUSDT   0.00938  1281.912004  2023-07-18 20:07:29.453044
3     SOLUSDT   0.00781  1279.918327  2023-07-18 20:07:29.453044
4   STORJUSDT  0.007732  1279.819471  2023-07-18 20:07:29.453044
..        ...       ...          ...                         ...
19    SUIUSDT  0.006627  1278.416689  2023-07-18 20:07:29.453044
20    STXUSDT  0.006757  1278.581428  2023-07-18 20:07:29.453044
21  MATICUSDT  0.008039  1280.209014  2023-07-18 20:07:29.453044
22    GMTUSDT  0.011624  1284.763024  2023-07-18 20:07:29.453044
23    ONTUSDT  0.008118  1280.310378  2023-07-18 20:07:29.453044

[3000 rows x 4 columns]

In [45]:
print(f"length of appended_premium_df: {len(appended_premium_df)}, size: {sys.getsizeof(appended_premium_df) / 1024 / 1024}")

length of appended_premium_df: 43432, size: 22.55217742919922

2023-09-07 16:15:47,527 - update_dollar - INFO - fetch_dollar|Dollar price (1335.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1335.5 KRW) has been updated.

In [50]:
 
start = time.time()
appended_premium_df = pd.DataFrame()
start_datetime = datetime.datetime.now()
while True:
    if datetime.datetime.now() - start_datetime > datetime.timedelta(minutes=2):
        break
    premium_df = core.get_premium_df('BINANCE_USD_M/USDT', 'UPBIT_SPOT/KRW')
    premium_df['datetime_now'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
    appended_premium_df = pd.concat([appended_premium_df, premium_df], axis=0)
    appended_premium_df.loc[:, 'datetime_now'] = pd.to_datetime(appended_premium_df['datetime_now'])

# cut_i = 20000
# column_list = ['symbol','tp_kimp','tp_usdt']
# # print(f"generating_kimp_df: {time.time()-start}")
# start = time.time()
# test_appended_premium_df = appended_premium_df.iloc[:cut_i, :][column_list]
# test_appended_premium_df['datetime_now'] = datetime.datetime.now()#.strftime("%Y-%m-%d %H:%M:%S.%f")
# print(f"length of test_appended_premium_df: {len(test_appended_premium_df)}, size: {sys.getsizeof(test_appended_premium_df) / 1024 / 1024}")
# appended_kimp_dict = test_appended_premium_df.reset_index(drop=True).to_dict()
# print(f"converting df to dict: {time.time()-start}, size: {sys.getsizeof(appended_kimp_dict) / 1024 / 1024}")
# start = time.time()
# appended_kimp_pickle = pickle.dumps(appended_kimp_dict)
# print(f"converting df to pickle: {time.time()-start}, size: {sys.getsizeof(appended_kimp_pickle) / 1024 / 1024}")
# start = time.time()
# redis_cli.set_dict('kimp_dict', appended_kimp_dict)
# print(f"redis saving dict: {time.time()-start}")
# start = time.time()
# redis_cli.set_data('kimp_dict_pickle', appended_kimp_pickle)
# print(f"redis saving pickle: {time.time()-start}")
# start = time.time()
# fetched_dict = redis_cli.get_dict('kimp_dict')
# fetched_df = pd.DataFrame(fetched_dict)
# # fetched_df.loc[:, 'datetime_now'] = pd.to_datetime(fetched_df['datetime_now'])
# print(f"redis fetching dict: {time.time()-start}")
# start = time.time()
# fetched_pickle = redis_cli.get_data('kimp_dict_pickle')
# fetched_df = pd.DataFrame(pickle.loads(fetched_pickle))
# # fetched_df.loc[:, 'datetime_now'] = pd.to_datetime(fetched_df['datetime_now'])
# print(f"redis fetching pickle: {time.time()-start}")

2023-09-07 16:19:19,016 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:19:24,232 - update_dollar - INFO - fetch_dollar|Dollar price (1335.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1335.0 KRW) has been updated.
2023-09-07 16:19:34,719 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:19:50,032 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:19:55,130 - update_dollar - INFO - fetch_dollar|Dollar price (1335.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1335.0 KRW) has been updated.
2023-09-07 16:20:05,554 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:20:21,003 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:20:26,194 - update_dollar - INFO - fetch_dollar|Dollar price (1335.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1335.0 KRW) has been updated.
2023-09-07 16:20:36,422 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:20:52,052 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-07 16:20:57,259 - update_dollar - INFO - fetch_dollar|Dollar price (1335.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1335.0 KRW) has been updated.
2023-09-07 16:21:08,336 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

2023-09-07 16:21:23,657 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [266]:
start = time.time()
temp = resample_ohlc_df(pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_1T_kline')), resample_period="5T", closed_count=5)
print(f"resample_ohlc_df: {time.time()-start}")
temp[temp['base_asset']=='XRP'].tail(20)

resample_ohlc_df: 1.1875619888305664

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,count,closed
171,XRP,2023-09-12 15:25:00,1.022668,1.022668,0.866287,0.866287,1.001644,1.001644,1.001644,1.001644,0.824311,0.824311,0.824311,0.824311,3,False
172,XRP,2023-09-12 15:30:00,0.866287,1.022668,0.866287,1.022668,1.001644,1.001644,1.001644,1.001644,0.824311,0.824311,0.824311,0.824311,5,True
173,XRP,2023-09-12 15:35:00,1.022668,1.179050,0.866287,0.866287,1.001644,1.157993,1.001644,1.001644,0.824311,0.980628,0.824311,0.824311,5,True

In [4]:
core.check_status(print_result=True)

[UPBIT SPOT]1th_ticker_proc status: True
[UPBIT SPOT]1th_orderbook_proc status: True
[UPBIT SPOT]2th_ticker_proc status: True
[UPBIT SPOT]2th_orderbook_proc status: True
[UPBIT SPOT]3th_ticker_proc status: True
[UPBIT SPOT]3th_orderbook_proc status: True
[UPBIT SPOT]4th_ticker_proc status: True
[UPBIT SPOT]4th_orderbook_proc status: True
[UPBIT SPOT]5th_ticker_proc status: True
[UPBIT SPOT]5th_orderbook_proc status: True
[UPBIT SPOT]6th_ticker_proc status: True
[UPBIT SPOT]6th_orderbook_proc status: True

[BINANCE SPOT]1th_price_proc status: True
[BINANCE SPOT]2th_price_proc status: True
[BINANCE SPOT]3th_price_proc status: True
[BINANCE SPOT]4th_price_proc status: True
[BINANCE SPOT]5th_price_proc status: True
[BINANCE SPOT]6th_price_proc status: True

[BINANCE USD-M]1th_price_proc status: True
[BINANCE USD-M]2th_price_proc status: True
[BINANCE USD-M]3th_price_proc status: True
[BINANCE USD-M]4th_price_proc status: True
[BINANCE USD-M]5th_price_proc status: True
[BINANCE USD-M]6th_price_proc status: True
[BINANCE USD-M]liquidation_proc status: True

[BINANCE COIN-M]1th_price_proc status: True
[BINANCE COIN-M]2th_price_proc status: True
[BINANCE COIN-M]3th_price_proc status: True
[BINANCE COIN-M]4th_price_proc status: True
[BINANCE COIN-M]5th_price_proc status: True
[BINANCE COIN-M]6th_price_proc status: True
[BINANCE COIN-M]liquidation_proc status: True

True

In [5]:

def generate_ohlc_df(df, freq='1T'):
    df = df.set_index(['base_asset', 'datetime_now'])
    ohlc_df = pd.DataFrame()
    if 'tp_premium' in df.columns:
        df['tp_premium'] = pd.to_numeric(df['tp_premium'], errors='coerce')
        tp_ohlc_df = df.groupby(['base_asset', pd.Grouper(level='datetime_now', freq=freq)])['tp_premium'].ohlc()
        # add prefix of tp_ to the column names
        tp_ohlc_df.columns = ['tp_' + col for col in tp_ohlc_df.columns]
        ohlc_df = pd.concat([ohlc_df, tp_ohlc_df], axis=1)
    if 'LS_premium' in df.columns:
        df['LS_premium'] = pd.to_numeric(df['LS_premium'], errors='coerce')
        LS_ohlc_df = df.groupby(['base_asset', pd.Grouper(level='datetime_now', freq=freq)])['LS_premium'].ohlc()
        # add prefix of LS_ to the column names
        LS_ohlc_df.columns = ['LS_' + col for col in LS_ohlc_df.columns]
        ohlc_df = pd.concat([ohlc_df, LS_ohlc_df], axis=1)
    if 'SL_premium' in df.columns:
        df['SL_premium'] = pd.to_numeric(df['SL_premium'], errors='coerce')
        SL_ohlc_df = df.groupby(['base_asset', pd.Grouper(level='datetime_now', freq=freq)])['SL_premium'].ohlc()
        # add prefix of SL_ to the column names
        SL_ohlc_df.columns = ['SL_' + col for col in SL_ohlc_df.columns]
        ohlc_df = pd.concat([ohlc_df, SL_ohlc_df], axis=1)
    if 'tp_premium' not in df.columns and 'LS_premium' not in df.columns and 'SL_premium' not in df.columns:
        raise ValueError('There is no proper column in the dataframe')
    ohlc_df.reset_index(inplace=True)
    return ohlc_df

# start = time.time()
# ohlc_df = generate_ohlc_df(appended_premium_df, freq='1T')
# print(f"generating ohlc df: {time.time()-start}")
# ohlc_df

In [73]:
import matplotlib.pyplot as plt
import mplfinance as mpf

2023-09-07 19:09:42,948 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [9]:
def draw_ohlc(df, premium_type="tp"):
    df = df.set_index('datetime_now', drop=True)
    selected_columns = [col for col in df.columns if premium_type in col]
    df = df[selected_columns]
    df.columns = [col.replace(premium_type+'_', '') for col in df.columns]
    df.rename(columns={'open':'Open', 'high':'High', 'low':'Low', 'close':'Close'}, inplace=True)
    mpf.plot(df, type='candle', style='charles')

In [10]:
draw_ohlc(btc_ohlc_df, premium_type="tp")

NameError: name 'btc_ohlc_df' is not defined

2023-09-08 13:57:23,533 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-08 13:57:24,487 - update_dollar - INFO - fetch_dollar|Dollar price (1333.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1333.9 KRW) has been updated.

In [6]:

def ohlc_1T_loader(origin_exchange_code, target_exchange_code, redis_cli, loop_downtime_sec=0.01, max_length=300):
    appended_premium_df = pd.DataFrame()
    kline_switch = False
    while True:
        time.sleep(loop_downtime_sec)
        premium_df = core.get_premium_df(origin_exchange_code, target_exchange_code)
        datetime_now = datetime.datetime.now()
        premium_df['datetime_now'] = datetime_now
        appended_premium_df = pd.concat([appended_premium_df, premium_df], axis=0)
        appended_premium_df.loc[: ,'datetime_now'] = pd.to_datetime(appended_premium_df['datetime_now'])
        # print(f"redis saving ohlc_1T_now time: {time.time()-start}")
        if datetime_now.second == 0 and kline_switch == True:
            adjusted_datetime_now = datetime.datetime(datetime_now.year, datetime_now.month, datetime_now.day, datetime_now.hour, datetime_now.minute)
            cut_appended_premium_df = appended_premium_df[appended_premium_df['datetime_now'] < adjusted_datetime_now]
            start = time.time()
            ohlc_df = generate_ohlc_df(cut_appended_premium_df)
            print(f"generating ohlc_df(length: {len(cut_appended_premium_df)}): {time.time()-start}")
            # Save into redis db for current data
            start = time.time()
            redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_1T_now', pickle.dumps(ohlc_df))
            print(f"redis saving ohlc_1T_now time: {time.time()-start}")
            # Append into redis db for historical data
            start = time.time()
            old_ohlc_1T_kline = redis_cli.get_data(f'{origin_exchange_code}:{target_exchange_code}_1T_kline')
            if old_ohlc_1T_kline is None:
                old_ohlc_1T_kline = pd.DataFrame()
            else:
                old_ohlc_1T_kline = pickle.loads(old_ohlc_1T_kline)
            new_ohlc_1T_kline = pd.concat([old_ohlc_1T_kline, ohlc_df], axis=0).tail(max_length*ohlc_df['base_asset'].nunique())
            new_ohlc_1T_kline['closed'] = True
            redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_1T_kline', pickle.dumps(new_ohlc_1T_kline))
            print(f"redis ohlc_1T_kline load and saving time after appending: {time.time()-start}")
            appended_premium_df = appended_premium_df[appended_premium_df['datetime_now'] >= adjusted_datetime_now]
            kline_switch = False
        elif datetime_now.second != 0:
            # Save into redis db for current data
            ohlc_df = generate_ohlc_df(appended_premium_df)
            redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_1T_now', pickle.dumps(ohlc_df))
            kline_switch = True
        else:
            # Save into redis db for current data
            ohlc_df = generate_ohlc_df(appended_premium_df)
            redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_1T_now', pickle.dumps(ohlc_df))


redis_cli = InitRedis()
# ohlc_loader("BINANCE_USD_M/USDT", "UPBIT_SPOT/KRW", redis_cli)
ohlc_loader_proc = Process(target=ohlc_1T_loader, args=("BINANCE_USD_M/USDT", "UPBIT_SPOT/KRW", redis_cli), daemon=True)
ohlc_loader_proc.start()

2023-09-12 15:54:14,376 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

generating ohlc_df(length: 15982): 0.06250929832458496
redis saving ohlc_1T_now time: 0.0004570484161376953
redis ohlc_1T_kline load and saving time after appending: 0.0035893917083740234
generating ohlc_df(length: 17995): 0.06371498107910156
redis saving ohlc_1T_now time: 0.00046634674072265625
redis ohlc_1T_kline load and saving time after appending: 0.004090785980224609
generating ohlc_df(length: 19032): 0.07593464851379395
redis saving ohlc_1T_now time: 0.000518798828125
redis ohlc_1T_kline load and saving time after appending: 0.003861665725708008
generating ohlc_df(length: 19215): 0.06598687171936035
redis saving ohlc_1T_now time: 0.0006155967712402344
redis ohlc_1T_kline load and saving time after appending: 0.003770112991333008
generating ohlc_df(length: 18910): 0.07305097579956055
redis saving ohlc_1T_now time: 0.00040841102600097656
redis ohlc_1T_kline load and saving time after appending: 0.004749298095703125
generating ohlc_df(length: 19154): 0.08915448188781738
redis saving ohlc_1T_now time: 0.0005428791046142578
redis ohlc_1T_kline load and saving time after appending: 0.0031049251556396484
generating ohlc_df(length: 18117): 0.07637929916381836
redis saving ohlc_1T_now time: 0.00042724609375
redis ohlc_1T_kline load and saving time after appending: 0.00493931770324707
generating ohlc_df(length: 18300): 0.07361412048339844
redis saving ohlc_1T_now time: 0.0006992816925048828
redis ohlc_1T_kline load and saving time after appending: 0.003782987594604492
generating ohlc_df(length: 18239): 0.0710904598236084
redis saving ohlc_1T_now time: 0.0007255077362060547
redis ohlc_1T_kline load and saving time after appending: 0.004179477691650391
generating ohlc_df(length: 18727): 0.06566238403320312
redis saving ohlc_1T_now time: 0.0006561279296875
redis ohlc_1T_kline load and saving time after appending: 0.003865480422973633
generating ohlc_df(length: 18971): 0.07058143615722656
redis saving ohlc_1T_now time: 0.0005409717559814453
redis ohlc_1T_kline load and saving time after appending: 0.0045506954193115234
generating ohlc_df(length: 19032): 0.06595802307128906
redis saving ohlc_1T_now time: 0.00033974647521972656
redis ohlc_1T_kline load and saving time after appending: 0.0030112266540527344
generating ohlc_df(length: 18483): 0.06161761283874512
redis saving ohlc_1T_now time: 0.0006399154663085938
redis ohlc_1T_kline load and saving time after appending: 0.004139423370361328
generating ohlc_df(length: 18971): 0.07167720794677734
redis saving ohlc_1T_now time: 0.0005888938903808594
redis ohlc_1T_kline load and saving time after appending: 0.003922700881958008
generating ohlc_df(length: 18666): 0.07372379302978516
redis saving ohlc_1T_now time: 0.0006387233734130859
redis ohlc_1T_kline load and saving time after appending: 0.004057407379150391
generating ohlc_df(length: 18971): 0.08015584945678711
redis saving ohlc_1T_now time: 0.0005671977996826172
redis ohlc_1T_kline load and saving time after appending: 0.004143476486206055
generating ohlc_df(length: 18605): 0.06710577011108398
redis saving ohlc_1T_now time: 0.0004589557647705078
redis ohlc_1T_kline load and saving time after appending: 0.003890514373779297
generating ohlc_df(length: 17141): 0.06410050392150879
redis saving ohlc_1T_now time: 0.0005564689636230469
redis ohlc_1T_kline load and saving time after appending: 0.0049626827239990234
generating ohlc_df(length: 17446): 0.06347036361694336
redis saving ohlc_1T_now time: 0.0005965232849121094
redis ohlc_1T_kline load and saving time after appending: 0.004854679107666016
generating ohlc_df(length: 17873): 0.06714248657226562
redis saving ohlc_1T_now time: 0.0007672309875488281
redis ohlc_1T_kline load and saving time after appending: 0.005430936813354492
generating ohlc_df(length: 18300): 0.07361555099487305
redis saving ohlc_1T_now time: 0.0003590583801269531
redis ohlc_1T_kline load and saving time after appending: 0.00445866584777832
generating ohlc_df(length: 18422): 0.0659027099609375
redis saving ohlc_1T_now time: 0.0005645751953125
redis ohlc_1T_kline load and saving time after appending: 0.004946231842041016
generating ohlc_df(length: 18666): 0.07175540924072266
redis saving ohlc_1T_now time: 0.0005259513854980469
redis ohlc_1T_kline load and saving time after appending: 0.004103899002075195
generating ohlc_df(length: 18300): 0.07849669456481934
redis saving ohlc_1T_now time: 0.0005507469177246094
redis ohlc_1T_kline load and saving time after appending: 0.004813432693481445
generating ohlc_df(length: 17995): 0.07155632972717285
redis saving ohlc_1T_now time: 0.00048422813415527344
redis ohlc_1T_kline load and saving time after appending: 0.004063844680786133
generating ohlc_df(length: 18849): 0.06966447830200195
redis saving ohlc_1T_now time: 0.00045609474182128906
redis ohlc_1T_kline load and saving time after appending: 0.00811910629272461
generating ohlc_df(length: 18849): 0.07100415229797363
redis saving ohlc_1T_now time: 0.0004572868347167969
redis ohlc_1T_kline load and saving time after appending: 0.003954410552978516
generating ohlc_df(length: 18422): 0.08027195930480957
redis saving ohlc_1T_now time: 0.0004909038543701172
redis ohlc_1T_kline load and saving time after appending: 0.006049156188964844
generating ohlc_df(length: 18178): 0.07337069511413574
redis saving ohlc_1T_now time: 0.0005750656127929688
redis ohlc_1T_kline load and saving time after appending: 0.004809141159057617
generating ohlc_df(length: 18788): 0.0694267749786377
redis saving ohlc_1T_now time: 0.0007183551788330078
redis ohlc_1T_kline load and saving time after appending: 0.005748748779296875
generating ohlc_df(length: 18605): 0.07876968383789062
redis saving ohlc_1T_now time: 0.0005486011505126953
redis ohlc_1T_kline load and saving time after appending: 0.004652261734008789
generating ohlc_df(length: 18666): 0.06441974639892578
redis saving ohlc_1T_now time: 0.0008292198181152344
redis ohlc_1T_kline load and saving time after appending: 0.005964517593383789
generating ohlc_df(length: 18971): 0.06398272514343262
redis saving ohlc_1T_now time: 0.0005557537078857422
redis ohlc_1T_kline load and saving time after appending: 0.004937171936035156
generating ohlc_df(length: 18422): 0.07549214363098145
redis saving ohlc_1T_now time: 0.0003917217254638672
redis ohlc_1T_kline load and saving time after appending: 0.005213737487792969
generating ohlc_df(length: 18666): 0.0729372501373291
redis saving ohlc_1T_now time: 0.0006196498870849609
redis ohlc_1T_kline load and saving time after appending: 0.004250764846801758
generating ohlc_df(length: 19032): 0.0629568099975586
redis saving ohlc_1T_now time: 0.0006442070007324219
redis ohlc_1T_kline load and saving time after appending: 0.005680084228515625
generating ohlc_df(length: 18178): 0.0689694881439209
redis saving ohlc_1T_now time: 0.0005452632904052734
redis ohlc_1T_kline load and saving time after appending: 0.005939960479736328
generating ohlc_df(length: 18422): 0.07633280754089355
redis saving ohlc_1T_now time: 0.0016489028930664062
redis ohlc_1T_kline load and saving time after appending: 0.0062181949615478516
generating ohlc_df(length: 18483): 0.06833529472351074
redis saving ohlc_1T_now time: 0.0005822181701660156
redis ohlc_1T_kline load and saving time after appending: 0.004960536956787109
generating ohlc_df(length: 17751): 0.07454752922058105
redis saving ohlc_1T_now time: 0.0004904270172119141
redis ohlc_1T_kline load and saving time after appending: 0.004743099212646484
generating ohlc_df(length: 18361): 0.07763218879699707
redis saving ohlc_1T_now time: 0.0005452632904052734
redis ohlc_1T_kline load and saving time after appending: 0.006914377212524414
generating ohlc_df(length: 18666): 0.07303357124328613
redis saving ohlc_1T_now time: 0.0004820823669433594
redis ohlc_1T_kline load and saving time after appending: 0.0054225921630859375
generating ohlc_df(length: 18239): 0.07045388221740723
redis saving ohlc_1T_now time: 0.0006709098815917969
redis ohlc_1T_kline load and saving time after appending: 0.004876375198364258
generating ohlc_df(length: 18422): 0.07850146293640137
redis saving ohlc_1T_now time: 0.0004487037658691406
redis ohlc_1T_kline load and saving time after appending: 0.005043506622314453
generating ohlc_df(length: 18605): 0.07486867904663086
redis saving ohlc_1T_now time: 0.00040531158447265625
redis ohlc_1T_kline load and saving time after appending: 0.005139827728271484
generating ohlc_df(length: 18056): 0.06696867942810059
redis saving ohlc_1T_now time: 0.0005648136138916016
redis ohlc_1T_kline load and saving time after appending: 0.004612922668457031
generating ohlc_df(length: 18239): 0.07413148880004883
redis saving ohlc_1T_now time: 0.0005064010620117188
redis ohlc_1T_kline load and saving time after appending: 0.005431175231933594
generating ohlc_df(length: 18361): 0.07133769989013672
redis saving ohlc_1T_now time: 0.0004296302795410156
redis ohlc_1T_kline load and saving time after appending: 0.006165742874145508
generating ohlc_df(length: 18605): 0.07169175148010254
redis saving ohlc_1T_now time: 0.00046539306640625
redis ohlc_1T_kline load and saving time after appending: 0.0040378570556640625
generating ohlc_df(length: 18422): 0.07381534576416016
redis saving ohlc_1T_now time: 0.0006058216094970703
redis ohlc_1T_kline load and saving time after appending: 0.005198001861572266
generating ohlc_df(length: 17995): 0.06986689567565918
redis saving ohlc_1T_now time: 0.0005123615264892578
redis ohlc_1T_kline load and saving time after appending: 0.006612062454223633
generating ohlc_df(length: 17934): 0.06922459602355957
redis saving ohlc_1T_now time: 0.0008111000061035156
redis ohlc_1T_kline load and saving time after appending: 0.004725456237792969
generating ohlc_df(length: 17995): 0.07003951072692871
redis saving ohlc_1T_now time: 0.00046515464782714844
redis ohlc_1T_kline load and saving time after appending: 0.005940914154052734
generating ohlc_df(length: 17812): 0.0724635124206543
redis saving ohlc_1T_now time: 0.0005488395690917969
redis ohlc_1T_kline load and saving time after appending: 0.004942655563354492
generating ohlc_df(length: 17568): 0.06865882873535156
redis saving ohlc_1T_now time: 0.0005803108215332031
redis ohlc_1T_kline load and saving time after appending: 0.0055310726165771484
generating ohlc_df(length: 17446): 0.0737152099609375
redis saving ohlc_1T_now time: 0.0006964206695556641
redis ohlc_1T_kline load and saving time after appending: 0.00507664680480957
generating ohlc_df(length: 17568): 0.07148957252502441
redis saving ohlc_1T_now time: 0.0005965232849121094
redis ohlc_1T_kline load and saving time after appending: 0.006223440170288086
generating ohlc_df(length: 17568): 0.07277417182922363
redis saving ohlc_1T_now time: 0.0006015300750732422
redis ohlc_1T_kline load and saving time after appending: 0.0064144134521484375
generating ohlc_df(length: 17934): 0.06683230400085449
redis saving ohlc_1T_now time: 0.00040721893310546875
redis ohlc_1T_kline load and saving time after appending: 0.005677700042724609
generating ohlc_df(length: 17934): 0.06351256370544434
redis saving ohlc_1T_now time: 0.0004639625549316406
redis ohlc_1T_kline load and saving time after appending: 0.006766796112060547
generating ohlc_df(length: 18178): 0.08481168746948242
redis saving ohlc_1T_now time: 0.0005693435668945312
redis ohlc_1T_kline load and saving time after appending: 0.005808353424072266
generating ohlc_df(length: 18056): 0.07360720634460449
redis saving ohlc_1T_now time: 0.0005373954772949219
redis ohlc_1T_kline load and saving time after appending: 0.005259990692138672
generating ohlc_df(length: 18239): 0.07363271713256836
redis saving ohlc_1T_now time: 0.00048351287841796875
redis ohlc_1T_kline load and saving time after appending: 0.005334615707397461
generating ohlc_df(length: 17995): 0.07286334037780762
redis saving ohlc_1T_now time: 0.0004961490631103516
redis ohlc_1T_kline load and saving time after appending: 0.00783395767211914
generating ohlc_df(length: 18178): 0.07452535629272461
redis saving ohlc_1T_now time: 0.0005865097045898438
redis ohlc_1T_kline load and saving time after appending: 0.007689714431762695
generating ohlc_df(length: 17812): 0.05815386772155762
redis saving ohlc_1T_now time: 0.0005116462707519531
redis ohlc_1T_kline load and saving time after appending: 0.006166934967041016
generating ohlc_df(length: 17141): 0.07407307624816895
redis saving ohlc_1T_now time: 0.000331878662109375
redis ohlc_1T_kline load and saving time after appending: 0.00718235969543457
generating ohlc_df(length: 17385): 0.07386517524719238
redis saving ohlc_1T_now time: 0.00033593177795410156
redis ohlc_1T_kline load and saving time after appending: 0.005706310272216797
generating ohlc_df(length: 17324): 0.07301640510559082
redis saving ohlc_1T_now time: 0.0003802776336669922
redis ohlc_1T_kline load and saving time after appending: 0.0053446292877197266
generating ohlc_df(length: 17385): 0.07139205932617188
redis saving ohlc_1T_now time: 0.0005953311920166016
redis ohlc_1T_kline load and saving time after appending: 0.008656740188598633
generating ohlc_df(length: 17690): 0.07570815086364746
redis saving ohlc_1T_now time: 0.0008637905120849609
redis ohlc_1T_kline load and saving time after appending: 0.005330801010131836
generating ohlc_df(length: 17385): 0.07526612281799316
redis saving ohlc_1T_now time: 0.0006508827209472656
redis ohlc_1T_kline load and saving time after appending: 0.006621837615966797
generating ohlc_df(length: 17751): 0.06820106506347656
redis saving ohlc_1T_now time: 0.0007243156433105469
redis ohlc_1T_kline load and saving time after appending: 0.008239984512329102
generating ohlc_df(length: 17812): 0.07387948036193848
redis saving ohlc_1T_now time: 0.00043654441833496094
redis ohlc_1T_kline load and saving time after appending: 0.005181789398193359
generating ohlc_df(length: 17995): 0.06935715675354004
redis saving ohlc_1T_now time: 0.0005207061767578125
redis ohlc_1T_kline load and saving time after appending: 0.006874799728393555
generating ohlc_df(length: 18117): 0.07841682434082031
redis saving ohlc_1T_now time: 0.0005991458892822266
redis ohlc_1T_kline load and saving time after appending: 0.006410360336303711
generating ohlc_df(length: 17568): 0.07277917861938477
redis saving ohlc_1T_now time: 0.000377655029296875
redis ohlc_1T_kline load and saving time after appending: 0.00611567497253418
generating ohlc_df(length: 17507): 0.0759880542755127
redis saving ohlc_1T_now time: 0.0003972053527832031
redis ohlc_1T_kline load and saving time after appending: 0.0055849552154541016
generating ohlc_df(length: 16775): 0.0686337947845459
redis saving ohlc_1T_now time: 0.0003333091735839844
redis ohlc_1T_kline load and saving time after appending: 0.006346225738525391
generating ohlc_df(length: 16958): 0.07201862335205078
redis saving ohlc_1T_now time: 0.00035452842712402344
redis ohlc_1T_kline load and saving time after appending: 0.005845546722412109
generating ohlc_df(length: 17507): 0.08173513412475586
redis saving ohlc_1T_now time: 0.0005474090576171875
redis ohlc_1T_kline load and saving time after appending: 0.006346225738525391
generating ohlc_df(length: 17019): 0.08038043975830078
redis saving ohlc_1T_now time: 0.0005025863647460938
redis ohlc_1T_kline load and saving time after appending: 0.005429744720458984
generating ohlc_df(length: 16897): 0.06562399864196777
redis saving ohlc_1T_now time: 0.0004391670227050781
redis ohlc_1T_kline load and saving time after appending: 0.0061452388763427734
generating ohlc_df(length: 17446): 0.08023285865783691
redis saving ohlc_1T_now time: 0.0004627704620361328
redis ohlc_1T_kline load and saving time after appending: 0.008806228637695312
generating ohlc_df(length: 17690): 0.07879900932312012
redis saving ohlc_1T_now time: 0.0007565021514892578
redis ohlc_1T_kline load and saving time after appending: 0.009508848190307617
generating ohlc_df(length: 17507): 0.0671834945678711
redis saving ohlc_1T_now time: 0.00035309791564941406
redis ohlc_1T_kline load and saving time after appending: 0.0057027339935302734
generating ohlc_df(length: 17629): 0.07235455513000488

redis saving ohlc_1T_now time: 0.00039887428283691406
redis ohlc_1T_kline load and saving time after appending: 0.006140947341918945generating ohlc_df(length: 17568): 0.0739297866821289
redis saving ohlc_1T_now time: 0.0005254745483398438
redis ohlc_1T_kline load and saving time after appending: 0.00653386116027832
generating ohlc_df(length: 17507): 0.07665133476257324
redis saving ohlc_1T_now time: 0.0004665851593017578
redis ohlc_1T_kline load and saving time after appending: 0.00694584846496582
generating ohlc_df(length: 17934): 0.06726861000061035
redis saving ohlc_1T_now time: 0.00043201446533203125
redis ohlc_1T_kline load and saving time after appending: 0.0061299800872802734
generating ohlc_df(length: 17812): 0.0735177993774414
redis saving ohlc_1T_now time: 0.0004239082336425781
redis ohlc_1T_kline load and saving time after appending: 0.005952596664428711
generating ohlc_df(length: 17690): 0.0706031322479248
redis saving ohlc_1T_now time: 0.0009121894836425781
redis ohlc_1T_kline load and saving time after appending: 0.006729841232299805
generating ohlc_df(length: 17690): 0.10364341735839844
redis saving ohlc_1T_now time: 0.0005519390106201172
redis ohlc_1T_kline load and saving time after appending: 0.012823104858398438
generating ohlc_df(length: 17812): 0.07199382781982422
redis saving ohlc_1T_now time: 0.0003795623779296875
redis ohlc_1T_kline load and saving time after appending: 0.00632166862487793
generating ohlc_df(length: 17873): 0.07775235176086426
redis saving ohlc_1T_now time: 0.0005664825439453125
redis ohlc_1T_kline load and saving time after appending: 0.0060541629791259766
generating ohlc_df(length: 18056): 0.071624755859375
redis saving ohlc_1T_now time: 0.0007905960083007812
redis ohlc_1T_kline load and saving time after appending: 0.008464574813842773
generating ohlc_df(length: 17690): 0.07839250564575195
redis saving ohlc_1T_now time: 0.0003604888916015625
redis ohlc_1T_kline load and saving time after appending: 0.008232831954956055
generating ohlc_df(length: 17568): 0.07710933685302734
redis saving ohlc_1T_now time: 0.0005204677581787109
redis ohlc_1T_kline load and saving time after appending: 0.006974935531616211
generating ohlc_df(length: 17629): 0.07596826553344727
redis saving ohlc_1T_now time: 0.00047659873962402344
redis ohlc_1T_kline load and saving time after appending: 0.008920907974243164
generating ohlc_df(length: 18239): 0.05832529067993164

redis saving ohlc_1T_now time: 0.0006928443908691406redis ohlc_1T_kline load and saving time after appending: 0.008928060531616211
generating ohlc_df(length: 20923): 0.07503318786621094
redis saving ohlc_1T_now time: 0.0005245208740234375
redis ohlc_1T_kline load and saving time after appending: 0.008639335632324219
generating ohlc_df(length: 20984): 0.06386923789978027
redis saving ohlc_1T_now time: 0.0005865097045898438
redis ohlc_1T_kline load and saving time after appending: 0.007954597473144531
generating ohlc_df(length: 20862): 0.07076883316040039
redis saving ohlc_1T_now time: 0.0005860328674316406
redis ohlc_1T_kline load and saving time after appending: 0.008747100830078125
generating ohlc_df(length: 21289): 0.06542539596557617
redis saving ohlc_1T_now time: 0.0005590915679931641
redis ohlc_1T_kline load and saving time after appending: 0.007185697555541992
generating ohlc_df(length: 21106): 0.06336522102355957
redis saving ohlc_1T_now time: 0.0006272792816162109
redis ohlc_1T_kline load and saving time after appending: 0.008064985275268555
generating ohlc_df(length: 20984): 0.07131361961364746
redis saving ohlc_1T_now time: 0.00045371055603027344
redis ohlc_1T_kline load and saving time after appending: 0.009387969970703125
generating ohlc_df(length: 20984): 0.07501649856567383
redis saving ohlc_1T_now time: 0.0005407333374023438
redis ohlc_1T_kline load and saving time after appending: 0.008277654647827148

Process Process-37:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1393, in get_connection
    if connection.can_read():
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 809, in can_read
    return self._parser.can_read(timeout)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 315, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 222, in can_read
    return bool(self.length) or self._read_from_socket(
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 677, in _connect
    raise err
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 665, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_227652/2736439613.py", line 38, in ohlc_1T_loader
    redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_1T_now', pickle.dumps(ohlc_df))
  File "/home/kp_info_loader/etc/redis_connector/redis_connector.py", line 12, in set_data
    self.redis_conn.set(key_name, value)
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 2220, in set
    return self.execute_command("SET", *pieces, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1397, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

In [93]:
pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_1T_now'))

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close
0,1INCH,2023-09-12 17:24:00,2.857002,2.857002,2.812007,2.812007,2.902035,2.902035,2.857002,2.857002,2.197662,2.197662,2.152956,2.152956
1,AAVE,2023-09-12 17:24:00,2.515322,2.515322,2.476637,2.476637,2.486885,2.486885,2.448211,2.448211,2.254307,2.254307,2.187307,2.215728
2,ADA,2023-09-12 17:24:00,2.541263,2.582947,2.457998,2.457998,2.582947,2.582947,2.499614,2.499614,2.235170,2.235170,2.152153,2.152153
3,ALGO,2023-09-12 17:24:00,2.000079,2.000079,1.886997,2.000079,2.836146,2.836146,2.836146,2.836146,1.886997,1.886997,1.886997,1.886997
4,ANKR,2023-09-12 17:24:00,2.272886,2.272886,2.272886,2.272886,2.702604,2.702604,2.702604,2.702604,2.214578,2.214578,2.214578,2.214578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,XLM,2023-09-12 17:24:00,2.936257,2.936257,2.833051,2.840982,2.936257,2.936257,2.833051,2.848915,2.346795,2.346795,2.244187,2.252073
57,XRP,2023-09-12 17:24:00,2.591999,2.591999,2.368097,2.548693,2.591999,2.591999,2.548693,2.548693,2.411317,2.411317,2.368097,2.368097
58,XTZ,2023-09-12 17:24:00,2.668802,2.668802,2.668802,2.668802,2.593934,2.828972,2.593934,2.828972,2.316795,2.316795,2.316795,2.316795
59,ZIL,2023-09-12 17:24:00,2.065837,2.065837,2.065837,2.065837,2.631553,2.631553,2.631553,2.631553,2.065837,2.065837,2.065837,2.065837
60,ZRX,2023-09-12 17:24:00,2.701013,2.701013,2.701013,2.701013,2.764409,2.764409,2.701013,2.701013,2.236303,2.236303,2.173272,2.173272

2023-09-12 17:24:33,359 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [94]:
temp = pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_1T_kline'))
temp

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,closed
0,1INCH,2023-09-12 15:27:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,True
1,AAVE,2023-09-12 15:27:00,4.132675,4.132675,4.132675,4.132675,4.039255,4.039255,4.039255,4.039255,3.961578,3.961578,3.961578,3.961578,True
2,ADA,2023-09-12 15:27:00,2.500119,2.500119,2.500119,2.500119,2.458265,2.458265,2.458265,2.458265,2.109809,2.109809,2.109809,2.109809,True
3,ALGO,2023-09-12 15:27:00,3.329785,4.176751,3.329785,4.176751,4.176751,4.176751,4.176751,4.176751,3.213423,3.213423,3.213423,3.213423,True
4,ANKR,2023-09-12 15:27:00,2.463891,2.581463,2.463891,2.463891,2.953410,3.012477,2.522643,2.953410,2.033370,2.150448,1.974932,2.033370,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,XLM,2023-09-12 17:23:00,2.952153,2.952153,2.896538,2.936257,2.936257,2.960103,2.904479,2.936257,2.346795,2.362599,2.315201,2.346795,True
57,XRP,2023-09-12 17:23:00,2.570341,2.591999,2.411317,2.591999,2.591999,2.613666,2.591999,2.591999,2.411317,2.432941,2.411317,2.411317,True
58,XTZ,2023-09-12 17:23:00,2.828972,2.828972,2.668802,2.668802,2.828972,2.828972,2.593934,2.593934,2.316795,2.316795,2.316795,2.316795,True
59,ZIL,2023-09-12 17:23:00,2.065837,2.065837,2.065837,2.065837,2.563720,2.631553,2.563720,2.631553,1.998423,2.065837,1.998423,2.065837,True
60,ZRX,2023-09-12 17:23:00,2.827883,2.827883,2.701013,2.701013,2.827883,2.827883,2.764409,2.764409,1.834414,2.236303,1.771592,2.236303,True

2023-09-12 17:24:41,130 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:24:48,635 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [9]:
def resample_ohlc_df(ohlc_df, resample_period, closed_count):
    ohlc_df['count'] = 1
    ohlc_df = ohlc_df.set_index(['base_asset','datetime_now'])
    resampled_df = ohlc_df.groupby('base_asset').resample(resample_period, level='datetime_now').agg({
        'tp_open': 'first',
        'tp_high': 'max',
        'tp_low': 'min',
        'tp_close': 'last',
        'LS_open': 'first',
        'LS_high': 'max',
        'LS_low': 'min',
        'LS_close': 'last',
        'SL_open': 'first',
        'SL_high': 'max',
        'SL_low': 'min',
        'SL_close': 'last',
        'count': 'sum'
    })
    resampled_df = resampled_df.reset_index()
    resampled_df['closed'] = resampled_df['count'].apply(lambda x: True if x==closed_count else False)
    return resampled_df

2023-09-12 15:55:01,008 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 15:55:02,699 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.

In [56]:

def ohlc_min_resample_loader(origin_exchange_code, target_exchange_code, redis_cli, original_period, resample_period, resample_closed_count, loop_downtime_sec=0.01, max_length=300):
    start = time.time()
    resampled_ohlc_history_df = resample_ohlc_df(pickle.loads(redis_cli.get_data(f'{origin_exchange_code}:{target_exchange_code}_{original_period}_kline')), resample_period, closed_count=resample_closed_count)
    redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_{resample_period}_kline', pickle.dumps(resampled_ohlc_history_df))
    print(f"initial generating and storing resampled_ohlc_history_df(length: {len(resampled_ohlc_history_df)}): {time.time()-start}")

    while True:
        time.sleep(loop_downtime_sec)
        original_ohlc_1T_now = pickle.loads(redis_cli.get_data(f'{origin_exchange_code}:{target_exchange_code}_1T_now'))
        try:
            original_ohlc_history_last_datetime = pickle.loads(redis_cli.get_data(f'{origin_exchange_code}:{target_exchange_code}_{original_period}_kline')).iloc[-1]['datetime_now']
        except TypeError:
            print(f"original_ohlc_history_last_datetime is None")
            continue
        resampled_ohlc_history_df = pickle.loads(redis_cli.get_data(f'{origin_exchange_code}:{target_exchange_code}_{resample_period}_kline'))
        resampled_ohlc_history_df = resampled_ohlc_history_df[resampled_ohlc_history_df['closed']==True]
        resampled_ohlc_history_last_datetime = resampled_ohlc_history_df.iloc[-1]['datetime_now']
        datetime_now = datetime.datetime.now()
        # print(f"(original_ohlc_history_last_datetime.minute + int(original_period[:-1])) % int(resample_period[:-1]): {(original_ohlc_history_last_datetime.minute + int(original_period[:-1])) % int(resample_period[:-1])}")
        # print(f"datetime_now - resampled_ohlc_history_last_datetime > datetime.timedelta(minutes=int(resample_period[:-1])*2): {datetime_now - resampled_ohlc_history_last_datetime > datetime.timedelta(minutes=int(resample_period[:-1])*2)}")
        # print(f"datetime_now: {datetime_now}")
        # print(f"resampled_ohlc_history_last_datetime: {resampled_ohlc_history_last_datetime}")
        # print(f"(datetime_now - resampled_ohlc_history_last_datetime): {datetime_now - resampled_ohlc_history_last_datetime}")
        if ((original_ohlc_history_last_datetime.minute + int(original_period[:-1])) % int(resample_period[:-1]) == 0 and
            (datetime_now - resampled_ohlc_history_last_datetime) > datetime.timedelta(minutes=int(resample_period[:-1])*2)):
            # concatenate fetched resampled_ohlc_history_df and newly generated resampled_ohlc_history_df
            start = time.time()
            resampled_ohlc_history_df = pd.concat([resampled_ohlc_history_df, resample_ohlc_df(pickle.loads(redis_cli.get_data(f'{origin_exchange_code}:{target_exchange_code}_{original_period}_kline')), resample_period, closed_count=resample_closed_count)], axis=0, ignore_index=True)
            resampled_ohlc_history_df = resampled_ohlc_history_df.drop_duplicates(subset=['base_asset', 'datetime_now'], keep='last').groupby('base_asset').tail(max_length)
            print(f"resampling ohlc_df(length: {len(resampled_ohlc_history_df)}): {time.time()-start}")
            # Save into the Redis DB
            start = time.time()
            redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_{resample_period}_kline', pickle.dumps(resampled_ohlc_history_df))
            print(f"redis saving {origin_exchange_code}:{target_exchange_code}_{resample_period}_kline time: {time.time()-start}")
        else:
            # generate resampled_ohlc_now_df
            resampled_ohlc_last_df = resampled_ohlc_history_df.groupby('base_asset').tail(1).reset_index(drop=True).copy()
            # Compare it to thr original_ohlc_1T_now
            resampled_ohlc_last_df.loc[:, 'tp_high'] = np.where(resampled_ohlc_last_df['tp_high']>original_ohlc_1T_now['tp_high'], resampled_ohlc_last_df['tp_high'], original_ohlc_1T_now['tp_high'])
            resampled_ohlc_last_df.loc[:, 'tp_low'] = np.where(resampled_ohlc_last_df['tp_low']<original_ohlc_1T_now['tp_low'], resampled_ohlc_last_df['tp_low'], original_ohlc_1T_now['tp_low'])
            resampled_ohlc_last_df.loc[:, 'tp_close'] = original_ohlc_1T_now['tp_close']
            resampled_ohlc_last_df.loc[:, 'LS_high'] = np.where(resampled_ohlc_last_df['LS_high']>original_ohlc_1T_now['LS_high'], resampled_ohlc_last_df['LS_high'], original_ohlc_1T_now['LS_high'])
            resampled_ohlc_last_df.loc[:, 'LS_low'] = np.where(resampled_ohlc_last_df['LS_low']<original_ohlc_1T_now['LS_low'], resampled_ohlc_last_df['LS_low'], original_ohlc_1T_now['LS_low'])
            resampled_ohlc_last_df.loc[:, 'LS_close'] = original_ohlc_1T_now['LS_close']
            resampled_ohlc_last_df.loc[:, 'SL_high'] = np.where(resampled_ohlc_last_df['SL_high']>original_ohlc_1T_now['SL_high'], resampled_ohlc_last_df['SL_high'], original_ohlc_1T_now['SL_high'])
            resampled_ohlc_last_df.loc[:, 'SL_low'] = np.where(resampled_ohlc_last_df['SL_low']<original_ohlc_1T_now['SL_low'], resampled_ohlc_last_df['SL_low'], original_ohlc_1T_now['SL_low'])
            resampled_ohlc_last_df.loc[:, 'SL_close'] = original_ohlc_1T_now['SL_close']
            resampled_ohlc_last_df.loc[:, 'datetime_now'] = resampled_ohlc_last_df['datetime_now'] + datetime.timedelta(minutes=int(resample_period[:-1]))
            # Save into the Redis DB
            redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_{resample_period}_now', pickle.dumps(resampled_ohlc_last_df))

redis_cli = InitRedis()
original_period= '1T'
resample_period = '5T'
resample_closed_count = 5
ohlc_loader_proc = Process(target=ohlc_min_resample_loader, args=("BINANCE_USD_M/USDT", "UPBIT_SPOT/KRW", redis_cli, original_period, resample_period, resample_closed_count), daemon=True)
ohlc_loader_proc.start()

initial generating and storing resampled_ohlc_history_df(length: 976): 1.2660799026489258

2023-09-12 16:44:20,509 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 16:44:35,791 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 16:44:38,502 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.

resampling ohlc_df(length: 976): 1.1915650367736816
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0006897449493408203
resampling ohlc_df(length: 1037): 1.2497236728668213
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0007913112640380859
resampling ohlc_df(length: 1098): 1.1845455169677734
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0007405281066894531
resampling ohlc_df(length: 1159): 1.15960693359375
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0005769729614257812
resampling ohlc_df(length: 1220): 1.2782304286956787
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.001220703125
resampling ohlc_df(length: 1281): 1.195591688156128
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0007824897766113281
resampling ohlc_df(length: 1342): 1.2529311180114746
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0006525516510009766
resampling ohlc_df(length: 1403): 1.3245313167572021
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0005609989166259766
resampling ohlc_df(length: 1464): 1.2519521713256836
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.000579833984375
resampling ohlc_df(length: 1525): 1.258800745010376
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.00066375732421875
resampling ohlc_df(length: 1586): 0.951866865158081
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0007796287536621094
resampling ohlc_df(length: 1647): 0.9902565479278564
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0005109310150146484
resampling ohlc_df(length: 1708): 0.9586758613586426
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0007832050323486328
resampling ohlc_df(length: 1769): 0.9537794589996338
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0006933212280273438
resampling ohlc_df(length: 1830): 1.4657337665557861
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0008249282836914062
resampling ohlc_df(length: 1891): 1.3609769344329834
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0006911754608154297
resampling ohlc_df(length: 1952): 1.2550067901611328
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0007078647613525391
resampling ohlc_df(length: 2013): 1.2585208415985107
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0006847381591796875
resampling ohlc_df(length: 2074): 1.32295823097229
redis saving BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline time: 0.0008857250213623047

Process Process-49:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 192, in _read_from_socket
    data = self._sock.recv(socket_read_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_227652/3338402716.py", line 50, in ohlc_min_resample_loader
    redis_cli.set_data(f'{origin_exchange_code}:{target_exchange_code}_{resample_period}_now', pickle.dumps(resampled_ohlc_last_df))
  File "/home/kp_info_loader/etc/redis_connector/redis_connector.py", line 12, in set_data
    self.redis_conn.set(key_name, value)
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 2220, in set
    return self.execute_command("SET", *pieces, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1242, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1228, in _disconnect_raise
    raise error
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 830, in read_response
    raise ConnectionError(f"Error while reading from {hosterr}" f" : {e.args}")
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (104, 'Connection reset by peer')

In [55]:
ohlc_loader_proc.terminate()

2023-09-12 16:44:05,239 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 16:44:07,614 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.

In [70]:
ohlc_loader_proc.is_alive()

True

2023-09-12 16:59:37,058 - update_dollar - INFO - fetch_dollar|Dollar price (1328.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1328.0 KRW) has been updated.
2023-09-12 16:59:40,834 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [63]:
resample_ohlc_df(pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline')), '5T', 5)

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,count,closed
0,1INCH,2023-09-12 15:25:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,1,False
1,1INCH,2023-09-12 15:30:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,1,False
2,1INCH,2023-09-12 15:35:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.617920,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,1,False
3,1INCH,2023-09-12 15:40:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,1,False
4,1INCH,2023-09-12 15:45:00,1.424754,1.424754,1.099675,1.099675,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,ZRX,2023-09-12 16:25:00,2.062434,2.594373,2.062434,2.466926,2.594373,2.998786,2.594373,2.934812,2.062434,2.466926,2.062434,2.403322,1,False
1033,ZRX,2023-09-12 16:30:00,2.466926,2.934812,2.403322,2.743365,2.934812,2.934812,2.679707,2.743365,2.403322,2.403322,2.149691,2.212981,1,False
1034,ZRX,2023-09-12 16:35:00,2.743365,2.743365,2.616128,2.743365,2.743365,2.807101,2.679707,2.743365,2.212981,2.276349,2.149691,2.212981,1,False
1035,ZRX,2023-09-12 16:40:00,2.743365,2.743365,2.616128,2.743365,2.743365,2.807101,2.616128,2.807101,2.212981,2.276349,2.086480,2.276349,1,False
1036,ZRX,2023-09-12 16:45:00,2.743365,2.807101,2.616128,2.616128,2.807101,2.870917,2.679707,2.679707,2.276349,2.339796,2.149691,2.149691,1,False

In [96]:
temp = pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline'))
temp

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,count,closed
1220,1INCH,2023-09-12 15:25:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,3,False
1221,1INCH,2023-09-12 15:30:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,5,True
1222,1INCH,2023-09-12 15:35:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.617920,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,5,True
1223,1INCH,2023-09-12 15:40:00,1.424754,1.424754,1.424754,1.424754,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,5,True
1224,1INCH,2023-09-12 15:45:00,1.424754,1.424754,1.099675,1.099675,1.293262,1.293262,1.293262,1.293262,0.924989,0.924989,0.924989,0.924989,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2618,ZRX,2023-09-12 16:55:00,2.403322,2.466926,2.212981,2.276349,2.934812,2.934812,2.743365,2.743365,2.403322,2.403322,2.212981,2.212981,5,True
2619,ZRX,2023-09-12 17:00:00,2.276349,2.276349,2.086480,2.149691,2.743365,2.743365,2.552628,2.679707,2.212981,2.212981,2.023347,2.149691,5,True
2620,ZRX,2023-09-12 17:05:00,2.149691,2.212981,2.086480,2.086480,2.679707,2.679707,2.616128,2.616128,2.149691,2.149691,2.086480,2.086480,5,True
2621,ZRX,2023-09-12 17:10:00,2.086480,2.616128,2.086480,2.299412,2.616128,3.082565,2.489207,2.827883,2.086480,2.552628,1.834414,2.299412,5,True
2622,ZRX,2023-09-12 17:15:00,2.299412,2.299412,2.047443,2.173272,2.827883,2.827883,2.574456,2.701013,2.299412,2.299412,2.047443,2.173272,5,True

In [97]:
temp = pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_now'))
temp[temp['base_asset']=='XRP']

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,count,closed
57,XRP,2023-09-12 17:20:00,2.311162,2.591999,2.182062,2.527053,2.469784,2.591999,2.340484,2.527053,2.289622,2.411317,2.160577,2.3465,5,True

2023-09-12 17:25:03,893 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:25:11,901 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:25:19,149 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:25:34,419 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:25:42,775 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:25:49,666 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:26:04,940 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:26:13,660 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:26:20,209 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:26:35,472 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:26:44,522 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:26:50,735 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:27:05,979 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:27:16,483 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:27:21,242 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:27:36,488 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:27:47,364 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:27:51,769 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:28:07,074 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:28:18,228 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:28:22,609 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:28:37,885 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:28:49,286 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:28:53,142 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:29:08,412 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:29:20,214 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:29:23,682 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:29:38,917 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:29:51,194 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:29:54,188 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:30:09,459 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:30:22,065 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:30:24,713 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:30:39,984 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:30:52,997 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:30:55,253 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:31:10,506 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:31:23,940 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:31:25,762 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:31:41,032 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:31:54,753 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:31:56,321 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:32:11,582 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:32:25,730 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:32:26,848 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:32:42,378 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:32:57,568 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:32:57,663 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:33:13,253 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:33:28,626 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:33:28,991 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:33:44,705 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:33:59,466 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:34:00,161 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:34:15,794 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:34:30,368 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:34:31,313 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:34:46,600 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:35:01,303 - update_dollar - INFO - fetch_dollar|Dollar price (1327.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1327.0 KRW) has been updated.
2023-09-12 17:35:02,063 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:35:17,308 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-09-12 17:35:18,350 - kimp_bot_core - ERROR - update_exchange_info_as_df|name:binance_spot_info_df, Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kp_info_loader/kp_info_loader_core.py", line 98, in update_exchange_info_as_df
    self.info_dict[data_name] = self.binance_adaptor.spot_exchange_info()
  File "/home/kp_info_loader/exchange_plugin/binance_plug.py", line 51, in spot_exchange_info
    df = pd.DataFrame(self.pub_client.get_exchange_info()['symbols'])
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 503, in get_exchange_info
    return self._get('exchangeInfo', version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 415, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 378, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/binance/client.py", line 358, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

[ERROR] update_exchange_info_as_df|name:binance_spot_info_df, Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)

In [204]:
core.check_status(print_result=True)

[UPBIT SPOT]1th_ticker_proc status: True
[UPBIT SPOT]1th_orderbook_proc status: True
[UPBIT SPOT]2th_ticker_proc status: True
[UPBIT SPOT]2th_orderbook_proc status: True
[UPBIT SPOT]3th_ticker_proc status: True
[UPBIT SPOT]3th_orderbook_proc status: True
[UPBIT SPOT]4th_ticker_proc status: True
[UPBIT SPOT]4th_orderbook_proc status: True
[UPBIT SPOT]5th_ticker_proc status: True
[UPBIT SPOT]5th_orderbook_proc status: True
[UPBIT SPOT]6th_ticker_proc status: True
[UPBIT SPOT]6th_orderbook_proc status: True

[BINANCE SPOT]1th_price_proc status: True
[BINANCE SPOT]2th_price_proc status: True
[BINANCE SPOT]3th_price_proc status: True
[BINANCE SPOT]4th_price_proc status: True
[BINANCE SPOT]5th_price_proc status: True
[BINANCE SPOT]6th_price_proc status: True

[BINANCE USD-M]1th_price_proc status: True
[BINANCE USD-M]2th_price_proc status: True
[BINANCE USD-M]3th_price_proc status: True
[BINANCE USD-M]4th_price_proc status: True
[BINANCE USD-M]5th_price_proc status: True
[BINANCE USD-M]6th_price_proc status: True
[BINANCE USD-M]liquidation_proc status: True

[BINANCE COIN-M]1th_price_proc status: True
[BINANCE COIN-M]2th_price_proc status: True
[BINANCE COIN-M]3th_price_proc status: True
[BINANCE COIN-M]4th_price_proc status: True
[BINANCE COIN-M]5th_price_proc status: True
[BINANCE COIN-M]6th_price_proc status: True
[BINANCE COIN-M]liquidation_proc status: True

True

In [247]:
pickle.loads(redis_cli.get_data('BINANCE_USD_M/USDT:UPBIT_SPOT/KRW_5T_kline'))

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,count,closed
0,1INCH,2023-09-30,-0.200642,2.399993,-0.525722,1.424754,-0.005370,2.591893,-0.330028,1.293262,-0.373082,2.223059,-0.697599,0.924989,300,False
1,AAVE,2023-09-30,3.178788,5.433431,2.947543,4.132675,3.014878,5.251195,2.726320,4.039255,2.865272,5.158860,2.634470,3.961578,300,False
2,ADA,2023-09-30,1.272573,4.034552,0.965686,2.500119,1.537981,3.992072,1.231220,2.458265,1.189901,3.642990,0.883265,2.109809,300,False
3,ALGO,2023-09-30,2.482820,5.023716,1.635854,3.329785,3.329785,5.023716,2.482820,4.176751,2.367411,4.059435,1.521400,3.213423,300,False
4,ANKR,2023-09-30,2.464140,3.259739,1.555853,2.522643,2.959914,3.319914,1.901673,2.581463,2.464140,2.822198,1.417748,2.091875,300,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,XLM,2023-09-30,2.992724,3.185165,1.312556,1.692207,3.000793,3.209329,1.869420,2.274560,2.404194,2.614902,1.289404,1.692207,300,False
118,XRP,2023-09-30,0.709905,2.899250,0.397141,0.866287,0.688945,2.877835,0.532596,1.001644,0.511678,2.700113,0.355361,0.824311,300,False
119,XTZ,2023-09-30,-1.078651,0.847653,-1.531899,-0.512091,-0.965339,0.847653,-1.305275,-0.512091,-1.227629,0.582633,-1.680194,-0.888205,300,False
120,ZIL,2023-09-30,3.241642,3.241642,1.468661,2.218773,3.241642,3.517874,1.865540,2.782869,2.671976,2.809054,1.271379,2.218773,300,False
121,ZRX,2023-09-30,2.983616,3.244499,0.990327,2.275271,3.048713,3.375437,1.881097,2.275271,2.509037,2.833844,1.360255,1.747421,300,False

2023-09-12 15:29:04,484 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
[INFO] self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API