In [1]:
import okx.client as client
import okx.websocket.WsPublic as WsPublic
import pandas as pd
import json
import time
import datetime

In [2]:
api_key="fcb66a6e-0443-4743-8d9b-61caf7eab662"
api_secret_key="0029E09874B38F5AC7E68E9DFC348667"

In [53]:
import okx.MarketData as MarketData
flag = "0"  # live trading: 0, demo trading: 1

marketDataAPI = MarketData.MarketAPI(flag = flag)
result = marketDataAPI.get_tickers(instType = "SWAP")
# print(result)
test = pd.DataFrame(result['data'])
test[test['instId'].str.contains("ETH")]

header:  {'Content-Type': 'application/json', 'x-simulated-trading': '0'}
domain: https://www.okx.com
url: /api/v5/market/tickers?instType=SWAP

,instType,instId,last,lastSz,askPx,askSz,bidPx,bidSz,open24h,high24h,low24h,volCcy24h,vol24h,ts,sodUtc0,sodUtc8
49,SWAP,ETH-USDT-SWAP,1854.99,38,1855,8782,1854.99,1379,1864.99,1893.07,1837,1992042.3,19904170,1685599476547,1873.4,1858.3
80,SWAP,ETHW-USDT-SWAP,1.899,191,1.899,8245,1.898,1300,1.971,1.984,1.835,2018914.4,20187053,1685599476413,1.935,1.934
123,SWAP,ETH-USD-SWAP,1855.63,9,1855.63,12245,1855.62,133,1864.55,1891.95,1838,185271.4382,34509758,1685599476704,1874.31,1859.16
124,SWAP,ETH-USDC-SWAP,1855.99,410,1855.52,820,1855.51,410,1863.74,1889,1839.68,1160.981,1160070,1685599476708,1874.82,1859.05

In [3]:
import time

from okx.websocket.WsPublic import WsPublic


def publicCallback(message):
    print("publicCallback", message)


if __name__ == '__main__':
    url = "wss://ws.okx.com:8443/ws/v5/public"
    ws = WsPublic(url=url)
    ws.start()
    args = []
    # arg1 = {"channel": "instruments", "instType": "FUTURES"}
    # arg2 = {"channel": "instruments", "instType": "SPOT"}
    arg3 = {"channel": "tickers", "instId": "BTC-USDT"}
    # arg4 = {"channel": "tickers", "instId": "ETH-USDT"}
    # args.append(arg1)
    # args.append(arg2)
    args.append(arg3)
    # args.append(arg4)
    # ws.subscribe(args, publicCallback)
    ws.subscribe([json.dumps({"channel": "tickers", "instId": "BTC-USDT"}], publicCallback)
    time.sleep(10)
    print("-----------------------------------------unsubscribe--------------------------------------------")
    # args2 = [arg4]
    # ws.unsubscribe(args2, publicCallback)
    # time.sleep(10)
    print("-----------------------------------------unsubscribe all--------------------------------------------")
    # args3 = [arg1, arg2, arg3]
    
    # ws.unsubscribe(args3, publicCallback)
    ws.unsubscribe(args, publicCallback)

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/okx/websocket/WsConnectManager.py", line 124, in run
    reactor.run(installSignalHandlers=False)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/base.py", line 1282, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/base.py", line 1262, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/base.py", line 765, in startRunning

TypeError: string indices must be integers

    raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable

In [5]:
import json
import websocket

data = {
      "op": "subscribe",
      "args": [
        {
          "channel": 'tickers',
          "instId": "BTC-USDT-SWAP",
        },
        {
          "channel": 'tickers',
          "instId": "ETH-USDT-SWAP",
        }
      ]
    }

# data = {
#       "op": "login",
#       "args": [
#         {
#           "apiKey": '',
#           "passphrase": '',
#           "timestamp": '',
#           "sign": ''
#         }
#       ]
#     }

def on_message(ws, message):
    message_dict = json.loads(message)
    # if message_dict['cd'] == 'KRW-BCH':                                                         # test
    #     print(message_dict['tp'], datetime.datetime.fromtimestamp(message_dict['tms']/1000))    # test
    # upbit_result_dict[message_dict['cd']] = message_dict
    if 'data' in message_dict.keys():
      print(message_dict)

def on_error(ws, error):
    # print(f'upbit_websocket on_error executed!')
    print(error)
    # price_websocket_logger.error(f'upbit_orderbook_ticker_websocket|upbit_websocket on_error executed!\n Error: {error}')
    pass

def on_close(ws, close_status_code, close_msg):
    print(f"\n\n### closed ###\nclose_msg: {close_msg}\nclose_status_code: {close_status_code}")
    # price_websocket_logger.info(f"upbit_orderbook_ticker_websocket|\n\n### closed ###\nclose_msg: {close_msg}\nclose_status_code: {close_status_code}")

def on_open(ws):
    print(f'on_open started')
    # price_websocket_logger.info(f'upbit_orderbook_ticker_websocket|upbit_websocket started')
    ws.send(json.dumps(data))

# websocket.enableTrace(False)
ws = websocket.WebSocketApp("wss://ws.okx.com:8443/ws/v5/public",
                        on_open=on_open,
                        on_message=on_message,
                        on_error=on_error,
                        on_close=on_close)
ws.run_forever()

on_open started
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '5', 'askPx': '26855.4', 'askSz': '242', 'bidPx': '26855.3', 'bidSz': '371', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82870.88', 'vol24h': '8263714', 'ts': '1685937412105'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '8', 'askPx': '1870.25', 'askSz': '1187', 'bidPx': '1870.24', 'bidSz': '346', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483134.9', 'vol24h': '14776483', 'ts': '1685937412113'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '20', 'askPx': '1870.25', 'askSz': '1144', 'bidPx': '1870.24', 'bidSz': '369', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483136.9', 'vol24h': '14776503', 'ts': '1685937413011'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '5', 'askPx': '26855.4', 'askSz': '269', 'bidPx': '26855.3', 'bidSz': '323', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82870.88', 'vol24h': '8263714', 'ts': '1685937413078'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '50', 'askPx': '1870.25', 'askSz': '1121', 'bidPx': '1870.24', 'bidSz': '369', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483141.9', 'vol24h': '14776553', 'ts': '1685937413112'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '20', 'askPx': '1870.25', 'askSz': '1121', 'bidPx': '1870.24', 'bidSz': '355', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483144.9', 'vol24h': '14776583', 'ts': '1685937413214'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '3', 'askPx': '26855.4', 'askSz': '309', 'bidPx': '26855.3', 'bidSz': '323', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82870.91', 'vol24h': '8263717', 'ts': '1685937413803'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '20', 'askPx': '1870.25', 'askSz': '1118', 'bidPx': '1870.24', 'bidSz': '256', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483144.9', 'vol24h': '14776583', 'ts': '1685937414149'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.3', 'lastSz': '3', 'askPx': '26855.4', 'askSz': '269', 'bidPx': '26855.3', 'bidSz': '321', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82870.94', 'vol24h': '8263720', 'ts': '1685937414371'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '3', 'askPx': '1870.25', 'askSz': '1117', 'bidPx': '1870.24', 'bidSz': '309', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483145.2', 'vol24h': '14776586', 'ts': '1685937414759'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '7', 'askPx': '1870.25', 'askSz': '1117', 'bidPx': '1870.24', 'bidSz': '296', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483146.5', 'vol24h': '14776599', 'ts': '1685937414968'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '7', 'askPx': '1870.25', 'askSz': '1117', 'bidPx': '1870.24', 'bidSz': '277', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483146.5', 'vol24h': '14776599', 'ts': '1685937415069'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.3', 'lastSz': '3', 'askPx': '26855.4', 'askSz': '271', 'bidPx': '26855.3', 'bidSz': '312', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82870.94', 'vol24h': '8263720', 'ts': '1685937415068'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '15', 'askPx': '26855.4', 'askSz': '385', 'bidPx': '26855.3', 'bidSz': '307', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.09', 'vol24h': '8263735', 'ts': '1685937415412'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '2', 'askPx': '1870.25', 'askSz': '1444', 'bidPx': '1870.24', 'bidSz': '154', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483146.7', 'vol24h': '14776601', 'ts': '1685937415468'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '1', 'askPx': '26855.4', 'askSz': '307', 'bidPx': '26855.3', 'bidSz': '307', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.1', 'vol24h': '8263736', 'ts': '1685937415964'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '2', 'askPx': '1870.25', 'askSz': '1287', 'bidPx': '1870.24', 'bidSz': '19', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483146.7', 'vol24h': '14776601', 'ts': '1685937416069'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '1', 'askPx': '26855.4', 'askSz': '491', 'bidPx': '26855.3', 'bidSz': '150', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.1', 'vol24h': '8263736', 'ts': '1685937416068'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '2', 'askPx': '1870.25', 'askSz': '1650', 'bidPx': '1870.24', 'bidSz': '17', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483147', 'vol24h': '14776604', 'ts': '1685937416204'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '8', 'askPx': '1870.25', 'askSz': '1623', 'bidPx': '1870.24', 'bidSz': '17', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483149.3', 'vol24h': '14776627', 'ts': '1685937416511'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '2', 'askPx': '1870.25', 'askSz': '1525', 'bidPx': '1870.24', 'bidSz': '40', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483149.5', 'vol24h': '14776629', 'ts': '1685937416713'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '5', 'askPx': '1870.25', 'askSz': '1498', 'bidPx': '1870.24', 'bidSz': '35', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483150', 'vol24h': '14776634', 'ts': '1685937416835'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '1', 'askPx': '1870.25', 'askSz': '1498', 'bidPx': '1870.24', 'bidSz': '34', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483150.1', 'vol24h': '14776635', 'ts': '1685937416966'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.24', 'lastSz': '1', 'askPx': '1870.25', 'askSz': '1525', 'bidPx': '1870.24', 'bidSz': '34', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483150.1', 'vol24h': '14776635', 'ts': '1685937417074'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '1', 'askPx': '26855.4', 'askSz': '479', 'bidPx': '26855.3', 'bidSz': '112', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.1', 'vol24h': '8263736', 'ts': '1685937417068'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '5', 'askPx': '1870.25', 'askSz': '1520', 'bidPx': '1870.24', 'bidSz': '34', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483150.6', 'vol24h': '14776640', 'ts': '1685937417196'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.3', 'lastSz': '18', 'askPx': '26855.4', 'askSz': '634', 'bidPx': '26855.3', 'bidSz': '93', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.28', 'vol24h': '8263754', 'ts': '1685937417513'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '3', 'askPx': '1870.25', 'askSz': '1399', 'bidPx': '1870.24', 'bidSz': '326', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483150.9', 'vol24h': '14776643', 'ts': '1685937417792'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '5', 'askPx': '26855.4', 'askSz': '642', 'bidPx': '26855.3', 'bidSz': '93', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.33', 'vol24h': '8263759', 'ts': '1685937417804'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.4', 'lastSz': '5', 'askPx': '26855.4', 'askSz': '642', 'bidPx': '26855.3', 'bidSz': '119', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82871.33', 'vol24h': '8263759', 'ts': '1685937418013'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.3', 'lastSz': '7', 'askPx': '26855.4', 'askSz': '642', 'bidPx': '26855.3', 'bidSz': '42', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82872.1', 'vol24h': '8263836', 'ts': '1685937418114'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.25', 'lastSz': '3', 'askPx': '1870.25', 'askSz': '1092', 'bidPx': '1870.24', 'bidSz': '531', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483150.9', 'vol24h': '14776643', 'ts': '1685937418114'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.1', 'lastSz': '1', 'askPx': '26855.4', 'askSz': '952', 'bidPx': '26855.1', 'bidSz': '6', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82872.4', 'vol24h': '8263866', 'ts': '1685937418268'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26855.1', 'lastSz': '6', 'askPx': '26855.2', 'askSz': '1056', 'bidPx': '26854.2', 'bidSz': '13', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82872.46', 'vol24h': '8263872', 'ts': '1685937418383'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1870.21', 'lastSz': '1', 'askPx': '1870.22', 'askSz': '1753', 'bidPx': '1870.19', 'bidSz': '20', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483206.7', 'vol24h': '14777201', 'ts': '1685937418378'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1869.9', 'lastSz': '1', 'askPx': '1869.9', 'askSz': '2677', 'bidPx': '1869.89', 'bidSz': '339', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483252.6', 'vol24h': '14777660', 'ts': '1685937418478'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26852', 'lastSz': '1', 'askPx': '26852.1', 'askSz': '1499', 'bidPx': '26852', 'bidSz': '160', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82872.47', 'vol24h': '8263873', 'ts': '1685937418605'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1869.89', 'lastSz': '5', 'askPx': '1869.9', 'askSz': '2303', 'bidPx': '1869.89', 'bidSz': '814', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483253.1', 'vol24h': '14777665', 'ts': '1685937418702'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1869.9', 'lastSz': '5', 'askPx': '1869.9', 'askSz': '2108', 'bidPx': '1869.89', 'bidSz': '767', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483253.6', 'vol24h': '14777670', 'ts': '1685937418907'}]}
{'arg': {'channel': 'tickers', 'instId': 'BTC-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'BTC-USDT-SWAP', 'last': '26852', 'lastSz': '1', 'askPx': '26852.1', 'askSz': '1260', 'bidPx': '26852', 'bidSz': '135', 'open24h': '27066.9', 'high24h': '27478.8', 'low24h': '26795', 'sodUtc0': '27116.5', 'sodUtc8': '27176.1', 'volCcy24h': '82872.47', 'vol24h': '8263873', 'ts': '1685937419068'}]}
{'arg': {'channel': 'tickers', 'instId': 'ETH-USDT-SWAP'}, 'data': [{'instType': 'SWAP', 'instId': 'ETH-USDT-SWAP', 'last': '1869.9', 'lastSz': '5', 'askPx': '1869.9', 'askSz': '2070', 'bidPx': '1869.89', 'bidSz': '803', 'open24h': '1894.4', 'high24h': '1914.89', 'low24h': '1867', 'sodUtc0': '1889.89', 'sodUtc8': '1901.39', 'volCcy24h': '1483253.6', 'vol24h': '14777670', 'ts': '1685937419113'}]}



### closed ###
close_msg: None
close_status_code: None

False

In [11]:
ws.close()

In [66]:
from okx.Account import AccountAPI
from okx.BlockTrading import BlockTradingAPI
from okx.Convert import ConvertAPI
from okx.Earning import EarningAPI
from okx.FDBroker import FDBrokerAPI
from okx.Funding import FundingAPI
from okx.Grid import GridAPI
from okx.MarketData import MarketAPI
from okx.NDBroker import NDBrokerAPI
from okx.PublicData import PublicAPI
from okx.Status import StatusAPI
from okx.SubAccount import SubAccountAPI
from okx.Trade import TradeAPI
from okx.TradingData import TradingDataAPI

class OkxClient:
    def __init__(self, okx_api_key='-1', okx_secret_key='-1', passphrase='-1', demo_trading='0', debug=False):
        self.AccountAPI = AccountAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.BlockTradingAPI = BlockTradingAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.ConvertAPI = ConvertAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.EarningAPI = EarningAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.FDBrokerAPI = FDBrokerAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.FundingAPI = FundingAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.GridAPI = GridAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.MarketAPI = MarketAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.NDBrokerAPI = NDBrokerAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.PublicAPI = PublicAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.StatusAPI = StatusAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.SubAccountAPI = SubAccountAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.TradeAPI = TradeAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)
        self.TradingDataAPI = TradingDataAPI(api_key=okx_api_key, api_secret_key=okx_secret_key, passphrase=passphrase, flag=demo_trading, debug=debug)

In [120]:
okx_client = OkxClient(okx_api_key=api_key, okx_secret_key=api_secret_key, passphrase='121431Rn!!')

In [125]:
pd.DataFrame(okx_client.AccountAPI.get_account_balance()['data'][0]['details'])

,availBal,availEq,cashBal,ccy,crossLiab,disEq,eq,eqUsd,fixedBal,frozenBal,...,maxLoan,mgnRatio,notionalLever,ordFrozen,spotInUseAmt,stgyEq,twap,uTime,upl,uplLiab
0,0.25781735586,,0.25781735586,USDT,,0.2578792320254064,0.25781735586,0.2578792320254064,0,0,...,,,,0,,0,0,1685617518274,,

In [126]:
okx_client.AccountAPI.get_account_balance()['data'][0]['details']

[{'availBal': '0.25781735586',
  'availEq': '',
  'cashBal': '0.25781735586',
  'ccy': 'USDT',
  'crossLiab': '',
  'disEq': '0.2578766538518478',
  'eq': '0.25781735586',
  'eqUsd': '0.2578766538518478',
  'fixedBal': '0',
  'frozenBal': '0',
  'interest': '',
  'isoEq': '',
  'isoLiab': '',
  'isoUpl': '',
  'liab': '',
  'maxLoan': '',
  'mgnRatio': '',
  'notionalLever': '',
  'ordFrozen': '0',
  'spotInUseAmt': '',
  'stgyEq': '0',
  'twap': '0',
  'uTime': '1685617518274',
  'upl': '',
  'uplLiab': ''}]

In [124]:
pd.DataFrame(okx_client.FundingAPI.get_balances()['data'])

   availBal       bal  ccy frozenBal
0  0.000749  0.000749  XRP         0

In [78]:
datetime.datetime.fromtimestamp(1618795886000/1000)

datetime.datetime(2021, 4, 19, 10, 31, 26)