In [1]:
import os
import json
import sys
import argparse
import datetime
import pandas as pd
from kimp_bot_core import InitKimpCore
from exchange_plugin.common_info import InitCommonInfo
from monitor_engine.kimp_core_monitor import InitKimpCoreMonitor
from etc.db_handler.create_schema_tables import InitDBClient
# from trigger_engine.snatcher import InitSnatcher

# for jupyter notebook
import nest_asyncio
nest_asyncio.apply()

[WARNING] upbit-client is currently a newer version: 1.3.4.1
Please update to the latest version using the pip command:`pip install --upgrade upbit-client`

In [2]:
with open("/home/kimp_bot_core_okx/kimp_bot_config.json") as f:
    config = json.load(f)
proc_n = 1
# node = config['node']
node = 'kp_trade_v2_okx_dev'
monitor_bot_name = config['monitor_setting']['monitor_bot']
monitor_bot_token = config['telegram_bot_setting'][monitor_bot_name]
monitor_bot_api_url = config['monitor_setting']['monitor_bot_api_url']
admin_id = config['telegram_admin_id']['charlie1155']

master_flag = config['node_settings'][node]['MASTER']
local_db_dict = config['database_setting'][config['node_settings'][node]['local_db_settings']]
local_db_dict['database'] = node
remote_db_dict = config['database_setting'][config['node_settings'][node]['remote_db_settings']]
if master_flag:
    remote_db_dict['database'] = node
else:
    remote_db_dict['database'] = config['node_settings'][node].get('reference_node')
encryption_key = config['encryption_key']

# Create database and tables if not exists
temp_local_db_dict = local_db_dict.copy()
temp_local_db_dict['create_database'] = True
temp_db_client = InitDBClient(**temp_local_db_dict)
temp_db_client.create_all_table(master_node=master_flag)
temp_db_client.curr.close()
temp_db_client.conn.close()


my_okx_demo_api_key = "bbb8a09a-6ea2-4686-add5-1095c918b7f4"
my_okx_demo_secret_key = "FBEAD86057449BAEC3FFA8A80CE76E4F"
my_okx_demo_passphrase = "121431Rn!!"

In [3]:
kimp_core = InitKimpCore(proc_n, node, admin_id, okx_demo_trading='1')
# kimp_core.set_monitor_bot_token(monitor_bot_token)
# kimp_core.set_monitor_api_url(monitor_bot_api_url)
# kimp_core.monitor_websocket()
# InitKimpCoreMonitor("/home/kimp_bot_core/loggers/logs/", 'test', proc_n, kimp_core.get_kimp_df, kimp_core.get_dollar_dict, monitor_bot_token, monitor_bot_api_url)

2023-06-26 15:53:56,271 - kimp_bot_core - INFO - InitKimpCore|InitKimpCore initiated with proc_n=1
[INFO] InitKimpCore|InitKimpCore initiated with proc_n=1
2023-06-26 15:53:56,396 - okx_plug - INFO - okx_plug_logger started.
[INFO] okx_plug_logger started.
2023-06-26 15:53:57,223 - upbit_plug - INFO - upbit_plug_logger started.
[INFO] upbit_plug_logger started.
2023-06-26 15:53:57,744 - price_websocket - INFO - okx_upbit_websocket|price_websocket.okx_upbit_websocket executed
[INFO] okx_upbit_websocket|price_websocket.okx_upbit_websocket executed
2023-06-26 15:53:57,816 - price_websocket - INFO - okx_ticker_websocket|1th okx_ticker_proc started.
[INFO] okx_ticker_websocket|1th okx_ticker_proc started.
2023-06-26 15:53:58,208 - price_websocket - INFO - okx_ticker_websocket|okx_websocket started
[INFO] okx_ticker_websocket|okx_websocket started
2023-06-26 15:53:58,268 - price_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2023-06-26 15:53:58,340 - price_websocket - INFO - upbit_orderbook_ticker_websocket|upbit_websocket started
[INFO] upbit_orderbook_ticker_websocket|upbit_websocket started
2023-06-26 15:53:58,652 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:53:58,778 - price_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-06-26 15:53:58,845 - price_websocket - INFO - upbit_orderbook_ticker_websocket|upbit_websocket started
[INFO] upbit_orderbook_ticker_websocket|upbit_websocket started

In [4]:
kimp_core.websocket_proc_status(print_status=True)

2023-06-26 15:53:59,758 - price_websocket - INFO - check_proc_status|whole_status_flag_list: [True, True, True]
[INFO] check_proc_status|whole_status_flag_list: [True, True, True]
2023-06-26 15:53:59,760 - price_websocket - INFO - check_proc_status|Integrity Flag: True
[INFO] check_proc_status|Integrity Flag: True

1th okx_ticker_proc status: True
1th upbit_ticker_proc status: True
1th upbit_orderbook_proc status: True

(True,
 'Proc Status\n1th okx_ticker_proc status: True\n1th upbit_ticker_proc status: True\n1th upbit_orderbook_proc status: True')

In [5]:
# kimpcore.stop_monitor_websocket()
# time.sleep(2)
kimp_core.terminate_websocket_procs()

2023-06-26 15:53:59,776 - price_websocket - INFO - terminate_websocket_proc|terminating 1th okx_ticker_proc..
[INFO] terminate_websocket_proc|terminating 1th okx_ticker_proc..
2023-06-26 15:53:59,777 - price_websocket - INFO - terminate_websocket_proc|terminating 1th upbit_ticker_proc..
[INFO] terminate_websocket_proc|terminating 1th upbit_ticker_proc..
2023-06-26 15:53:59,779 - price_websocket - INFO - terminate_websocket_proc|terminating 1th upbit_orderbook_proc..
[INFO] terminate_websocket_proc|terminating 1th upbit_orderbook_proc..
2023-06-26 15:54:01,782 - price_websocket - INFO - terminate_websocket_proc|1th okx_ticker_proc is_alive: False
[INFO] terminate_websocket_proc|1th okx_ticker_proc is_alive: False
2023-06-26 15:54:01,784 - price_websocket - INFO - terminate_websocket_proc|1th upbit_ticker_proc is_alive: False
[INFO] terminate_websocket_proc|1th upbit_ticker_proc is_alive: False
2023-06-26 15:54:01,786 - price_websocket - INFO - terminate_websocket_proc|1th upbit_orderbook_proc is_alive: False
[INFO] terminate_websocket_proc|1th upbit_orderbook_proc is_alive: False

In [6]:
common_info = InitCommonInfo(logging_dir=None, node='test', admin_id=admin_id, local_db_dict=local_db_dict, 
                             remote_db_dict=remote_db_dict, monitor_bot_token=monitor_bot_token, monitor_bot_api_url=monitor_bot_api_url, kimp_core=kimp_core, kline_schema_name='coin_kimp_kline', MASTER=master_flag)

In [7]:
common_info.kimp_history('SHIB', 1)

,datetime_kst,upbit_open,upbit_high,upbit_low,upbit_close,okx_open,okx_high,okx_low,okx_close,okx_volume,...,okx_completed,매매기준율,okx_open_krw,okx_high_krw,okx_low_krw,okx_close_krw,okx_open_kimp,okx_high_kimp,okx_low_kimp,okx_close_kimp
0,2023-06-26 12:35:00,0.0101,0.0101,0.0101,0.0101,0.000008,0.000008,0.000008,0.000008,1534.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
1,2023-06-26 12:36:00,0.0102,0.0102,0.0102,0.0102,0.000008,0.000008,0.000008,0.000008,2605.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
2,2023-06-26 12:37:00,0.0102,0.0102,0.0102,0.0102,0.000008,0.000008,0.000008,0.000008,246.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
3,2023-06-26 12:39:00,0.0102,0.0102,0.0102,0.0102,0.000008,0.000008,0.000008,0.000008,55.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
4,2023-06-26 12:40:00,0.0101,0.0101,0.0101,0.0101,0.000008,0.000008,0.000008,0.000008,1745.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2023-06-26 15:42:00,0.0102,0.0102,0.0102,0.0102,0.000008,0.000008,0.000008,0.000008,197.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
124,2023-06-26 15:43:00,0.0103,0.0103,0.0103,0.0103,0.000008,0.000008,0.000008,0.000008,258.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
125,2023-06-26 15:50:00,0.0103,0.0103,0.0103,0.0103,0.000008,0.000008,0.000008,0.000008,1136.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
126,2023-06-26 15:52:00,0.0102,0.0102,0.0102,0.0102,0.000008,0.000008,0.000008,0.000008,203.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf
127,2023-06-26 15:53:00,0.0102,0.0103,0.0102,0.0103,0.000008,0.000008,0.000008,0.000008,2435.0,...,1.0,1306.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf

2023-06-26 15:54:29,852 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:55:00,883 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:55:32,016 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:56:02,864 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:56:33,697 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:57:04,848 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:57:35,817 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:58:07,092 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:58:37,994 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:59:08,866 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 15:59:40,245 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:00:11,320 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:00:42,499 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:01:13,332 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:01:44,075 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:02:15,151 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:02:46,279 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:03:17,380 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:03:48,172 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:04:19,010 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:04:50,011 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:05:21,463 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:05:52,587 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:06:23,995 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:06:54,792 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:07:25,631 - update_dollar - INFO - fetch_dollar|Dollar price (1305.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1305.5 KRW) has been updated.
2023-06-26 16:07:56,633 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:08:27,922 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:08:59,197 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:09:30,053 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:10:00,925 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:10:31,861 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.

In [17]:
# coin = 'SHIB'
# period = 1
# count = 200

# # upbit = self.upbit_adaptor.upbit_fetch_candle(f'KRW-{coin}'.upper(), period, count)[0]
# upbit = kimp_core.upbit_adaptor.upbit_fetch_candle(f'KRW-{coin}'.upper(), period, count)[0]
# # okx = self.okx_adaptor.okx_fetch_candle(f'{coin}-USDT-SWAP'.upper(), period, count)
# okx = kimp_core.okx_adaptor.okx_fetch_candle(f'{coin}-USDT-SWAP'.upper(), period, count)
# # Fetch dollar data
# # dollar_df = self.fetch_update_dollar_200(use_local_db=False)
# dollar_df = common_info.fetch_update_dollar_200(use_local_db=False)
# # Merge info from upbit and okx
# merged = upbit[['candle_date_time_kst','opening_price','high_price','low_price','trade_price']].merge(okx, how='inner', left_on='candle_date_time_kst', right_on='okx_time')
# merged['date'] = merged['candle_date_time_kst'].apply(lambda x: x.date())
# merged = merged.merge(dollar_df[['날짜','매매기준율']], how='left', left_on='date', right_on='날짜').drop('날짜', axis=1).fillna(method='ffill').fillna(dollar_df.iloc[-1,1])
# merged = merged.rename(columns={'candle_date_time_kst':'datetime_kst','high_price':'upbit_high', 'opening_price':'upbit_open', 'low_price':'upbit_low', 'trade_price':'upbit_close'})
# merged.loc[:,'okx_open':'okx_close'] = merged.loc[:,'okx_open':'okx_close'].astype(float)
# merged = merged.drop(['okx_time','date'], axis=1)
# merged['okx_open_krw'] = merged['okx_open'].multiply(merged['매매기준율'], axis=0)#.round(1)
# merged['okx_high_krw'] = merged['okx_high'].multiply(merged['매매기준율'], axis=0)#.round(1)
# merged['okx_low_krw'] = merged['okx_low'].multiply(merged['매매기준율'], axis=0)#.round(1)
# merged['okx_close_krw'] = merged['okx_close'].multiply(merged['매매기준율'], axis=0)#.round(1)
# merged['okx_open_kimp'] = (merged['upbit_open'] - merged['okx_open_krw'])/merged['okx_open_krw']
# merged['okx_high_kimp'] = (merged['upbit_high'] - merged['okx_high_krw'])/merged['okx_high_krw']
# merged['okx_low_kimp'] = (merged['upbit_low'] - merged['okx_low_krw'])/merged['okx_low_krw']
# merged['okx_close_kimp'] = (merged['upbit_close'] - merged['okx_close_krw'])/merged['okx_close_krw']

In [19]:
merged['okx_open_kimp']

0      0.012459
1      0.002273
2      0.001754
3      0.012196
4      0.011934
         ...
119    0.008655
120    0.000526
121    0.009818
122    0.010206
123    0.011372
Name: okx_open_kimp, Length: 124, dtype: float64

2023-06-26 16:19:51,287 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.
2023-06-26 16:20:22,231 - update_dollar - INFO - fetch_dollar|Dollar price (1306.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1306.0 KRW) has been updated.

In [17]:
kimp_core.okx_adaptor.okx_market_enter(my_okx_demo_api_key, my_okx_demo_secret_key, my_okx_demo_passphrase, 'ETH-USDT-SWAP', 0.1, 'isolated')

{'clOrdId': '',
 'ordId': '588348591190691840',
 'sCode': '0',
 'sMsg': 'Order placed',
 'tag': ''}

In [62]:
kimp_core.okx_adaptor.okx_market_exit(my_okx_demo_api_key, my_okx_demo_secret_key, my_okx_demo_passphrase, 'ETH-USDT-SWAP', 0.01, 'cross')

{'clOrdId': '',
 'ordId': '',
 'sCode': '51121',
 'sMsg': 'Order quantity must be a multiple of the lot size.',
 'tag': ''}

2023-06-12 14:53:30,497 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:54:01,358 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:54:32,038 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:55:02,759 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:55:33,541 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:56:04,340 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:56:35,042 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 14:57:05,820 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 14:57:36,543 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 14:58:07,301 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 14:58:38,116 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:59:08,924 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 14:59:39,706 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 15:00:10,504 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 15:00:41,181 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 15:01:11,969 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 15:01:42,685 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 15:02:13,370 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 15:02:44,226 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 15:03:15,030 - update_dollar - INFO - fetch_dollar|Dollar price (1289.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.8 KRW) has been updated.
2023-06-12 15:03:45,822 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 15:04:16,604 - update_dollar - INFO - fetch_dollar|Dollar price (1289.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.6 KRW) has been updated.
2023-06-12 15:04:47,401 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:05:18,190 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:05:48,994 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:06:19,827 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:06:50,608 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:07:21,392 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:07:52,181 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:08:23,010 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:08:53,694 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:09:24,384 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:09:55,178 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:10:25,891 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:10:56,578 - update_dollar - INFO - fetch_dollar|Dollar price (1289.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.3 KRW) has been updated.
2023-06-12 15:11:27,416 - update_dollar - INFO - fetch_dollar|Dollar price (1289.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.3 KRW) has been updated.
2023-06-12 15:11:58,095 - update_dollar - INFO - fetch_dollar|Dollar price (1289.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.3 KRW) has been updated.
2023-06-12 15:12:28,876 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:12:59,680 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:13:30,510 - update_dollar - INFO - fetch_dollar|Dollar price (1288.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.9 KRW) has been updated.
2023-06-12 15:14:01,320 - update_dollar - INFO - fetch_dollar|Dollar price (1288.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.9 KRW) has been updated.
2023-06-12 15:14:32,126 - update_dollar - INFO - fetch_dollar|Dollar price (1288.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.9 KRW) has been updated.
2023-06-12 15:15:02,815 - update_dollar - INFO - fetch_dollar|Dollar price (1288.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.9 KRW) has been updated.
2023-06-12 15:15:33,495 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:16:04,278 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:16:35,060 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:17:05,849 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:17:36,548 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:18:07,228 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:18:37,916 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:19:08,660 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:19:39,496 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:20:10,283 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:20:41,061 - update_dollar - INFO - fetch_dollar|Dollar price (1288.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.6 KRW) has been updated.
2023-06-12 15:21:11,886 - update_dollar - INFO - fetch_dollar|Dollar price (1288.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.6 KRW) has been updated.
2023-06-12 15:21:42,570 - update_dollar - INFO - fetch_dollar|Dollar price (1288.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.6 KRW) has been updated.
2023-06-12 15:22:13,245 - update_dollar - INFO - fetch_dollar|Dollar price (1288.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.6 KRW) has been updated.
2023-06-12 15:22:44,029 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:23:14,714 - update_dollar - INFO - fetch_dollar|Dollar price (1289.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.1 KRW) has been updated.
2023-06-12 15:23:45,514 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:24:16,307 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:24:47,082 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:25:17,915 - update_dollar - INFO - fetch_dollar|Dollar price (1289.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.4 KRW) has been updated.
2023-06-12 15:25:48,690 - update_dollar - INFO - fetch_dollar|Dollar price (1289.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.2 KRW) has been updated.
2023-06-12 15:26:19,466 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:26:50,245 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:27:21,031 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:27:51,835 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:28:22,651 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:28:53,326 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:29:24,138 - update_dollar - INFO - fetch_dollar|Dollar price (1288.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.8 KRW) has been updated.
2023-06-12 15:29:54,924 - update_dollar - INFO - fetch_dollar|Dollar price (1288.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.8 KRW) has been updated.
2023-06-12 15:30:25,953 - update_dollar - INFO - fetch_dollar|Dollar price (1288.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.8 KRW) has been updated.
2023-06-12 15:30:56,735 - update_dollar - INFO - fetch_dollar|Dollar price (1288.3 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.3 KRW) has been updated.
2023-06-12 15:31:27,511 - update_dollar - INFO - fetch_dollar|Dollar price (1288.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.5 KRW) has been updated.
2023-06-12 15:31:58,338 - update_dollar - INFO - fetch_dollar|Dollar price (1288.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.5 KRW) has been updated.
2023-06-12 15:32:29,176 - update_dollar - INFO - fetch_dollar|Dollar price (1288.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.5 KRW) has been updated.
2023-06-12 15:32:59,965 - update_dollar - INFO - fetch_dollar|Dollar price (1288.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.5 KRW) has been updated.
2023-06-12 15:33:30,767 - update_dollar - INFO - fetch_dollar|Dollar price (1288.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.5 KRW) has been updated.
2023-06-12 15:34:01,654 - update_dollar - INFO - fetch_dollar|Dollar price (1288.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.5 KRW) has been updated.
2023-06-12 15:34:32,448 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:35:03,150 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:35:33,962 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:36:04,773 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:36:35,466 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:37:06,312 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:37:36,992 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:38:07,812 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:38:38,619 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:39:09,338 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:39:40,014 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:40:10,818 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:40:41,496 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:41:12,272 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:41:43,057 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:42:13,851 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:42:44,644 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:43:15,439 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:43:46,233 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:44:16,913 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:44:47,600 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:45:18,396 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:45:49,179 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:46:19,977 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:46:50,777 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:47:21,460 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:47:52,216 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:48:23,002 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:48:53,777 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:49:24,574 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:49:55,352 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:50:26,129 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:50:56,923 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:51:27,702 - update_dollar - INFO - fetch_dollar|Dollar price (1289.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.5 KRW) has been updated.
2023-06-12 15:51:58,481 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:52:29,280 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:53:00,021 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1289.0 KRW) has been updated.
2023-06-12 15:53:30,810 - update_dollar - INFO - fetch_dollar|Dollar price (1289.0 KRW) has been updated.

In [42]:
my_client = kimp_core.okx_adaptor.load_user_client(my_okx_demo_api_key, my_okx_demo_secret_key, my_okx_demo_passphrase)
my_client.TradeAPI.get_order(instId='XRP-USDT-SWAP', ordId='12341234234')#['data'][0]

{'code': '51603', 'data': [], 'msg': 'Order does not exist'}

2023-06-08 17:08:46,385 - update_dollar - INFO - fetch_dollar|Dollar price (1303.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1303.5 KRW) has been updated.
2023-06-08 17:09:17,069 - update_dollar - INFO - fetch_dollar|Dollar price (1303.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1303.5 KRW) has been updated.
2023-06-08 17:09:47,843 - update_dollar - INFO - fetch_dollar|Dollar price (1303.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1303.5 KRW) has been updated.
2023-06-08 17:10:18,601 - update_dollar - INFO - fetch_dollar|Dollar price (1303.5 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1303.5 KRW) has been updated.
2023-06-08 17:10:49,281 - update_dollar - INFO - fetch_dollar|Dollar price (1303.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1303.0 KRW) has been updated.
2023-06-08 17:11:20,067 - update_dollar - INFO - fetch_dollar|Dollar price (1303.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1303.0 KRW) has been updated.

In [6]:
kimp_df = kimp_core.get_kimp_df()
kimp_df.head()

,symbol,acc_trade_price_24h,trade_price,okx_bid_price,okx_ask_price,okx_last_price,okx_last_price_krw,signed_change_rate,upbit_market_state,upbit_delisting_date,upbit_market_warning,upbit_is_trading_suspended,upbit_timestamp,okx_timestamp,enter_kimp,exit_kimp,tp_kimp,enter_usdt,exit_usdt,tp_usdt
0,BTC,120356786842.705505,35178000.0,26723.0,26723.1,26723.0,34419224.0,0.002451,ACTIVE,None,NONE,False,1687271643799,1687271643895,0.022074,0.022041,0.022045,1316.431538,1316.389191,1316.394117
1,XRP,117095194997.628601,626.0,0.47454,0.47455,0.47458,611.25904,-0.02795,ACTIVE,None,NONE,False,1687271643556,1687271643610,0.024202,0.022544,0.024116,1319.172251,1317.037193,1319.061065
2,SUI,112707979975.717896,996.0,0.7563,0.7564,0.7564,974.2432,-0.03301,ACTIVE,None,NONE,False,1687271643539,1687271643610,0.022467,0.021306,0.022332,1316.937723,1315.441565,1316.763617
3,STX,109592787398.57695,826.0,0.6283,0.6284,0.6284,809.3792,0.064433,ACTIVE,None,NONE,False,1687271643717,1687271643895,0.021933,0.020535,0.020535,1316.250199,1314.449395,1314.449395
4,APT,31928755265.329948,8795.0,6.6786,6.6788,6.6776,8600.7488,-0.030854,ACTIVE,None,NONE,False,1687271643017,1687271643853,0.023014,0.022402,0.022585,1317.641422,1316.853327,1317.089972

2023-06-20 23:34:33,546 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:35:04,332 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:35:35,115 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:36:05,902 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:36:36,701 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:37:07,506 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:37:38,250 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:38:08,929 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:38:39,610 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:39:10,404 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:39:41,083 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:40:11,859 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:40:42,636 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:41:13,435 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:41:44,216 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:42:15,019 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:42:45,801 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:43:16,581 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:43:47,388 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:44:18,183 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:44:48,964 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:45:19,751 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:45:50,543 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:46:21,330 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:46:52,008 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:47:22,818 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:47:53,519 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:48:24,263 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:48:54,942 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:49:25,770 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:49:56,464 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:50:27,249 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:50:58,027 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:51:28,803 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:51:59,481 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:52:30,291 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:53:01,085 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:53:31,875 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:54:02,660 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:54:33,451 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:55:04,260 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:55:35,052 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:56:05,827 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:56:36,619 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:57:07,401 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:57:38,211 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:58:08,991 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:58:39,674 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:59:10,469 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-20 23:59:41,278 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:00:12,057 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:00:42,840 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:01:13,644 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:01:44,336 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:02:15,133 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:02:45,889 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:03:16,674 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:03:47,457 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:04:18,244 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:04:48,937 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:05:19,724 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:05:50,539 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:06:21,215 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:06:51,995 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:07:22,778 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:07:53,573 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:08:24,269 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:08:54,947 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:09:25,727 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:09:56,509 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:10:27,193 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:10:57,981 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:11:28,790 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:11:59,490 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:12:30,273 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:13:00,964 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:13:31,756 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:14:02,534 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:14:33,317 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:15:04,020 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:15:34,794 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:16:05,580 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:16:36,363 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:17:07,142 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:17:37,930 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:18:08,603 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:18:39,391 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:19:10,178 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:19:40,970 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:20:11,769 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:20:42,457 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:21:13,299 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:21:44,066 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:22:14,744 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:22:45,529 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:23:16,310 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:23:47,094 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:24:17,891 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:24:48,675 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:25:19,463 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:25:50,274 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:26:20,947 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:26:51,628 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:27:22,302 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:27:53,075 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:28:23,750 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:28:54,421 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:29:25,200 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:29:55,992 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:30:26,676 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:30:57,453 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:31:28,244 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:31:59,030 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:32:29,703 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:33:00,376 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:33:31,162 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:34:01,948 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1288.0 KRW) has been updated.
2023-06-21 00:34:32,761 - update_dollar - INFO - fetch_dollar|Dollar price (1288.0 KRW) has been updated.

In [20]:
kimp_core.okx_adaptor.okx_fetch_candle('ETH-USDT-SWAP', 'weeks')

,okx_time,okx_open,okx_high,okx_low,okx_close,okx_volume,okx_volCcy,okx_volCcyQuote,okx_completed
0,2023-06-19 01:00:00,1738.23,1829.72,1696.54,1808.32,59704510.0,5970451.0,10437558155.812,0.0
1,2023-06-12 01:00:00,1741.58,1778.36,1623.19,1738.23,146773421.0,14677342.1,25100538432.212002,1.0
2,2023-06-05 01:00:00,1901.39,1913.65,1713.98,1741.58,165508415.0,16550841.5,30161677653.075001,1.0
3,2023-05-29 01:00:00,1844.4,1935.0,1837.0,1901.42,115945310.0,11594531.0,21865213300.297001,1.0
4,2023-05-22 01:00:00,1807.63,1880.0,1758.82,1844.4,116731778.0,11673177.8,21246029129.259998,1.0
...,...,...,...,...,...,...,...,...,...
182,2019-12-23 01:00:00,129.63,135.69,122.65,131.9,2014042.0,201404.2,26176001.273272,1.0
183,2019-12-16 01:00:00,120.0,130.99,120.0,129.59,103535.0,10353.5,1323742.5975,1.0
184,2019-12-09 01:00:00,150.66,151.63,143.92,144.87,127529442.0,12752944.2,1880286327.89175,1.0
185,2019-12-02 01:00:00,145.0,152.0,143.5,150.57,360334744.0,36033474.4,5322223572.35525,1.0
186,2019-11-25 01:00:00,155.0,155.0,150.0,150.2,40.0,4.0,600.8,1.0

2023-06-21 13:15:01,820 - update_dollar - INFO - fetch_dollar|Dollar price (1292.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.8 KRW) has been updated.
2023-06-21 13:15:32,625 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:16:03,447 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:16:34,264 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:17:05,042 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:17:35,847 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:18:06,590 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:18:37,384 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:19:08,181 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:19:38,971 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:20:09,791 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:20:40,476 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:21:11,282 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:21:42,079 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:22:12,869 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:22:43,721 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:23:14,522 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:23:45,322 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:24:16,110 - update_dollar - INFO - fetch_dollar|Dollar price (1292.7 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.7 KRW) has been updated.
2023-06-21 13:24:46,896 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:25:18,003 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:25:48,788 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:26:19,486 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:26:50,271 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:27:21,013 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:27:51,827 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:28:22,610 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:28:53,427 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:29:24,232 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:29:55,024 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:30:25,935 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:30:56,709 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:31:27,502 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:31:58,188 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 13:32:28,861 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:32:59,650 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:33:30,475 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:34:01,252 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:34:31,944 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:35:02,742 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:35:33,497 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:36:04,196 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 13:36:34,982 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:37:05,771 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:37:36,580 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:38:07,265 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:38:37,940 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:39:08,730 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:39:39,545 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:40:10,225 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 13:40:41,030 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:41:11,845 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:41:42,683 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:42:13,501 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:42:44,297 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:43:15,173 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:43:45,862 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:44:16,654 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:44:47,482 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:45:18,319 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:45:49,106 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:46:19,807 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:46:50,609 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:47:21,312 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:47:52,108 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:48:22,959 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:48:53,717 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:49:24,627 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:49:55,307 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:50:26,091 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 13:50:56,876 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:51:27,698 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:51:58,493 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:52:29,185 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:52:59,975 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:53:30,778 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:54:01,623 - update_dollar - INFO - fetch_dollar|Dollar price (1291.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.9 KRW) has been updated.
2023-06-21 13:54:32,425 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:55:03,233 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:55:34,038 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:56:04,724 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:56:35,425 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:57:06,253 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:57:37,051 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:58:07,875 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:58:38,653 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:59:09,443 - update_dollar - INFO - fetch_dollar|Dollar price (1292.1 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.1 KRW) has been updated.
2023-06-21 13:59:40,240 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 14:00:10,997 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 14:00:41,817 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:01:12,824 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:01:43,639 - update_dollar - INFO - fetch_dollar|Dollar price (1291.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.6 KRW) has been updated.
2023-06-21 14:02:14,426 - update_dollar - INFO - fetch_dollar|Dollar price (1291.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.6 KRW) has been updated.
2023-06-21 14:02:45,118 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:03:15,903 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:03:46,712 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 14:04:17,505 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 14:04:48,301 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:05:19,100 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:05:49,954 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:06:20,747 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:06:51,421 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:07:22,211 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 14:07:52,890 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 14:08:23,686 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 14:08:54,393 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 14:09:25,194 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 14:09:55,914 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 14:10:26,702 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 14:10:57,506 - update_dollar - INFO - fetch_dollar|Dollar price (1292.4 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.4 KRW) has been updated.
2023-06-21 14:11:28,303 - update_dollar - INFO - fetch_dollar|Dollar price (1292.2 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.2 KRW) has been updated.
2023-06-21 14:11:58,973 - update_dollar - INFO - fetch_dollar|Dollar price (1292.0 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1292.0 KRW) has been updated.
2023-06-21 14:12:29,660 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:13:00,418 - update_dollar - INFO - fetch_dollar|Dollar price (1291.8 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.8 KRW) has been updated.
2023-06-21 14:13:31,172 - update_dollar - INFO - fetch_dollar|Dollar price (1291.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.6 KRW) has been updated.
2023-06-21 14:14:01,957 - update_dollar - INFO - fetch_dollar|Dollar price (1291.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.6 KRW) has been updated.
2023-06-21 14:14:32,690 - update_dollar - INFO - fetch_dollar|Dollar price (1291.6 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1291.6 KRW) has been updated.
2023-06-21 14:15:03,408 - update_dollar - INFO - fetch_dollar|Dollar price (1291.6 KRW) has been updated.