In [1]:
sys.path.append("/home/coin_trading_bot/kimp_bot_core")
monitor_bot_token = "5556345865:AAFJy8wdyTjKxDBOb89bTRFsNs6UFMn4twY"
monitor_bot_url = "http://222.106.173.213:22180/api/master_v1/monitorbot/"
from etc.db_handler.create_schema_tables import InitDBClient

In [2]:
from telegram_bot_plugin.telegram_bot import InitTelegramBot
# Initiating kimp_bot_core
from kimp_bot_core import InitKimpCore
kimp_core = InitKimpCore(proc_n=1)

[WARNING] upbit-client is currently a newer version: 1.3.2.0
Please update to the latest version using the pip command:`pip install --upgrade upbit-client`
2022-09-19 15:16:25,509 - kimp_bot_core - INFO - InitKimpCore|InitKimpCore initiated with proc_n=1
[INFO] InitKimpCore|InitKimpCore initiated with proc_n=1
2022-09-19 15:16:26,786 - price_websocket - INFO - binance_upbit_websocket|price_websocket.binance_upbit_websocket executed
[INFO] binance_upbit_websocket|price_websocket.binance_upbit_websocket executed
2022-09-19 15:16:26,867 - price_websocket - INFO - binance_bookticker_websocket|1th binance_bookticker_proc started.
[INFO] binance_bookticker_websocket|1th binance_bookticker_proc started.
2022-09-19 15:16:27,322 - price_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2022-09-19 15:16:27,390 - update_dollar - INFO - fetch_dollar|Dollar price (1392.9 KRW) has been updated.
[INFO] fetch_dollar|Dollar price (1392.9 KRW) has been updated.
2022-09-19 15:16:27,550 - price_websocket - INFO - upbit_orderbook_ticker_websocket|upbit_websocket started
[INFO] upbit_orderbook_ticker_websocket|upbit_websocket started
2022-09-19 15:16:27,632 - price_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
[INFO] upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2022-09-19 15:16:27,811 - price_websocket - INFO - upbit_orderbook_ticker_websocket|upbit_websocket started
[INFO] upbit_orderbook_ticker_websocket|upbit_websocket started

In [3]:
kimp_core.set_monitor_bot_token(monitor_bot_token)
kimp_core.set_monitor_api_url(monitor_bot_url)
kimp_core.monitor_websocket()

2022-09-19 15:16:28,977 - kimp_bot_core - INFO - monitor_websocket|monitor_websocket_procs started.
[INFO] monitor_websocket|monitor_websocket_procs started.

In [4]:
kimp_core.BINANCE_BOOKTICKER_PROC_LIST[0].is_alive()

True

In [5]:
node = 'test_node'

email_smtp_dict = {
        "email_host":"smtp.worksmobile.com",
        "email_port":"587",
        "email_host_user":"people9@people9.co.kr",
        "email_host_password":"vlvmfskdls9!",
        "email_use_tls":True
    }

local_db_dict = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',
    'passwd': '13245dh',
    'database': 'test_coin_trade'
}
remote_db_dict = {
    'host': '222.106.173.213',
    'port': 22153,
    'user': 'root',
    'passwd': '13245dh!!',
    'database': 'coin_trade'
}

encryption_key = '13245dh!!'
bot_token = "1334132077:AAE7Pvj0bu4sHGKWlH6VsZFsSkcwPrwxB6I"

logging_dir = "/home/coin_trading_bot/kimp_bot_core/telegram_bot_plugin/"

test_telegram_bot = InitTelegramBot(logging_dir, node, encryption_key, email_smtp_dict, local_db_dict, remote_db_dict, kimp_core.get_kimp_df, kimp_core.get_dollar_dict, kimp_core.get_both_listed_binance_symbols, monitor_bot_token, monitor_bot_url, bot_token)

2022-09-19 15:16:30,972 - snatcher - INFO - Local Mariadb client has been connected to localhost - test_coin_trade.
[INFO] Local Mariadb client has been connected to localhost - test_coin_trade.
2022-09-19 15:16:31,153 - snatcher - INFO - Remote Mariadb client has been connected to 222.106.173.213 - coin_trade.
[INFO] Remote Mariadb client has been connected to 222.106.173.213 - coin_trade.
2022-09-19 15:16:31,609 - snatcher - INFO - start_monitor_load_userinfo|start_monitor_load_userinfo started.
[INFO] start_monitor_load_userinfo|start_monitor_load_userinfo started.
2022-09-19 15:16:31,613 - snatcher - INFO - start_monitor_load_user_api_key|start_monitor_load_user_api_key started.
[INFO] start_monitor_load_user_api_key|start_monitor_load_user_api_key started.
2022-09-19 15:16:31,629 - snatcher - INFO - start_monitor_load_trade_history|start_monitor_load_trade_history started.
[INFO] start_monitor_load_trade_history|start_monitor_load_trade_history started.
2022-09-19 15:16:31,636 - snatcher - INFO - start_monitor_load_addcoin|start_monitor_load_addcoin started.
[INFO] start_monitor_load_addcoin|start_monitor_load_addcoin started.
2022-09-19 15:16:31,647 - snatcher - INFO - start_monitor_load_addcir|start_monitor_load_addcir started.
[INFO] start_monitor_load_addcir|start_monitor_load_addcir started.
2022-09-19 15:16:31,652 - snatcher - INFO - start_monitor_load_binance_futures_exchange_info|start_monitor_load_binance_futures_exchange_info started.
[INFO] start_monitor_load_binance_futures_exchange_info|start_monitor_load_binance_futures_exchange_info started.
2022-09-19 15:16:31,658 - snatcher - INFO - start_monitor_load_funding_info|start_monitor_load_funding_info started.
[INFO] start_monitor_load_funding_info|start_monitor_load_funding_info started.
2022-09-19 15:16:31,668 - snatcher - INFO - apply_addcir_limit|apply_addcir_limit started.
[INFO] apply_addcir_limit|apply_addcir_limit started.
2022-09-19 15:16:34,673 - snatcher - INFO - start_monitor_margin_call|start_monitor_margin_call started.
[INFO] start_monitor_margin_call|start_monitor_margin_call started.

In [6]:
test_telegram_bot.snatcher.start_monitor_high_low_loop()

2022-09-19 15:16:36,562 - snatcher - INFO - start_monitor_high_low_loop|start_monitor_high_low_loop started.
[INFO] start_monitor_high_low_loop|start_monitor_high_low_loop started.

In [9]:
userinfo_df = test_telegram_bot.snatcher.userinfo_df
user_api_key_df = test_telegram_bot.snatcher.user_api_key_df

In [6]:
test_telegram_bot.snatcher.start_monitor_high_low_loop_thread.is_alive()

True

In [7]:
test_telegram_bot.snatcher.monitor_loop_load_funding_info_thread.is_alive()

True

In [5]:
test_telegram_bot.snatcher.addcir_df

,user_id,datetime,last_updated_timestamp,redis_uuid,symbol,addcir_uuid,auto_low,auto_high,pauto_num,fauto_num,cir_trade_switch,cir_trade_capital,cir_trade_num,remark
0,1390695186,2022-09-18 17:40:55,16634904552192710,fd57ed53-c51e-4f3a-8450-698d93669480,XRP,9752a82e372d11eda2946c02e06636d4,None,None,10.0,None,1,10000.0,-1,None

In [6]:
test_telegram_bot.snatcher.addcoin_df

,user_id,datetime,last_updated_timestamp,redis_uuid,symbol,addcoin_uuid,high,low,rolling_window,switch,auto_trade_switch,auto_trade_capital,enter_upbit_uuid,enter_binance_orderId,exit_upbit_uuid,exit_binance_orderId,remark
0,1390695186,2022-09-18 17:41:00,16634904601171840,28a72e8d-83ab-489d-8dbd-65a0bb1eb10f,XRP,9752a82e372d11eda2946c02e06636d4,6.098,-3.902,None,1,0,10000.0,None,None,None,None,None

:

In [6]:
test_telegram_bot.snatcher.userinfo_df

,user_id,register_origin,datetime,datetime_end,status,user_name,binance_uid,referral_use,referral_code,interest_coin,...,alarm_num,alarm_period,kimp_diff,addcir_limit,addcir_num_limit,exd_percent,kimp_diff_wallet,kimp_diff_coin,on_off,remark
0,123123,kimp_bot1,2022-09-16 14:06:43,2023-09-17 19:55:53,None,test1,None,None,None,None,...,1,1,None,None,None,None,None,None,1,None
1,1390695186,kimp_bot1,2022-09-18 16:47:54,2023-09-17 13:59:38,None,test1,None,None,None,None,...,1,1,None,0.0,None,None,None,None,1,None

:

In [6]:
test_telegram_bot.snatcher.monitor_apply_addcir_limit_thread.is_alive()

True

: