In [171]:
from binance_websocket import BinanceWebsocket
import pandas as pd
from upbit_websocket import UpbitWebsocket
import time
import datetime
from multiprocessing import Process, Manager
import pickle

# Go to the upper directory with absolute path
import sys
sys.path.append('/home/kp_info_loader')
from etc.redis_connector.redis_connector import InitRedis

In [2]:
binance_spot_symbol_list = ['BTCUSDT','ETHUSDT','XRPUSDT','BCHUSDT','XEMUSDT','MTLUSDT','KAVAUSDT','TUSDT','SUIUSDT','SOLUSDT','WAVESUSDT','STXUSDT','STORJUSDT','DOGEUSDT','ETCUSDT','FLOWUSDT','ETCUSDT','MATICUSDT','AAVEUSDT','ALGOUSDT','GMTUSDT','SANDUSDT','ANKRUSDT','ONTUSDT','SXPUSDT']
binance_usdm_symbol_list = binance_spot_symbol_list
binance_coinm_symbol_list = [x[:-1]+'_PERP' for x in binance_spot_symbol_list]
proc_n = 3
logging_dir = '/home/kp_info_loader/exchange_websocket/'
binance_ws = BinanceWebsocket(binance_spot_symbol_list, binance_usdm_symbol_list, binance_coinm_symbol_list, proc_n, logging_dir)

2023-07-17 15:05:26,174 - binance_websocket - INFO - started 1th Binance price websocket for usdm, coinm, spot proc..
2023-07-17 15:05:26,283 - binance_websocket - INFO - started 2th Binance price websocket for usdm, coinm, spot proc..
2023-07-17 15:05:26,394 - binance_websocket - INFO - started 3th Binance price websocket for usdm, coinm, spot proc..

In [3]:
upbit_symbol_list = ['KRW-'+x[:-4] for x in binance_spot_symbol_list]
upbit_ws = UpbitWebsocket(upbit_symbol_list, proc_n, logging_dir)

2023-07-15 14:20:03,848 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.

2023-07-15 14:20:03,952 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-15 14:20:04,360 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-07-15 14:20:04,449 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-15 14:20:04,870 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
2023-07-15 14:20:04,959 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-15 14:20:05,378 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
2023-07-15 14:20:05,463 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-15 14:20:05,890 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-07-15 14:20:05,987 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-15 14:20:06,401 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
2023-07-15 14:20:06,495 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started

2023-07-17 15:05:26,519 - binance_websocket - INFO - started binance_liquidation_websocket for usdm, coinm..
2023-07-17 15:05:26,522 - binance_websocket - INFO - started binance_kline_websocket for usdm, coinm, spot..

2023-07-17 15:05:26,548 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_ticker_proc started.
2023-07-17 15:05:26,657 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-17 15:05:27,061 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|1th upbit_orderbook_proc started.
2023-07-17 15:05:27,156 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-17 15:05:27,574 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_ticker_proc started.
2023-07-17 15:05:27,657 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-17 15:05:28,085 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|2th upbit_orderbook_proc started.
2023-07-17 15:05:28,169 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-17 15:05:28,596 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_ticker_proc started.
2023-07-17 15:05:28,688 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started
2023-07-17 15:05:29,106 - upbit_websocket - INFO - upbit_orderbook_ticker_websocket|3th upbit_orderbook_proc started.
2023-07-17 15:05:29,189 - upbit_websocket - INFO - upbit_websocket|upbit_websocket started

In [4]:
def get_ticker_ratio(price_krw):
    if price_krw < 0.1:
        ticker_size = 0.0001
    elif price_krw < 1:
        ticker_size = 0.001
    elif price_krw < 10:
        ticker_size = 0.01
    elif price_krw < 100:
        ticker_size = 0.1
    elif price_krw < 1000:
        ticker_size = 1
    elif price_krw < 10000:
        ticker_size = 5
    elif price_krw < 100000:
        ticker_size = 10
    elif price_krw < 500000:
        ticker_size = 50
    elif price_krw < 1000000:
        ticker_size = 100
    elif price_krw < 2000000:
        ticker_size = 500
    elif price_krw >= 2000000:
        ticker_size = 1000
    ticker_ratio = ticker_size / price_krw
    return ticker_ratio

def binance_bookticker_convert(BINANCE_BOOKTICKER_DICT):
    BINANCE_BOOKTICKER_DICT_copy = dict(BINANCE_BOOKTICKER_DICT.copy())
    converted_df = pd.DataFrame(BINANCE_BOOKTICKER_DICT_copy).transpose().reset_index(drop=True)
    # binance_bookTicker_column_dict = {
    #     'e':'event_type',
    #     'u':'order_book_updateId',
    #     'E':'event_time',
    #     'T':'transaction_time',
    #     's':'symbol',
    #     'b':'best_bid_price',
    #     'B':'best_bid_qty',
    #     'a':'best_ask_price',
    #     'A':'best_ask_qty'
    # }
    # temp_df = temp_df.rename(columns=binance_bookTicker_column_dict)
    return converted_df

def binance_ticker_convert(binance_ticker_dict):
    binance_ticker_dict_copy = dict(binance_ticker_dict.copy())
    converted_df = pd.DataFrame(binance_ticker_dict_copy).transpose().reset_index(drop=True)
    return converted_df

def upbit_ticker_convert(UPBIT_TICKER_DICT):
    UPBIT_TICKER_DICT_copy = dict(UPBIT_TICKER_DICT.copy())
    converted_df = pd.DataFrame(UPBIT_TICKER_DICT_copy).transpose().reset_index(drop=True)
    # upbit_column_dict = {
    #     'ty':'type',
    #     'cd':'code',
    #     'op':'opening_price',
    #     'hp':'high_price',
    #     'lp':'low_price',
    #     'tp':'trade_price',
    #     'pcp':'prev_closing_price',
    #     'c':'change',
    #     'cp':'change_price',
    #     'scp':'signed_change_price',
    #     'cr':'change_rate',
    #     'scr':'signed_change_rate',
    #     'tv':'trade_volume',
    #     'atv':'acc_trade_volume',
    #     'atv24h':'acc_trade_volume_24h',
    #     'atp':'acc_trade_price',
    #     'atp24h':'acc_trade_price_24h',
    #     'tdt':'trade_date',
    #     'ttm':'trade_time',
    #     'ttms':'trade_timestamp',
    #     'ab':'ask_bid',
    #     'aav':'acc_ask_volume',
    #     'abv':'acc_bid_volume',
    #     'h52wp':'highest_52_week_price',
    #     'h52wdt':'highest_52_week_date',
    #     'l52wp':'lowest_52_week_price',
    #     'l52wdt':'lowest_52_week_date',
    #     'ts':'trade_status',
    #     'ms':'market_state',
    #     'msfi':'market_state_for_ios',
    #     'its':'is_trading_suspended',
    #     'dd':'delisting_date',
    #     'mw':'market_warning',
    #     'tms':'timestamp',
    #     'st':'stream_type'
    # }
    # temp_df = temp_df.rename(columns=upbit_column_dict)
    return converted_df

def upbit_orderbook_convert(UPBIT_ORDERBOOK_DICT):
    UPBIT_ORDERBOOK_DICT_copy = dict(UPBIT_ORDERBOOK_DICT.copy())
    converted_df = pd.DataFrame(UPBIT_ORDERBOOK_DICT_copy).transpose().reset_index(drop=True)
    # upbit_column_dict = {
    #     'ty':'type',
    #     'cd':'code',
    #     'tas':'total_ask_size',
    #     'tbs':'total_bid_size',
    #     'obu':'orderbook_units',
    #     'tms':'timestamp',
    #     'st':'stream_type'
    # }
    # temp_df = temp_df.rename(columns=upbit_column_dict)
    return converted_df

In [5]:
binance_bookticker_convert(binance_ws.binance_usdm_bookticker_dict)

,e,u,s,b,B,a,A,T,E
0,bookTicker,3070568036178,BTCUSDT,30252.80,22.844,30252.90,11.245,1689573929605,1689573929618
1,bookTicker,3070568036400,BCHUSDT,251.31,13.136,251.32,23.106,1689573929614,1689573929619
2,bookTicker,3070568036407,DOGEUSDT,0.071490,69535,0.071500,186276,1689573929614,1689573929619
3,bookTicker,3070568036562,ETHUSDT,1929.68,212.006,1929.69,10.040,1689573929618,1689573929622
4,bookTicker,3070568028638,WAVESUSDT,2.0072,664.1,2.0073,139.3,1689573929352,1689573929356
5,bookTicker,3070568014978,STORJUSDT,0.3142,46587,0.3143,7155,1689573928959,1689573928962
6,bookTicker,3070568031368,SANDUSDT,0.45120,21348,0.45130,14498,1689573929454,1689573929459
7,bookTicker,3070567999054,TUSDT,0.0241200,21776,0.0241300,212732,1689573928402,1689573928407
8,bookTicker,3070568031272,MATICUSDT,0.77800,7729,0.77810,25434,1689573929451,1689573929456
9,bookTicker,3070568031805,FLOWUSDT,0.623,94196.5,0.624,98929.8,1689573929470,1689573929474
10,bookTicker,3070568036443,ALGOUSDT,0.1228,234681.6,0.1229,243113.2,1689573929615,1689573929619
11,bookTicker,3070568005967,AAVEUSDT,78.820,49.9,78.830,26.6,1689573928639,1689573928643
12,bookTicker,3070568036468,KAVAUSDT,0.9211,3393.6,0.9212,489.1,1689573929615,1689573929620
13,bookTicker,3070568036384,XRPUSDT,0.7468,61827.7,0.7469,13010.0,1689573929613,1689573929618
14,bookTicker,3070568032946,SXPUSDT,0.3743,2242.7,0.3744,6812.3,1689573929508,1689573929522
15,bookTicker,3070568028059,ANKRUSDT,0.025660,94299,0.025670,98952,1689573929334,1689573929338
16,bookTicker,3070568004890,ETCUSDT,19.054,230.30,19.055,377.31,1689573928599,1689573928603
17,bookTicker,3070568029853,ONTUSDT,0.2084,7178.3,0.2085,35243.8,1689573929396,1689573929401
18,bookTicker,3070568031236,STXUSDT,0.6397000,3404,0.6398000,96,1689573929448,1689573929454
19,bookTicker,3070568034782,SOLUSDT,27.8300,291,27.8310,292,1689573929568,1689573929573
20,bookTicker,3070568032330,XEMUSDT,0.0299,3173737,0.0300,4523959,1689573929486,1689573929490
21,bookTicker,3070568035352,SUIUSDT,0.685800,2342.1,0.685900,8288.0,1689573929583,1689573929586
22,bookTicker,3070568036529,GMTUSDT,0.24230,58131,0.24240,48405,1689573929617,1689573929621
23,bookTicker,3070568028695,MTLUSDT,1.4352,125,1.4353,506,1689573929355,1689573929360

In [6]:
temp = binance_ticker_convert(binance_ws.binance_usdm_ticker_dict)
temp[temp['s']=='BTCUSDT'][['v','q']]

            v              q
6  149146.257  4517584656.84

In [7]:
upbit_orderbook_convert(upbit_ws.upbit_orderbook_dict)

,ty,cd,tms,tas,tbs,obu,st
0,orderbook,KRW-BTC,1689573930496,6.344443,8.738829,"[{'ap': 38930000, 'bp': 38909000, 'as': 0.0492...",REALTIME
1,orderbook,KRW-BCH,1689573931242,654.98349,708.358173,"[{'ap': 323250, 'bp': 323200, 'as': 11.4322128...",REALTIME
2,orderbook,KRW-KAVA,1689573906445,998393.111561,944659.215532,"[{'ap': 1190, 'bp': 1185, 'as': 13613.42502966...",SNAPSHOT
3,orderbook,KRW-SOL,1689573931199,10281.672172,12482.718073,"[{'ap': 35780, 'bp': 35750, 'as': 405.95736918...",REALTIME
4,orderbook,KRW-STORJ,1689573931019,1599663.079853,1284935.846228,"[{'ap': 404, 'bp': 403, 'as': 50824.49010232, ...",REALTIME
5,orderbook,KRW-FLOW,1689573929621,518348.894494,411313.195671,"[{'ap': 803, 'bp': 802, 'as': 6697.95310942, '...",REALTIME
6,orderbook,KRW-AAVE,1689573931252,1384.86779,1159.986969,"[{'ap': 101450, 'bp': 101250, 'as': 7.02189256...",REALTIME
7,orderbook,KRW-SAND,1689573929983,760199.378035,1050307.582169,"[{'ap': 580, 'bp': 579, 'as': 28601.94189938, ...",REALTIME
8,orderbook,KRW-SXP,1689573931241,1135159.776816,1054268.27214,"[{'ap': 481, 'bp': 480, 'as': 39172.26382353, ...",REALTIME
9,orderbook,KRW-ETH,1689573924943,303.329202,260.416198,"[{'ap': 2483000, 'bp': 2482000, 'as': 19.60044...",SNAPSHOT
10,orderbook,KRW-XEM,1689573929125,5115874.13908,5108218.93601,"[{'ap': 38.6, 'bp': 38.4, 'as': 755679.6935095...",REALTIME
11,orderbook,KRW-T,1689573925663,9248334.224901,27949004.433978,"[{'ap': 31, 'bp': 30.9, 'as': 648857.34608634,...",SNAPSHOT
12,orderbook,KRW-WAVES,1689573928537,177907.336407,183386.633445,"[{'ap': 2585, 'bp': 2580, 'as': 21878.21050407...",REALTIME
13,orderbook,KRW-DOGE,1689573931072,5302832.961744,12146389.371515,"[{'ap': 92, 'bp': 91.9, 'as': 30000.0, 'bs': 3...",REALTIME
14,orderbook,KRW-ETC,1689573929982,11896.732619,8479.304142,"[{'ap': 24520, 'bp': 24510, 'as': 376.78922757...",REALTIME
15,orderbook,KRW-ALGO,1689573931252,17319865.748711,18751714.061157,"[{'ap': 158, 'bp': 157, 'as': 1327003.9071326,...",REALTIME
16,orderbook,KRW-ANKR,1689573930348,12461803.554296,16768374.315271,"[{'ap': 33.1, 'bp': 33, 'as': 1532811.24779488...",REALTIME
17,orderbook,KRW-XRP,1689573931248,4982722.442984,7448708.952265,"[{'ap': 961, 'bp': 960, 'as': 183276.84172909,...",REALTIME
18,orderbook,KRW-MTL,1689573924048,446367.084708,462896.342463,"[{'ap': 1850, 'bp': 1845, 'as': 67255.51341355...",SNAPSHOT
19,orderbook,KRW-SUI,1689573931241,707499.66769,664822.330659,"[{'ap': 883, 'bp': 881, 'as': 27634.59455523, ...",REALTIME
20,orderbook,KRW-STX,1689573924768,656348.012352,702912.210453,"[{'ap': 823, 'bp': 821, 'as': 5407.34232943, '...",SNAPSHOT
21,orderbook,KRW-MATIC,1689573930526,682988.192084,305038.547595,"[{'ap': 1005, 'bp': 1000, 'as': 173552.0000914...",REALTIME
22,orderbook,KRW-GMT,1689573930881,1612100.246808,3887031.925219,"[{'ap': 313, 'bp': 311, 'as': 256569.88433523,...",REALTIME
23,orderbook,KRW-ONT,1689573928405,1391743.035247,1310825.138829,"[{'ap': 268, 'bp': 267, 'as': 100375.02771928,...",SNAPSHOT

In [8]:
upbit_ticker_convert(upbit_ws.upbit_ticker_dict)

,ty,cd,op,hp,lp,tp,pcp,atp,c,cp,...,l52wp,l52wdt,ms,its,dd,mw,tms,atp24h,atv24h,st
0,ticker,KRW-BTC,38946000.0,38983000.0,38832000.0,38930000.0,38933000.0,21523413830.796768,FALL,3000.0,...,20700000.0,2022-12-30,ACTIVE,False,None,NONE,1689573933148,75850451820.101379,1947.765096,REALTIME
1,ticker,KRW-BCH,322150.0,327300.0,319050.0,323250.0,322100.0,12748012801.96859,RISE,1150.0,...,120450.0,2022-12-30,ACTIVE,False,None,NONE,1689573930169,38744161488.730171,118895.612067,REALTIME
2,ticker,KRW-KAVA,1190.0,1195.0,1175.0,1185.0,1190.0,2658997240.760039,FALL,5.0,...,960.0,2023-06-15,ACTIVE,False,None,NONE,1689573900330,6689661225.485402,5627455.378676,SNAPSHOT
3,ticker,KRW-SOL,35340.0,36620.0,35100.0,35750.0,35350.0,22099247710.811935,RISE,400.0,...,10140.0,2022-12-29,ACTIVE,False,None,NONE,1689573931039,65587740163.807823,1823183.842709,REALTIME
4,ticker,KRW-STORJ,398.0,404.0,394.0,404.0,398.0,2422131586.689389,RISE,6.0,...,282.0,2023-06-15,ACTIVE,False,None,NONE,1689573930899,10075053602.285778,25022267.886,REALTIME
5,ticker,KRW-FLOW,786.0,814.0,769.0,803.0,787.0,15920153142.46673,RISE,16.0,...,577.0,2023-06-15,ACTIVE,False,None,NONE,1689573930439,28558836545.623806,35909566.518973,REALTIME
6,ticker,KRW-AAVE,99160.0,102150.0,98370.0,101050.0,98900.0,1093522755.326471,RISE,2150.0,...,63160.0,2023-06-10,ACTIVE,False,None,NONE,1689573900497,2608349081.498388,25941.725465,SNAPSHOT
7,ticker,KRW-SAND,569.0,582.0,566.0,580.0,569.0,5034280269.945773,RISE,11.0,...,473.0,2023-06-15,ACTIVE,False,None,NONE,1689573931779,12340437956.202471,21422522.308907,REALTIME
8,ticker,KRW-SXP,477.0,483.0,474.0,481.0,477.0,2468999106.082999,RISE,4.0,...,248.0,2022-12-31,ACTIVE,False,None,NONE,1689573900372,6073160008.288413,12709764.704621,SNAPSHOT
9,ticker,KRW-ETH,2477000.0,2486000.0,2467000.0,2483000.0,2476000.0,6373265351.29406,RISE,7000.0,...,1500000.0,2022-12-30,ACTIVE,False,None,NONE,1689573930033,17270464634.997429,6961.78567,REALTIME
10,ticker,KRW-XEM,38.5,38.8,38.1,38.4,38.6,763612695.575737,FALL,0.2,...,28.4,2023-06-10,ACTIVE,False,None,NONE,1689573900075,2167191301.964457,56312425.150413,SNAPSHOT
11,ticker,KRW-T,31.0,31.2,30.5,31.0,31.1,2255355978.839204,FALL,0.1,...,18.5,2022-12-29,ACTIVE,False,None,NONE,1689573930497,7418843138.086836,239766347.071178,REALTIME
12,ticker,KRW-WAVES,2555.0,2600.0,2530.0,2580.0,2555.0,5021554152.762755,RISE,25.0,...,1580.0,2022-12-30,ACTIVE,False,None,NONE,1689573900072,15232298537.273346,5909693.978661,SNAPSHOT
13,ticker,KRW-DOGE,89.6,94.1,89.1,92.0,89.5,25094896787.767056,RISE,2.5,...,77.0,2023-06-14,ACTIVE,False,None,NONE,1689573932682,54256191967.177628,594234483.081517,REALTIME
14,ticker,KRW-ETC,24260.0,24550.0,24190.0,24510.0,24260.0,4712913216.807085,RISE,250.0,...,18490.0,2023-06-10,ACTIVE,False,None,NONE,1689573930068,16012161979.753164,654540.494819,REALTIME
15,ticker,KRW-ALGO,150.0,162.0,147.0,157.0,149.0,17962239370.920486,RISE,8.0,...,126.0,2023-06-10,ACTIVE,False,None,NONE,1689573931117,38968516811.937706,252988213.820866,REALTIME
16,ticker,KRW-ANKR,32.6,33.2,32.2,33.0,32.7,1676135889.409552,RISE,0.3,...,18.5,2022-12-30,ACTIVE,False,None,NONE,1689573930253,5167846130.898664,156007481.395809,REALTIME
17,ticker,KRW-XRP,961.0,975.0,956.0,961.0,961.0,105019938235.352066,EVEN,0.0,...,408.0,2023-01-02,ACTIVE,False,None,NONE,1689573933450,859933372844.560547,886957007.651079,REALTIME
18,ticker,KRW-MTL,1840.0,1875.0,1825.0,1845.0,1845.0,4576441304.633625,EVEN,0.0,...,800.0,2022-12-17,ACTIVE,False,None,NONE,1689573930061,9261164418.925146,5030479.746751,REALTIME
19,ticker,KRW-SUI,867.0,886.0,858.0,882.0,867.0,7009202402.029481,RISE,15.0,...,768.0,2023-06-12,ACTIVE,False,None,NONE,1689573930545,19640461731.697651,22421171.269553,REALTIME
20,ticker,KRW-STX,814.0,828.0,809.0,822.0,815.0,3504074807.789158,RISE,7.0,...,257.0,2022-12-29,ACTIVE,False,None,NONE,1689573930449,11630610353.784758,14170800.699537,REALTIME
21,ticker,KRW-MATIC,989.0,1010.0,981.0,1005.0,989.0,3298962499.706967,RISE,16.0,...,732.0,2023-06-10,ACTIVE,False,None,NONE,1689573900494,8648679912.177313,8630590.021628,SNAPSHOT
22,ticker,KRW-GMT,298.0,319.0,297.0,313.0,298.0,13493212400.795097,RISE,15.0,...,236.0,2023-06-15,ACTIVE,False,None,NONE,1689573931824,21138374381.471912,68679133.528802,REALTIME
23,ticker,KRW-ONT,264.0,270.0,262.0,267.0,264.0,874951822.510956,RISE,3.0,...,182.0,2022-12-30,ACTIVE,False,None,NONE,1689573930150,2275834659.354995,8549321.362087,REALTIME

In [255]:
current_dollar = 1270

def generate_upbit_binance_kimp_df(upbit_ticker_dict, upbit_orderbook_dict, binance_ticker_dict, binance_bookticker_dict):
    upbit_allticker_df = upbit_ticker_convert(upbit_ticker_dict)
    upbit_orderbook_df = upbit_orderbook_convert(upbit_orderbook_dict)
    binance_ticker_df = binance_ticker_convert(binance_ticker_dict)
    binance_bookticker_df = binance_bookticker_convert(binance_bookticker_dict)
    upbit_allticker_df = upbit_allticker_df.merge(upbit_orderbook_df, on='cd')
    upbit_allticker_df['base_symbol'] = upbit_allticker_df['cd'].apply(lambda x: x.replace('KRW-', ''))

    binance_allticker_df = binance_bookticker_df.merge(binance_ticker_df[['s','c','q']], on='s')
    binance_allticker_df['base_symbol'] = binance_bookticker_df['s'].apply(lambda x: x.replace('USDT', '').replace('USD_PERP',''))
    merged_allticker_df = upbit_allticker_df.merge(binance_allticker_df, on='base_symbol')
    merged_allticker_df.loc[:, ['a','b','c_y','q']] = merged_allticker_df[['a','b','c_y','q']].astype(float) # 'c_y' is a trade_price of binance
    merged_allticker_df[['binance_bid_price_krw', 'binance_trade_price_krw', 'binance_ask_price_krw']] = merged_allticker_df[['b','c_y','a']] * current_dollar
    merged_allticker_df['upbit_ask_price'] = merged_allticker_df['obu'].apply(lambda x: x[0]['ap'])
    merged_allticker_df['upbit_bid_price'] = merged_allticker_df['obu'].apply(lambda x: x[0]['bp'])
    merged_allticker_df['enter_kimp'] = (merged_allticker_df['upbit_ask_price'] - merged_allticker_df['binance_bid_price_krw']) / merged_allticker_df['binance_bid_price_krw']
    merged_allticker_df['exit_kimp'] = (merged_allticker_df['upbit_bid_price'] - merged_allticker_df['binance_ask_price_krw']) / merged_allticker_df['binance_ask_price_krw']
    merged_allticker_df['tp_kimp'] = (merged_allticker_df['tp'] - merged_allticker_df['binance_trade_price_krw']) / merged_allticker_df['binance_trade_price_krw']
    merged_allticker_df['enter_usdt'] = (merged_allticker_df['enter_kimp'] + 1) * current_dollar
    merged_allticker_df['exit_usdt'] = (merged_allticker_df['exit_kimp'] + 1) * current_dollar
    merged_allticker_df['tp_usdt'] = (merged_allticker_df['tp_kimp'] + 1) * current_dollar
    merged_allticker_df['upbit_ticker_ratio'] = merged_allticker_df['tp'].apply(lambda x: get_ticker_ratio(x))
    merged_allticker_df = merged_allticker_df.rename(columns={
        's':'symbol',
        'atp24h':'upbit_acc_trade_price_24h',
        'q':'binance_acc_trade_price_24h_usdt',
        'tp':'upbit_trade_price',
        'b':'binance_bid_price',
        'a':'binance_ask_price',
        'c_y':'binance_trade_price',
        'scr':'signed_change_rate',
        'ms':'upbit_market_state',
        'dd':'upbit_delisting_date',
        'mw':'upbit_market_warning',
        'its':'upbit_is_trading_suspended',
        'tms_x':'upbit_timestamp',
        'E':'binance_bookticker_event_time'
    })
    # SPOT bookticker doesn't have event_time, but it's not a problem.
    if 'binance_bookticker_event_time' not in merged_allticker_df.columns:
        merged_allticker_df['binance_bookticker_event_time'] = -1
    merged_allticker_df['binance_acc_trade_price_24h_krw'] = merged_allticker_df['binance_acc_trade_price_24h_usdt'] * current_dollar
    kimp_df = (merged_allticker_df[['symbol','upbit_acc_trade_price_24h','upbit_trade_price','upbit_ticker_ratio','upbit_ask_price','upbit_bid_price','binance_acc_trade_price_24h_usdt', 'binance_acc_trade_price_24h_krw',
    'binance_bid_price','binance_bid_price_krw','binance_trade_price','binance_trade_price_krw','binance_ask_price','binance_ask_price_krw','signed_change_rate','upbit_market_state','upbit_delisting_date',
    'upbit_market_warning','upbit_is_trading_suspended','upbit_timestamp','binance_bookticker_event_time',
    'enter_kimp', 'exit_kimp', 'tp_kimp',
    'enter_usdt', 'exit_usdt', 'tp_usdt']])
    return kimp_df

def generate_ohlc_df(df, freq='1T'):
    df = df.set_index(['symbol', 'datetime_now'])
    if 'tp_kimp' in df.columns:
        df['tp_kimp'] = pd.to_numeric(df['tp_kimp'], errors='coerce')
        ohlc_df = df.groupby(['symbol', pd.Grouper(level='datetime_now', freq=freq)])['tp_kimp'].ohlc()
    elif 'enter_kimp' in df.columns:
        df['enter_kimp'] = pd.to_numeric(df['enter_kimp'], errors='coerce')
        ohlc_df = df.groupby(['symbol', pd.Grouper(level='datetime_now', freq=freq)])['enter_kimp'].ohlc()
    elif 'exit_kimp' in df.columns:
        df['exit_kimp'] = pd.to_numeric(df['exit_kimp'], errors='coerce')
        ohlc_df = df.groupby(['symbol', pd.Grouper(level='datetime_now', freq=freq)])['exit_kimp'].ohlc()
    else:
        raise ValueError('There is no kimp column in the dataframe')
    return ohlc_df

In [150]:
redis_cli = InitRedis()

In [196]:
fetched_df.columns

Index(['symbol', 'upbit_acc_trade_price_24h', 'upbit_trade_price',
       'upbit_ticker_ratio', 'upbit_ask_price', 'upbit_bid_price',
       'binance_acc_trade_price_24h_usdt', 'binance_acc_trade_price_24h_krw',
       'binance_bid_price', 'binance_bid_price_krw', 'binance_trade_price',
       'binance_trade_price_krw', 'binance_ask_price', 'binance_ask_price_krw',
       'signed_change_rate', 'upbit_market_state', 'upbit_delisting_date',
       'upbit_market_warning', 'upbit_is_trading_suspended', 'upbit_timestamp',
       'binance_bookticker_event_time', 'enter_kimp', 'exit_kimp', 'tp_kimp',
       'enter_usdt', 'exit_usdt', 'tp_usdt'],
      dtype='object')

In [199]:
60 / 0.02

3000.0

In [216]:
datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')

'2023-07-18 20:02:03.982928'

In [240]:
test_appended_kimp_df[test_appended_kimp_df['datetime_now']<'2023-08-31 00:00:00.000000']

       symbol   tp_kimp      tp_usdt                datetime_now
0     BTCUSDT  0.009003  1281.434055  2023-07-18 20:07:29.453044
1     BCHUSDT  0.008457  1280.739844  2023-07-18 20:07:29.453044
2    KAVAUSDT   0.00938  1281.912004  2023-07-18 20:07:29.453044
3     SOLUSDT   0.00781  1279.918327  2023-07-18 20:07:29.453044
4   STORJUSDT  0.007732  1279.819471  2023-07-18 20:07:29.453044
..        ...       ...          ...                         ...
19    SUIUSDT  0.006627  1278.416689  2023-07-18 20:07:29.453044
20    STXUSDT  0.006757  1278.581428  2023-07-18 20:07:29.453044
21  MATICUSDT  0.008039  1280.209014  2023-07-18 20:07:29.453044
22    GMTUSDT  0.011624  1284.763024  2023-07-18 20:07:29.453044
23    ONTUSDT  0.008118  1280.310378  2023-07-18 20:07:29.453044

[3000 rows x 4 columns]

In [266]:
 
# start = time.time()
# appended_kimp_df = pd.DataFrame()
# start_datetime = datetime.datetime.now()
# while True:
#     if datetime.datetime.now() - start_datetime > datetime.timedelta(minutes=1):
#         break
#     kimp_df = generate_upbit_binance_kimp_df(upbit_ws.upbit_ticker_dict, upbit_ws.upbit_orderbook_dict, binance_ws.binance_usdm_ticker_dict, binance_ws.binance_usdm_bookticker_dict)
#     kimp_df['datetime_now'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
#     appended_kimp_df = pd.concat([appended_kimp_df, kimp_df], axis=0)

cut_i = 20000
column_list = ['symbol','tp_kimp','tp_usdt']
# print(f"generating_kimp_df: {time.time()-start}")
start = time.time()
test_appended_kimp_df = appended_kimp_df.iloc[:cut_i, :][column_list]
test_appended_kimp_df['datetime_now'] = datetime.datetime.now()#.strftime("%Y-%m-%d %H:%M:%S.%f")
# print(f"length of test_appended_kimp_df: {len(test_appended_kimp_df)}, size: {sys.getsizeof(test_appended_kimp_df) / 1024 / 1024}")
# appended_kimp_dict = test_appended_kimp_df.reset_index(drop=True).to_dict()
# print(f"converting df to dict: {time.time()-start}, size: {sys.getsizeof(appended_kimp_dict) / 1024 / 1024}")
# start = time.time()
# appended_kimp_pickle = pickle.dumps(appended_kimp_dict)
# print(f"converting df to pickle: {time.time()-start}, size: {sys.getsizeof(appended_kimp_pickle) / 1024 / 1024}")
# start = time.time()
# redis_cli.set_dict('kimp_dict', appended_kimp_dict)
# print(f"redis saving dict: {time.time()-start}")
# start = time.time()
# redis_cli.set_data('kimp_dict_pickle', appended_kimp_pickle)
# print(f"redis saving pickle: {time.time()-start}")
# start = time.time()
# fetched_dict = redis_cli.get_dict('kimp_dict')
# fetched_df = pd.DataFrame(fetched_dict)
# # fetched_df.loc[:, 'datetime_now'] = pd.to_datetime(fetched_df['datetime_now'])
# print(f"redis fetching dict: {time.time()-start}")
# start = time.time()
# fetched_pickle = redis_cli.get_data('kimp_dict_pickle')
# fetched_df = pd.DataFrame(pickle.loads(fetched_pickle))
# # fetched_df.loc[:, 'datetime_now'] = pd.to_datetime(fetched_df['datetime_now'])
# print(f"redis fetching pickle: {time.time()-start}")

In [267]:
len(test_appended_kimp_df)

20000

In [270]:
kimp_df = generate_upbit_binance_kimp_df(upbit_ws.upbit_ticker_dict, upbit_ws.upbit_orderbook_dict, binance_ws.binance_usdm_ticker_dict, binance_ws.binance_usdm_bookticker_dict)
kimp_df['datetime_now'] = datetime.datetime.now()#.strftime("%Y-%m-%d %H:%M:%S.%f")
start = time.time()
ohlc_df = generate_ohlc_df(test_appended_kimp_df, freq='1T')
print(f"generating ohlc df: {time.time()-start}")
ohlc_df

generating ohlc df: 0.015347003936767578

                                   open      high       low     close
symbol    datetime_now
AAVEUSDT  2023-07-18 22:07:00  0.008971  0.009380  0.008835  0.009244
ALGOUSDT  2023-07-18 22:07:00  0.014280  0.015140  0.014280  0.015140
ANKRUSDT  2023-07-18 22:07:00  0.009961  0.009961  0.009961  0.009961
BCHUSDT   2023-07-18 22:07:00  0.008457  0.008878  0.008457  0.008878
BTCUSDT   2023-07-18 22:07:00  0.009003  0.009141  0.008947  0.009138
DOGEUSDT  2023-07-18 22:07:00  0.007865  0.008010  0.007720  0.008010
ETCUSDT   2023-07-18 22:07:00  0.008681  0.008893  0.008681  0.008840
ETHUSDT   2023-07-18 22:07:00  0.008445  0.008625  0.008434  0.008620
FLOWUSDT  2023-07-18 22:07:00  0.009770  0.009770  0.008554  0.008554
GMTUSDT   2023-07-18 22:07:00  0.010833  0.011624  0.010833  0.011228
KAVAUSDT  2023-07-18 22:07:00  0.009380  0.009818  0.009380  0.009599
MATICUSDT 2023-07-18 22:07:00  0.008039  0.008170  0.007907  0.008170
MTLUSDT   2023-07-18 22:07:00  0.008262  0.008478  0.008189  0.008262
ONTUSDT   2023-07-18 22:07:00  0.008118  0.009097  0.008118  0.009097
SANDUSDT  2023-07-18 22:07:00  0.007326  0.008226  0.007326  0.008001
SOLUSDT   2023-07-18 22:07:00  0.007810  0.008343  0.007772  0.008343
STORJUSDT 2023-07-18 22:07:00  0.007732  0.008057  0.007732  0.007732
STXUSDT   2023-07-18 22:07:00  0.006914  0.008452  0.006757  0.008452
SUIUSDT   2023-07-18 22:07:00  0.006627  0.008220  0.006493  0.008085
SXPUSDT   2023-07-18 22:07:00  0.007262  0.007791  0.007262  0.007526
TUSDT     2023-07-18 22:07:00  0.007744  0.008575  0.005331  0.005746
WAVESUSDT 2023-07-18 22:07:00  0.007312  0.007362  0.007312  0.007362
XEMUSDT   2023-07-18 22:07:00  0.008611  0.008611  0.005249  0.005249
XRPUSDT   2023-07-18 22:07:00  0.008374  0.010387  0.008239  0.009353

In [287]:
60/23000

0.0026086956521739132

In [299]:

def ohlc_loader(redis_cli, loop_downtime_sec=0.01):
    appended_kimp_df = pd.DataFrame()
    kline_switch = False
    while True:
        time.sleep(loop_downtime_sec)
        kimp_df = generate_upbit_binance_kimp_df(upbit_ws.upbit_ticker_dict, upbit_ws.upbit_orderbook_dict, binance_ws.binance_usdm_ticker_dict, binance_ws.binance_usdm_bookticker_dict)
        datetime_now = datetime.datetime.now()
        kimp_df['datetime_now'] = datetime_now
        appended_kimp_df = pd.concat([appended_kimp_df, kimp_df], axis=0)
        # print(f"redis saving ohlc_1m_now time: {time.time()-start}")
        if datetime_now.second == 0 and kline_switch == True:
            adjusted_datetime_now = datetime.datetime(datetime_now.year, datetime_now.month, datetime_now.day, datetime_now.hour, datetime_now.minute)
            cut_appended_kimp_df = appended_kimp_df[appended_kimp_df['datetime_now'] < adjusted_datetime_now]
            start = time.time()
            ohlc_df = generate_ohlc_df(cut_appended_kimp_df)
            print(f"generating ohlc_df(length: {len(cut_appended_kimp_df)}): {time.time()-start}")
            # INSERT into redis db for current data
            start = time.time()
            redis_cli.set_data('ohlc_1m_now', pickle.dumps(ohlc_df))
            print(f"redis saving ohlc_1m_now time: {time.time()-start}")
            # Append into redis db for historical data
            start = time.time()
            old_ohlc_1m_kline = redis_cli.get_data('ohlc_1m_kline')
            if old_ohlc_1m_kline is None:
                old_ohlc_1m_kline = pd.DataFrame()
            else:
                old_ohlc_1m_kline = pickle.loads(old_ohlc_1m_kline)
            new_ohlc_1m_kline = pd.concat([old_ohlc_1m_kline, ohlc_df], axis=0)
            redis_cli.set_data('ohlc_1m_kline', pickle.dumps(new_ohlc_1m_kline))
            print(f"redis ohlc_1m_kline load and saving time after appending: {time.time()-start}")
            appended_kimp_df = appended_kimp_df[appended_kimp_df['datetime_now'] >= adjusted_datetime_now]
            kline_switch = False
        elif datetime_now.second != 0:
            # INSERT into redis db for current data
            ohlc_df = generate_ohlc_df(appended_kimp_df)
            redis_cli.set_data('ohlc_1m_now', pickle.dumps(ohlc_df))
            kline_switch = True
        else:
            # INSERT into redis db for current data
            ohlc_df = generate_ohlc_df(appended_kimp_df)
            redis_cli.set_data('ohlc_1m_now', pickle.dumps(ohlc_df))

ohlc_loader_proc = Process(target=ohlc_loader, args=(redis_cli,), daemon=True)
ohlc_loader_proc.start()

generating ohlc_df(length: 18936): 0.058554649353027344
redis saving ohlc_1m_now time: 0.0005478858947753906
redis ohlc_1m_kline load and saving time after appending: 0.002550840377807617
generating ohlc_df(length: 20544): 0.048239707946777344
redis saving ohlc_1m_now time: 0.0007450580596923828
redis ohlc_1m_kline load and saving time after appending: 0.002869129180908203
generating ohlc_df(length: 20640): 0.04867291450500488
redis saving ohlc_1m_now time: 0.0004830360412597656
redis ohlc_1m_kline load and saving time after appending: 0.0026514530181884766
generating ohlc_df(length: 20784): 0.05079174041748047
redis saving ohlc_1m_now time: 0.0005357265472412109
redis ohlc_1m_kline load and saving time after appending: 0.0023953914642333984
generating ohlc_df(length: 20712): 0.04863739013671875
redis saving ohlc_1m_now time: 0.0007083415985107422
redis ohlc_1m_kline load and saving time after appending: 0.005545616149902344
generating ohlc_df(length: 20928): 0.044495344161987305
redis saving ohlc_1m_now time: 0.0004591941833496094
redis ohlc_1m_kline load and saving time after appending: 0.003651142120361328
generating ohlc_df(length: 20616): 0.04509854316711426
redis saving ohlc_1m_now time: 0.0008757114410400391
redis ohlc_1m_kline load and saving time after appending: 0.003164052963256836
generating ohlc_df(length: 20592): 0.043210744857788086
redis saving ohlc_1m_now time: 0.0006608963012695312
redis ohlc_1m_kline load and saving time after appending: 0.003489971160888672
generating ohlc_df(length: 20952): 0.049440622329711914
redis saving ohlc_1m_now time: 0.0006074905395507812
redis ohlc_1m_kline load and saving time after appending: 0.0032129287719726562
generating ohlc_df(length: 20952): 0.04822063446044922
redis saving ohlc_1m_now time: 0.0006506443023681641
redis ohlc_1m_kline load and saving time after appending: 0.0032813549041748047
generating ohlc_df(length: 20856): 0.04970598220825195
redis saving ohlc_1m_now time: 0.0006439685821533203
redis ohlc_1m_kline load and saving time after appending: 0.0032286643981933594
generating ohlc_df(length: 21048): 0.05011916160583496
redis saving ohlc_1m_now time: 0.0006015300750732422
redis ohlc_1m_kline load and saving time after appending: 0.003615140914916992
generating ohlc_df(length: 20664): 0.048036813735961914
redis saving ohlc_1m_now time: 0.0004999637603759766
redis ohlc_1m_kline load and saving time after appending: 0.0029795169830322266
generating ohlc_df(length: 20616): 0.04963207244873047
redis saving ohlc_1m_now time: 0.0005478858947753906
redis ohlc_1m_kline load and saving time after appending: 0.0033600330352783203
generating ohlc_df(length: 20784): 0.04797005653381348
redis saving ohlc_1m_now time: 0.0007011890411376953
redis ohlc_1m_kline load and saving time after appending: 0.002871990203857422
generating ohlc_df(length: 20688): 0.04709029197692871
redis saving ohlc_1m_now time: 0.0006532669067382812
redis ohlc_1m_kline load and saving time after appending: 0.004026174545288086
generating ohlc_df(length: 20880): 0.049047231674194336
redis saving ohlc_1m_now time: 0.0006763935089111328
redis ohlc_1m_kline load and saving time after appending: 0.002802133560180664
generating ohlc_df(length: 20784): 0.048876047134399414
redis saving ohlc_1m_now time: 0.0007109642028808594
redis ohlc_1m_kline load and saving time after appending: 0.003560304641723633
generating ohlc_df(length: 20856): 0.04966545104980469
redis saving ohlc_1m_now time: 0.0006468296051025391
redis ohlc_1m_kline load and saving time after appending: 0.0030252933502197266
generating ohlc_df(length: 20256): 0.04967212677001953
redis saving ohlc_1m_now time: 0.0004923343658447266
redis ohlc_1m_kline load and saving time after appending: 0.003502368927001953
generating ohlc_df(length: 20112): 0.05072140693664551
redis saving ohlc_1m_now time: 0.0006413459777832031
redis ohlc_1m_kline load and saving time after appending: 0.0027582645416259766
generating ohlc_df(length: 19920): 0.05042266845703125
redis saving ohlc_1m_now time: 0.0006859302520751953
redis ohlc_1m_kline load and saving time after appending: 0.0040760040283203125
generating ohlc_df(length: 20040): 0.04703664779663086
redis saving ohlc_1m_now time: 0.0007131099700927734
redis ohlc_1m_kline load and saving time after appending: 0.003779888153076172
generating ohlc_df(length: 20568): 0.05239224433898926
redis saving ohlc_1m_now time: 0.0006794929504394531
redis ohlc_1m_kline load and saving time after appending: 0.0032067298889160156
generating ohlc_df(length: 20520): 0.047643423080444336
redis saving ohlc_1m_now time: 0.0006151199340820312
redis ohlc_1m_kline load and saving time after appending: 0.0033528804779052734
generating ohlc_df(length: 20496): 0.047782182693481445
redis saving ohlc_1m_now time: 0.00040721893310546875
redis ohlc_1m_kline load and saving time after appending: 0.002994537353515625
generating ohlc_df(length: 20280): 0.04972696304321289
redis saving ohlc_1m_now time: 0.0004775524139404297
redis ohlc_1m_kline load and saving time after appending: 0.003332853317260742
generating ohlc_df(length: 20664): 0.05045056343078613
redis saving ohlc_1m_now time: 0.00046706199645996094
redis ohlc_1m_kline load and saving time after appending: 0.0032236576080322266
generating ohlc_df(length: 20376): 0.0485234260559082
redis saving ohlc_1m_now time: 0.00046181678771972656
redis ohlc_1m_kline load and saving time after appending: 0.003207683563232422
generating ohlc_df(length: 20232): 0.049349308013916016
redis saving ohlc_1m_now time: 0.00044798851013183594
redis ohlc_1m_kline load and saving time after appending: 0.002574920654296875
generating ohlc_df(length: 20112): 0.0545804500579834
redis saving ohlc_1m_now time: 0.000560760498046875
redis ohlc_1m_kline load and saving time after appending: 0.003709077835083008
generating ohlc_df(length: 20448): 0.04596972465515137
redis saving ohlc_1m_now time: 0.0005090236663818359
redis ohlc_1m_kline load and saving time after appending: 0.004305124282836914
generating ohlc_df(length: 20472): 0.05226850509643555
redis saving ohlc_1m_now time: 0.0007274150848388672
redis ohlc_1m_kline load and saving time after appending: 0.003933906555175781
generating ohlc_df(length: 20496): 0.050824880599975586
redis saving ohlc_1m_now time: 0.0004532337188720703
redis ohlc_1m_kline load and saving time after appending: 0.002477407455444336
generating ohlc_df(length: 20496): 0.05107855796813965
redis saving ohlc_1m_now time: 0.0007081031799316406
redis ohlc_1m_kline load and saving time after appending: 0.0043370723724365234
generating ohlc_df(length: 20616): 0.050710201263427734
redis saving ohlc_1m_now time: 0.0007336139678955078
redis ohlc_1m_kline load and saving time after appending: 0.003432750701904297
generating ohlc_df(length: 19944): 0.051003456115722656
redis saving ohlc_1m_now time: 0.00051116943359375
redis ohlc_1m_kline load and saving time after appending: 0.003038167953491211
generating ohlc_df(length: 20184): 0.060129642486572266
redis saving ohlc_1m_now time: 0.0005629062652587891
redis ohlc_1m_kline load and saving time after appending: 0.0033423900604248047
generating ohlc_df(length: 19968): 0.05042839050292969
redis saving ohlc_1m_now time: 0.0007872581481933594
redis ohlc_1m_kline load and saving time after appending: 0.0032112598419189453
generating ohlc_df(length: 19488): 0.053014278411865234
redis saving ohlc_1m_now time: 0.0005767345428466797
redis ohlc_1m_kline load and saving time after appending: 0.002897977828979492
generating ohlc_df(length: 20112): 0.0536046028137207
redis saving ohlc_1m_now time: 0.0005438327789306641
redis ohlc_1m_kline load and saving time after appending: 0.004528522491455078
generating ohlc_df(length: 20112): 0.04816842079162598
redis saving ohlc_1m_now time: 0.0006449222564697266
redis ohlc_1m_kline load and saving time after appending: 0.0038149356842041016
generating ohlc_df(length: 20328): 0.051291465759277344
redis saving ohlc_1m_now time: 0.0004966259002685547
redis ohlc_1m_kline load and saving time after appending: 0.0034945011138916016
generating ohlc_df(length: 20280): 0.0588228702545166
redis saving ohlc_1m_now time: 0.0005137920379638672
redis ohlc_1m_kline load and saving time after appending: 0.0030143260955810547
generating ohlc_df(length: 20016): 0.05084824562072754
redis saving ohlc_1m_now time: 0.0004673004150390625
redis ohlc_1m_kline load and saving time after appending: 0.0033249855041503906
generating ohlc_df(length: 20328): 0.05368518829345703
redis saving ohlc_1m_now time: 0.0006635189056396484
redis ohlc_1m_kline load and saving time after appending: 0.003203868865966797
generating ohlc_df(length: 20232): 0.05505037307739258
redis saving ohlc_1m_now time: 0.0007119178771972656
redis ohlc_1m_kline load and saving time after appending: 0.0033822059631347656
generating ohlc_df(length: 20352): 0.05635404586791992
redis saving ohlc_1m_now time: 0.0005636215209960938
redis ohlc_1m_kline load and saving time after appending: 0.003875255584716797
generating ohlc_df(length: 20256): 0.060732364654541016
redis saving ohlc_1m_now time: 0.0007419586181640625
redis ohlc_1m_kline load and saving time after appending: 0.0032994747161865234
generating ohlc_df(length: 20040): 0.05711650848388672
redis saving ohlc_1m_now time: 0.0006723403930664062
redis ohlc_1m_kline load and saving time after appending: 0.0039899349212646484
generating ohlc_df(length: 20016): 0.05263781547546387
redis saving ohlc_1m_now time: 0.0006108283996582031
redis ohlc_1m_kline load and saving time after appending: 0.0035865306854248047
generating ohlc_df(length: 20040): 0.05262470245361328
redis saving ohlc_1m_now time: 0.00055694580078125
redis ohlc_1m_kline load and saving time after appending: 0.0037157535552978516
generating ohlc_df(length: 20136): 0.05558943748474121
redis saving ohlc_1m_now time: 0.000823974609375
redis ohlc_1m_kline load and saving time after appending: 0.0036411285400390625
generating ohlc_df(length: 20184): 0.05214214324951172
redis saving ohlc_1m_now time: 0.0005130767822265625
redis ohlc_1m_kline load and saving time after appending: 0.003473043441772461
generating ohlc_df(length: 19920): 0.05739736557006836
redis saving ohlc_1m_now time: 0.00077056884765625
redis ohlc_1m_kline load and saving time after appending: 0.0039713382720947266
generating ohlc_df(length: 20136): 0.049523353576660156
redis saving ohlc_1m_now time: 0.0004601478576660156
redis ohlc_1m_kline load and saving time after appending: 0.0036554336547851562
generating ohlc_df(length: 20040): 0.056020498275756836
redis saving ohlc_1m_now time: 0.0008618831634521484
redis ohlc_1m_kline load and saving time after appending: 0.002812623977661133
generating ohlc_df(length: 20232): 0.052863359451293945
redis saving ohlc_1m_now time: 0.0006511211395263672
redis ohlc_1m_kline load and saving time after appending: 0.003377199172973633
generating ohlc_df(length: 19968): 0.06348061561584473
redis saving ohlc_1m_now time: 0.0005948543548583984
redis ohlc_1m_kline load and saving time after appending: 0.0026924610137939453
generating ohlc_df(length: 19512): 0.05406332015991211
redis saving ohlc_1m_now time: 0.0005853176116943359
redis ohlc_1m_kline load and saving time after appending: 0.003894329071044922
generating ohlc_df(length: 19944): 0.05491518974304199
redis saving ohlc_1m_now time: 0.0006341934204101562
redis ohlc_1m_kline load and saving time after appending: 0.0031499862670898438
generating ohlc_df(length: 19920): 0.0564877986907959
redis saving ohlc_1m_now time: 0.0007169246673583984
redis ohlc_1m_kline load and saving time after appending: 0.003991603851318359
generating ohlc_df(length: 20088): 0.05054116249084473
redis saving ohlc_1m_now time: 0.0005593299865722656
redis ohlc_1m_kline load and saving time after appending: 0.005151271820068359
generating ohlc_df(length: 19896): 0.05119919776916504
redis saving ohlc_1m_now time: 0.0004944801330566406
redis ohlc_1m_kline load and saving time after appending: 0.004933357238769531
generating ohlc_df(length: 19776): 0.053848981857299805
redis saving ohlc_1m_now time: 0.0006334781646728516
redis ohlc_1m_kline load and saving time after appending: 0.0036242008209228516
generating ohlc_df(length: 19680): 0.055066585540771484
redis saving ohlc_1m_now time: 0.0005567073822021484
redis ohlc_1m_kline load and saving time after appending: 0.003049612045288086
generating ohlc_df(length: 20112): 0.04978680610656738
redis saving ohlc_1m_now time: 0.0006041526794433594
redis ohlc_1m_kline load and saving time after appending: 0.004996776580810547
generating ohlc_df(length: 20160): 0.051915645599365234
redis saving ohlc_1m_now time: 0.0006911754608154297
redis ohlc_1m_kline load and saving time after appending: 0.0030946731567382812
generating ohlc_df(length: 20016): 0.06017780303955078
redis saving ohlc_1m_now time: 0.0005862712860107422
redis ohlc_1m_kline load and saving time after appending: 0.002967357635498047
generating ohlc_df(length: 19944): 0.05255770683288574
redis saving ohlc_1m_now time: 0.0006871223449707031
redis ohlc_1m_kline load and saving time after appending: 0.0035631656646728516
generating ohlc_df(length: 20160): 0.05116105079650879
redis saving ohlc_1m_now time: 0.0007669925689697266
redis ohlc_1m_kline load and saving time after appending: 0.00341033935546875
generating ohlc_df(length: 20208): 0.05216813087463379
redis saving ohlc_1m_now time: 0.0005908012390136719
redis ohlc_1m_kline load and saving time after appending: 0.0037958621978759766
generating ohlc_df(length: 20184): 0.06158566474914551
redis saving ohlc_1m_now time: 0.0006539821624755859
redis ohlc_1m_kline load and saving time after appending: 0.004509925842285156
generating ohlc_df(length: 20064): 0.06300687789916992
redis saving ohlc_1m_now time: 0.0007119178771972656
redis ohlc_1m_kline load and saving time after appending: 0.0034155845642089844
generating ohlc_df(length: 20040): 0.0528256893157959
redis saving ohlc_1m_now time: 0.0007779598236083984
redis ohlc_1m_kline load and saving time after appending: 0.004396677017211914
generating ohlc_df(length: 20256): 0.06261515617370605
redis saving ohlc_1m_now time: 0.0006206035614013672
redis ohlc_1m_kline load and saving time after appending: 0.0036699771881103516
generating ohlc_df(length: 20040): 0.054839372634887695
redis saving ohlc_1m_now time: 0.0007588863372802734
redis ohlc_1m_kline load and saving time after appending: 0.003039121627807617
generating ohlc_df(length: 19992): 0.051834821701049805
redis saving ohlc_1m_now time: 0.00048470497131347656
redis ohlc_1m_kline load and saving time after appending: 0.002969980239868164
generating ohlc_df(length: 20160): 0.055164337158203125
redis saving ohlc_1m_now time: 0.0009458065032958984
redis ohlc_1m_kline load and saving time after appending: 0.005364656448364258
generating ohlc_df(length: 19944): 0.05498695373535156
redis saving ohlc_1m_now time: 0.0007414817810058594
redis ohlc_1m_kline load and saving time after appending: 0.0030057430267333984
generating ohlc_df(length: 19728): 0.052257537841796875
redis saving ohlc_1m_now time: 0.0005958080291748047
redis ohlc_1m_kline load and saving time after appending: 0.0030562877655029297
generating ohlc_df(length: 19848): 0.056543827056884766
redis saving ohlc_1m_now time: 0.0007498264312744141
redis ohlc_1m_kline load and saving time after appending: 0.0038728713989257812
generating ohlc_df(length: 19896): 0.05469846725463867
redis saving ohlc_1m_now time: 0.0006308555603027344
redis ohlc_1m_kline load and saving time after appending: 0.0033597946166992188
generating ohlc_df(length: 20256): 0.053582191467285156
redis saving ohlc_1m_now time: 0.0004425048828125
redis ohlc_1m_kline load and saving time after appending: 0.003718137741088867
generating ohlc_df(length: 19896): 0.054726362228393555
redis saving ohlc_1m_now time: 0.0006673336029052734
redis ohlc_1m_kline load and saving time after appending: 0.0036334991455078125
generating ohlc_df(length: 20160): 0.05550742149353027
redis saving ohlc_1m_now time: 0.0007030963897705078
redis ohlc_1m_kline load and saving time after appending: 0.003631114959716797
generating ohlc_df(length: 20040): 0.050230979919433594
redis saving ohlc_1m_now time: 0.0005364418029785156
redis ohlc_1m_kline load and saving time after appending: 0.0045087337493896484
generating ohlc_df(length: 20040): 0.050017356872558594
redis saving ohlc_1m_now time: 0.0005574226379394531
redis ohlc_1m_kline load and saving time after appending: 0.0039272308349609375
generating ohlc_df(length: 20016): 0.05984210968017578
redis saving ohlc_1m_now time: 0.0005545616149902344
redis ohlc_1m_kline load and saving time after appending: 0.0031731128692626953
generating ohlc_df(length: 19920): 0.05473494529724121
redis saving ohlc_1m_now time: 0.0005517005920410156
redis ohlc_1m_kline load and saving time after appending: 0.003347158432006836
generating ohlc_df(length: 20112): 0.06118607521057129
redis saving ohlc_1m_now time: 0.0006468296051025391
redis ohlc_1m_kline load and saving time after appending: 0.004175662994384766
generating ohlc_df(length: 20256): 0.0546107292175293
redis saving ohlc_1m_now time: 0.00048804283142089844
redis ohlc_1m_kline load and saving time after appending: 0.0038366317749023438
generating ohlc_df(length: 20256): 0.05397152900695801
redis saving ohlc_1m_now time: 0.0006654262542724609
redis ohlc_1m_kline load and saving time after appending: 0.004132747650146484
generating ohlc_df(length: 20400): 0.052206993103027344
redis saving ohlc_1m_now time: 0.0007226467132568359
redis ohlc_1m_kline load and saving time after appending: 0.004053831100463867
generating ohlc_df(length: 20160): 0.055680036544799805
redis saving ohlc_1m_now time: 0.0005917549133300781
redis ohlc_1m_kline load and saving time after appending: 0.0031442642211914062
generating ohlc_df(length: 20112): 0.06160855293273926
redis saving ohlc_1m_now time: 0.0004470348358154297
redis ohlc_1m_kline load and saving time after appending: 0.0031614303588867188
generating ohlc_df(length: 19872): 0.05672717094421387
redis saving ohlc_1m_now time: 0.0005598068237304688
redis ohlc_1m_kline load and saving time after appending: 0.0042459964752197266
generating ohlc_df(length: 20088): 0.05318307876586914
redis saving ohlc_1m_now time: 0.0006561279296875
redis ohlc_1m_kline load and saving time after appending: 0.0036034584045410156
generating ohlc_df(length: 19944): 0.05357766151428223
redis saving ohlc_1m_now time: 0.0006954669952392578
redis ohlc_1m_kline load and saving time after appending: 0.0036356449127197266
generating ohlc_df(length: 19872): 0.052934885025024414
redis saving ohlc_1m_now time: 0.0006124973297119141
redis ohlc_1m_kline load and saving time after appending: 0.0035817623138427734
generating ohlc_df(length: 19944): 0.05847620964050293
redis saving ohlc_1m_now time: 0.0004763603210449219
redis ohlc_1m_kline load and saving time after appending: 0.0038385391235351562
generating ohlc_df(length: 20160): 0.0525662899017334
redis saving ohlc_1m_now time: 0.0006039142608642578
redis ohlc_1m_kline load and saving time after appending: 0.003777027130126953
generating ohlc_df(length: 19920): 0.04948854446411133
redis saving ohlc_1m_now time: 0.0005292892456054688
redis ohlc_1m_kline load and saving time after appending: 0.0034666061401367188
generating ohlc_df(length: 19968): 0.05533146858215332
redis saving ohlc_1m_now time: 0.0006060600280761719
redis ohlc_1m_kline load and saving time after appending: 0.0033860206604003906
generating ohlc_df(length: 19872): 0.06494474411010742
redis saving ohlc_1m_now time: 0.0006010532379150391
redis ohlc_1m_kline load and saving time after appending: 0.0032765865325927734
generating ohlc_df(length: 19968): 0.06218886375427246
redis saving ohlc_1m_now time: 0.0006973743438720703
redis ohlc_1m_kline load and saving time after appending: 0.003446340560913086
generating ohlc_df(length: 20232): 0.05519986152648926

In [413]:
ohlc_loader_proc.terminate()
time.sleep(1)
ohlc_loader_proc.is_alive()

False

In [411]:
pickle.loads(redis_cli.get_data('ohlc_1m_now')).reset_index()

       symbol        datetime_now      open      high       low     close
0    AAVEUSDT 2023-07-19 19:43:00  0.011174  0.011735  0.011174  0.011595
1    ALGOUSDT 2023-07-19 19:43:00  0.011977  0.011977  0.011977  0.011977
2    ANKRUSDT 2023-07-19 19:43:00  0.013050  0.013050  0.013050  0.013050
3     BCHUSDT 2023-07-19 19:43:00  0.012520  0.012520  0.012273  0.012314
4     BTCUSDT 2023-07-19 19:43:00  0.012583  0.012583  0.012144  0.012439
5    DOGEUSDT 2023-07-19 19:43:00  0.012537  0.012684  0.012390  0.012537
6     ETCUSDT 2023-07-19 19:43:00  0.012356  0.012356  0.012248  0.012302
7     ETHUSDT 2023-07-19 19:43:00  0.011711  0.011722  0.011700  0.011700
8    FLOWUSDT 2023-07-19 19:43:00  0.012907  0.014513  0.012907  0.014513
9     GMTUSDT 2023-07-19 19:43:00  0.011801  0.011801  0.010944  0.011801
10   KAVAUSDT 2023-07-19 19:43:00  0.010601  0.010601  0.010045  0.010156
11  MATICUSDT 2023-07-19 19:43:00  0.012449  0.012722  0.012449  0.012449
12    MTLUSDT 2023-07-19 19:43:00  0.014104  0.014104  0.014030  0.014030
13    ONTUSDT 2023-07-19 19:43:00  0.008883  0.008883  0.008378  0.008883
14   SANDUSDT 2023-07-19 19:43:00  0.012781  0.012781  0.012323  0.012323
15    SOLUSDT 2023-07-19 19:43:00  0.011630  0.011937  0.011284  0.011322
16  STORJUSDT 2023-07-19 19:43:00  0.013538  0.013538  0.013210  0.013210
17    STXUSDT 2023-07-19 19:43:00  0.012177  0.012177  0.012017  0.012017
18    SUIUSDT 2023-07-19 19:43:00  0.013929  0.014210  0.012140  0.012140
19    SXPUSDT 2023-07-19 19:43:00  0.012589  0.012589  0.012589  0.012589
20      TUSDT 2023-07-19 19:43:00  0.013553  0.013978  0.013553  0.013978
21  WAVESUSDT 2023-07-19 19:43:00  0.010840  0.010892  0.008866  0.008866
22    XEMUSDT 2023-07-19 19:43:00  0.014693  0.018192  0.014693  0.018192
23    XRPUSDT 2023-07-19 19:43:00  0.013310  0.013438  0.012671  0.013310

In [412]:
temp = pickle.loads(redis_cli.get_data('ohlc_1m_kline')).reset_index()
temp[temp['symbol']=='BTCUSDT']

        symbol        datetime_now      open      high       low     close
4      BTCUSDT 2023-07-19 12:41:00  0.013161  0.013688  0.013161  0.013688
28     BTCUSDT 2023-07-19 12:42:00  0.013684  0.013769  0.013157  0.013160
52     BTCUSDT 2023-07-19 12:43:00  0.013160  0.013553  0.012979  0.013097
76     BTCUSDT 2023-07-19 12:44:00  0.013097  0.013235  0.012123  0.012462
100    BTCUSDT 2023-07-19 12:45:00  0.012462  0.012720  0.012378  0.012464
...        ...                 ...       ...       ...       ...       ...
10012  BTCUSDT 2023-07-19 19:38:00  0.012108  0.012108  0.011274  0.011274
10036  BTCUSDT 2023-07-19 19:39:00  0.011274  0.011277  0.011214  0.011217
10060  BTCUSDT 2023-07-19 19:40:00  0.011217  0.011234  0.010721  0.010987
10084  BTCUSDT 2023-07-19 19:41:00  0.010987  0.011697  0.010984  0.011286
10108  BTCUSDT 2023-07-19 19:42:00  0.011286  0.012791  0.011286  0.012583

[422 rows x 6 columns]

In [51]:
# Check the size of an object in Mb
import sys
sys.getsizeof(kimp_cache_df) / 1024 / 1024

32.36960315704346