In [6]:
import datetime
import pandas as pd
import requests
import os
import sys
from acw_api import AcwApi
import json
import time

with open("/home/trade_core/trade_core_config.json") as f:
    config = json.load(f)

In [57]:
class AcwApi:
    def __init__(self, prod=False):
        if prod is False:
            self.verify = False
            self.url = config['acw_setting']['dev_url']
        else:
            self.verify = True
            self.url = config['acw_setting']['prod_url']
        self.message_url = "messagecore/messages/"
        self.node_url = "tradecore/nodes/"
        self.kline_url = "infocore/kline/"

    def get_message(self, id=None):
        url = self.url + self.message_url
        if id is not None:
            fetch_list = False
            response = requests.get(url + str(id) + "/", verify=self.verify)
        else:
            fetch_list = True
            response = requests.get(url, verify=self.verify)
        if response.status_code == 200:
            if fetch_list:
                return pd.DataFrame(response.json()["results"])
            else:
                return pd.DataFrame([response.json()])
        else:
            raise Exception("Error: " + str(response.status_code) + "\n" + response.text)
        
    def create_message(self, telegram_chat_id, title, origin, type, content=None, remark=None, code=None, sent=False, send_times=1, send_term=1):
        url = self.url + self.message_url
        new_message_dict = {
            "datetime": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            "telegram_chat_id": telegram_chat_id,
            "title": title,
            "origin": origin,
            "type": type,
            "content": content,
            "remark": remark,
            "code": code,
            "sent": sent,
            "send_times": send_times,
            "send_term": send_term
        }
        response = requests.post(url, json=new_message_dict, verify=self.verify)
        if response.status_code == 201:
            return response.json()
        else:
            raise Exception("Error: " + str(response.status_code) + "\n" + response.text)

    def delete_message(self, id):
        url = self.url + self.message_url
        response = requests.delete(url + str(id) + "/", verify=self.verify)
        if response.status_code == 204:
            return True
        else:
            raise Exception("Error: " + str(response.status_code) + "\n" + response.text)
        
    def get_node(self, id=None):
        url = self.url + self.node_url
        if id is not None:
            fetch_list = False
            response = requests.get(url + str(id) + "/", verify=self.verify)
        else:
            fetch_list = True
            response = requests.get(url, verify=self.verify)
        if response.status_code == 200:
            if fetch_list:
                return pd.DataFrame(response.json()["results"])
            else:
                return pd.DataFrame([response.json()])
        else:
            raise Exception("Error: " + str(response.status_code) + "\n" + response.text)
        
    def get_kline(self, target_market_code, origin_market_code, base_asset, interval, start_time=None, end_time=None):
        url = self.url + self.kline_url
        params = {
            "target_market_code": target_market_code,
            "origin_market_code": origin_market_code,
            "base_asset": base_asset,
            "interval": interval,
            "start_time": start_time.strftime("%Y-%m-%dT%H:%M:%S") if start_time is not None else None,
            "end_time": end_time.strftime("%Y-%m-%dT%H:%M:%S") if end_time is not None else None
        }
        response = requests.get(url, params=params, verify=self.verify)
        if response.status_code == 200:
            return pd.DataFrame(response.json())
        else:
            raise Exception("Error: " + str(response.status_code) + "\n" + response.text)

In [58]:
acw_api = AcwApi(prod=False)

In [67]:
start = time.time()
kline_df = acw_api.get_kline('UPBIT_SPOT/KRW', 'BINANCE_USD_M/USDT', 'BTC', '1T', start_time=datetime.datetime.now()+datetime.timedelta(hours=999), end_time=datetime.datetime.now()+datetime.timedelta(hours=0))
print(time.time()-start)

0.16115975379943848

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-test.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [68]:
kline_df

,base_asset,datetime_now,tp_open,tp_high,tp_low,tp_close,LS_open,LS_high,LS_low,LS_close,SL_open,SL_high,SL_low,SL_close,dollar,tp,scr,atp24h,converted_tp,closed
0,BTC,2024-02-15T11:24:00+0000,2.485256,2.485256,2.439688,2.445420,2.484019,2.484019,2.441121,2.445420,2.482390,2.482390,2.439492,2.440925,1333.0,71485000.0,1.831935,6.055363e+11,69778619.60,True
1,BTC,2024-02-15T11:25:00+0000,2.445420,2.482582,2.438059,2.478735,2.445420,2.482778,2.441121,2.479385,2.440925,2.481148,2.436626,2.477755,1333.0,71480000.0,1.824812,6.058168e+11,69750080.56,True
2,BTC,2024-02-15T11:26:00+0000,2.480168,2.480168,2.433760,2.435388,2.460578,2.460578,2.435388,2.435388,2.458949,2.458949,2.433760,2.433760,1333.0,71478000.0,1.821963,6.060204e+11,69778619.60,True
3,BTC,2024-02-15T11:27:00+0000,2.435388,2.472969,2.407792,2.443329,2.435388,2.478979,2.409225,2.478979,2.433760,2.474483,2.407596,2.451553,1333.0,71486000.0,1.833359,6.065005e+11,69781020.08,True
4,BTC,2024-02-15T11:28:00+0000,2.443329,2.474679,2.401916,2.429980,2.478979,2.478979,2.402111,2.430176,2.451553,2.451553,2.400483,2.407059,1333.0,71501000.0,1.854727,6.066033e+11,69804758.16,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,BTC,2024-02-15T14:39:00+0000,2.585360,2.596286,2.480977,2.539181,2.586980,2.599879,2.484022,2.539376,2.556858,2.586855,2.482402,2.537755,1333.0,71901000.0,2.424536,5.700044e+11,70121354.80,True
196,BTC,2024-02-15T14:40:00+0000,2.537950,2.635605,2.480843,2.525526,2.540352,2.635605,2.481038,2.574121,2.538730,2.631058,2.477994,2.535460,1333.0,71999000.0,2.564139,5.705493e+11,70190435.28,True
197,BTC,2024-02-15T14:41:00+0000,2.576654,2.576654,2.494413,2.519849,2.576849,2.583281,2.500579,2.522892,2.538187,2.546042,2.479224,2.519849,1333.0,71997000.0,2.561290,5.707965e+11,70227376.00,True
198,BTC,2024-02-15T14:42:00+0000,2.519849,2.572111,2.487348,2.487348,2.522892,2.575290,2.487348,2.487348,2.519849,2.573670,2.485730,2.485730,1333.0,71996000.0,2.559866,5.713688e+11,70241778.88,True
199,BTC,2024-02-15T14:43:00+0000,2.497404,2.628333,2.462839,2.559112,2.492796,2.644116,2.434828,2.554636,2.491177,2.623897,2.433211,2.545904,1333.0,72076000.0,2.673827,5.726724e+11,70277519.36,True

In [12]:
response.json()

{'results': [{'uuid': '342b6270-cfd9-4676-90e4-125f67e4c03c',
   'email': 'superuser@halo-soft.net',
   'username': 'superuser',
   'first_name': 'Super',
   'last_name': 'User',
   'role': 'internal',
   'is_active': True,
   'date_joined': '2023-10-04T04:18:11+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': None,
    'user': '342b6270-cfd9-4676-90e4-125f67e4c03c'},
   'favorite_assets': [],
   'socialapps': [],
   'telegram_chat_id': None,
   'trade_config_allocations': []},
  {'uuid': '2c280bd2-6289-4e24-b1ee-5b7c5786265e',
   'email': 'ceo@halo-soft.net',
   'username': '헤일로테스트',
   'first_name': 'Chang-un',
   'last_name': 'Park',
   'role': 'user',
   'is_active': True,
   'date_joined': '2023-10-20T02:23:59+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': 'https://lh3.googleusercontent.com/a/ACg8ocIerr63_JO6LcR_Y4tWhz6pDV69zj8hMuvcc2eM_4fQ=s96-c',
    'user': '2c280bd2-6289-4e24-b1ee-5b7c5786265e'},
   'favorite_assets': [],
   'socialapps': [{'id': 5,
     'provider': 'telegram',
     'name': 'arbicrypto_dev_bot',
     'client_id': 'arbicrypto_dev_bot'}],
   'telegram_chat_id': '1390695186',
   'trade_config_allocations': []},
  {'uuid': '7a2da4bc-5d0a-4423-85e3-d6e1c91dafb6',
   'email': 'staff@halo-soft.net',
   'username': 'halo-staff',
   'first_name': 'Halo',
   'last_name': 'Staff',
   'role': 'internal',
   'is_active': True,
   'date_joined': '2023-10-20T03:02:12+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': None,
    'user': '7a2da4bc-5d0a-4423-85e3-d6e1c91dafb6'},
   'favorite_assets': [],
   'socialapps': [],
   'telegram_chat_id': None,
   'trade_config_allocations': []},
  {'uuid': '8e476113-9238-4bf6-b3e4-9d80ce2d580a',
   'email': 'visitor@gizelle.com',
   'username': '@risovti794552',
   'first_name': '',
   'last_name': '',
   'role': 'visitor',
   'is_active': True,
   'date_joined': '2023-10-24T04:33:20+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': None,
    'user': '8e476113-9238-4bf6-b3e4-9d80ce2d580a'},
   'favorite_assets': [],
   'socialapps': [],
   'telegram_chat_id': None,
   'trade_config_allocations': []},
  {'uuid': '47fcb148-ab2b-4db6-a54b-76e517042a1b',
   'email': 'user@gizelle.com',
   'username': 'user-gizelle',
   'first_name': 'User',
   'last_name': '',
   'role': 'user',
   'is_active': True,
   'date_joined': '2023-10-24T04:33:34+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': None,
    'user': '47fcb148-ab2b-4db6-a54b-76e517042a1b'},
   'favorite_assets': [],
   'socialapps': [],
   'telegram_chat_id': None,
   'trade_config_allocations': []},
  {'uuid': '11724593-caed-49b8-ba1f-99c74589db7e',
   'email': 'ernestine@halo-soft.net',
   'username': '엔타인',
   'first_name': 'Ernestine',
   'last_name': 'Lariosa',
   'role': 'user',
   'is_active': True,
   'date_joined': '2023-12-11T10:36:25+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': 'https://lh3.googleusercontent.com/a/ACg8ocJrC3EaInb-dvf231jOfdmTHV9DaZ95S7LKPhYcNayl=s96-c',
    'user': '11724593-caed-49b8-ba1f-99c74589db7e'},
   'favorite_assets': [{'id': 81,
     'base_asset': 'BTC',
     'market_codes': ['OKX_USD_M/USDT', 'OKX_COIN_M/USD'],
     'user': '11724593-caed-49b8-ba1f-99c74589db7e'},
    {'id': 85,
     'base_asset': 'BTC',
     'market_codes': ['BITHUMB_SPOT/KRW', 'BINANCE_COIN_M/USD'],
     'user': '11724593-caed-49b8-ba1f-99c74589db7e'},
    {'id': 89,
     'base_asset': 'ETH',
     'market_codes': ['BITHUMB_SPOT/KRW', 'BINANCE_COIN_M/USD'],
     'user': '11724593-caed-49b8-ba1f-99c74589db7e'}],
   'socialapps': [{'id': 5,
     'provider': 'telegram',
     'name': 'arbicrypto_dev_bot',
     'client_id': 'arbicrypto_dev_bot'}],
   'telegram_chat_id': '1731633310',
   'trade_config_allocations': [{'target_market_code': 'BITHUMB_SPOT/KRW',
     'origin_market_code': 'BINANCE_COIN_M/USD',
     'trade_config_uuid': '5c34c21b-cac2-4e97-af43-c7ef570a30bb'}]},
  {'uuid': '87c2c8da-ad4d-47d5-adbd-7aec629000dc',
   'email': 'gizelle@halo-soft.net',
   'username': 'gizelle',
   'first_name': 'Gizelle',
   'last_name': 'Peras',
   'role': 'user',
   'is_active': True,
   'date_joined': '2023-12-18T11:01:33+0000',
   'profile': {'referral': None,
    'level': 1,
    'points': 0,
    'picture': 'https://lh3.googleusercontent.com/a/ACg8ocJExaHg-K2kWTxGYfOWaL3GEoMUIkJCY9znT02g3pic=s96-c',
    'user': '87c2c8da-ad4d-47d5-adbd-7aec629000dc'},
   'favorite_assets': [{'id': 82,
     'base_asset': 'BTC',
     'market_codes': ['BITHUMB_SPOT/KRW', 'BINANCE_USD_M/USDT'],
     'user': '87c2c8da-ad4d-47d5-adbd-7aec629000dc'},
    {'id': 83,
     'base_asset': 'XRP',
     'market_codes': ['BITHUMB_SPOT/KRW', 'BINANCE_USD_M/USDT'],
     'user': '87c2c8da-ad4d-47d5-adbd-7aec629000dc'},
    {'id': 84,
     'base_asset': 'USDC',
     'market_codes': ['BITHUMB_SPOT/KRW', 'BINANCE_USD_M/USDT'],
     'user': '87c2c8da-ad4d-47d5-adbd-7aec629000dc'}],
   'socialapps': [{'id': 5,
     'provider': 'telegram',
     'name': 'arbicrypto_dev_bot',
     'client_id': 'arbicrypto_dev_bot'}],
   'telegram_chat_id': '1722781031',
   'trade_config_allocations': [{'target_market_code': 'UPBIT_SPOT/KRW',
     'origin_market_code': 'BINANCE_USD_M/USDT',
     'trade_config_uuid': '00dc872d-b31d-412d-94e5-9de9026f4a48'}]}]}

In [17]:
acw_api.get_node()

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,id,name,url,description,max_user_count,market_code_services
0,1,trade_core_dev,http://221.148.128.205:20081,changun's test tradecore server,300,"[UPBIT_SPOT/KRW:BINANCE_USD_M/USDT, BITHUMB_SP..."

In [34]:
node = 'trade_core_dev'

all_node_df = acw_api.get_node()
node_df = all_node_df[all_node_df['name']==node]
if len(node_df) != 1:
    raise Exception(f"Node not found or not unique, len(node_df)={len(node_df)}")
node_df['market_code_services'].values[0]

/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'acw-dev.orbitholdings.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

['UPBIT_SPOT/KRW:BINANCE_USD_M/USDT', 'BITHUMB_SPOT/KRW:BINANCE_SPOT/USDT']