In [1]:
import pandas as pd
import datetime
import time

from snatcher import InitSnatcher

[WARNING] upbit-client is currently a newer version: 1.3.2.0
Please update to the latest version using the pip command:`pip install --upgrade upbit-client`

In [3]:
sys.path.append("/home/coin_trading_bot/kimp_bot_core")
from telegram_bot_plugin.telegram_bot import InitTelegramBot
# Initiating kimp_bot_core
from kimp_bot_core import InitKimpCore
kimp_core = InitKimpCore(node='test', proc_n=1)

TypeError: __init__() missing 1 required positional argument: 'node'

In [3]:
local_db_dict = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',
    'passwd': '13245dh',
    'database': 'test_coin_trade'
}

bot_token = "5556345865:AAFJy8wdyTjKxDBOb89bTRFsNs6UFMn4twY"
api_url = "http://222.106.173.213:22180/api/master_v1/monitorbot/"

logging_dir = "/home/coin_trading_bot/kimp_bot_core/trigger_engine/"

test_bot = InitTelegramBot("1334132077:AAE7Pvj0bu4sHGKWlH6VsZFsSkcwPrwxB6I", logging_dir)
test_snatcher = InitSnatcher(logging_dir, "13245dh!!", local_db_dict, local_db_dict, kimp_core.get_kimp_df, kimp_core.update_dollar_return_dict, bot_token, api_url, 'kimp_bot_core', test_bot)

2022-09-13 17:43:24,458 - snatcher - INFO - Local Mariadb client has been connected to localhost - test_coin_trade.
[INFO] Local Mariadb client has been connected to localhost - test_coin_trade.
2022-09-13 17:43:24,461 - snatcher - INFO - Remote Mariadb client has been connected to localhost - test_coin_trade.
[INFO] Remote Mariadb client has been connected to localhost - test_coin_trade.
2022-09-13 17:43:24,483 - snatcher - INFO - start_monitor_load_userinfo|start_monitor_load_userinfo started.
[INFO] start_monitor_load_userinfo|start_monitor_load_userinfo started.
2022-09-13 17:43:24,485 - snatcher - INFO - start_monitor_load_user_api_key|start_monitor_load_user_api_key started.
[INFO] start_monitor_load_user_api_key|start_monitor_load_user_api_key started.
2022-09-13 17:43:24,489 - snatcher - INFO - start_monitor_load_trade_history|start_monitor_load_trade_history started.
[INFO] start_monitor_load_trade_history|start_monitor_load_trade_history started.
2022-09-13 17:43:24,506 - snatcher - INFO - start_monitor_load_addcoin|start_monitor_load_addcoin started.
[INFO] start_monitor_load_addcoin|start_monitor_load_addcoin started.
2022-09-13 17:43:24,514 - snatcher - INFO - start_monitor_load_addcir|start_monitor_load_addcir started.
[INFO] start_monitor_load_addcir|start_monitor_load_addcir started.

In [4]:
test_snatcher.start_monitor_high_low_loop()

2022-09-13 17:43:24,704 - snatcher - INFO - start_monitor_high_low_loop|start_monitor_high_low_loop started.
[INFO] start_monitor_high_low_loop|start_monitor_high_low_loop started.

In [5]:
test_snatcher.addcoin_df

,user_id,datetime,last_updated_timestamp,redis_uuid,symbol,addcoin_uuid,high,low,rolling_window,switch,auto_trade_switch,auto_trade_capital,enter_upbit_uuid,enter_binance_orderId,exit_upbit_uuid,exit_binance_orderId,remark
0,1390695186,2022-09-13 03:18:42,16630391222922690,67fd7c4a-bd76-414a-a41e-dbd4a3ee70af,XRPUSDT,None,1500.0,1400.0,None,0,None,None,None,None,None,None,None
1,1390695186,2022-09-13 03:18:42,16630391222964840,61e3f24c-97af-41f8-9501-908acfcba38d,BTC,None,15.0,14.0,None,0,None,None,None,None,None,None,None

In [8]:
upbit_access_key = test_snatcher.user_api_key_df.iloc[1, -3]
upbit_secret_key = test_snatcher.user_api_key_df.iloc[1, -2]
binance_access_key = test_snatcher.user_api_key_df.iloc[0,-3]
binance_secret_key = test_snatcher.user_api_key_df.iloc[0,-2]

In [6]:
test_snatcher.addcoin_df

,user_id,datetime,last_updated_timestamp,redis_uuid,symbol,addcoin_uuid,high,low,rolling_window,switch,auto_trade_switch,auto_trade_capital,enter_upbit_uuid,enter_binance_orderId,exit_upbit_uuid,exit_binance_orderId,remark
0,1390695186,2022-09-13 03:18:42,16630391222922690,67fd7c4a-bd76-414a-a41e-dbd4a3ee70af,XRPUSDT,None,1500,1400,None,0.0,None,None,None,None,None,None,None
1,1390695186,2022-09-13 03:18:42,16630391222964840,61e3f24c-97af-41f8-9501-908acfcba38d,BTC,None,15,14,None,0.0,None,None,None,None,None,None,None
2,1390695186,2022-09-13 06:38:56,16630511366825690,ba628998-278d-4a49-979d-8b48b8f24dab,XRP,None,7,6,None,0,0.0,10000.0,None,None,None,None,None

# Manipulate DB

In [5]:
import sys
sys.path.append("/home/kimp_bot_core")
from etc.db_handler.create_schema_tables import InitDBClient
import uuid
import pandas as pd

local_db_dict = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',
    'passwd': '13245dh',
    'database': 'test_coin_trade'
}
remote_db_dict = {
    "host":"222.106.173.216",
    "port":22153,
    "user":"root",
    "passwd":"13245dh!!",
    "database": "kp_trade_v2_dev"
}

In [6]:
test_client = InitDBClient(**remote_db_dict)

In [9]:
test_client.conn.close()

In [ ]:
# Add user for test
test_client = InitDBClient(**local_db_dict)

sql = """
INSERT INTO user_info
(user_id, register_origin, datetime_end, user_name, binance_leverage, binance_cross, binance_margin_call, safe_reverse, alarm_num, alarm_period, on_off)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
# my id = 1390695186
val = [99999, 'kimp_bot1', datetime.datetime.now()+datetime.timedelta(days=365),
    'test1',
    1,
    False,
    False,
    False,
    1,
    1,
    True
]

test_client.curr.execute(sql, val)
test_client.conn.commit()
# test_client.conn.close()

In [6]:
# # Add addcoin for test

test_client = InitDBClient(**local_db_dict)
sql = """
INSERT INTO addcoin
(
    user_id,
    last_updated_timestamp,
    redis_uuid,
    symbol,
    addcoin_uuid,
    high,
    low,
    switch,
    auto_trade_switch,
    auto_trade_capital
    )

VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

val = [
    1390695186,
    datetime.datetime.now().timestamp()*10000000,
    str(uuid.uuid4()),
    'XRP',
    None,
    7,
    6,
    None,
    0, # auto_trade_switch
    10000 # auto_trade_capital
]

test_client.curr.execute(sql, val)
test_client.conn.commit()
test_client.conn.close()

:

In [ ]:
# # Add addcir for test

test_client = InitDBClient(**local_db_dict)
sql = """
INSERT INTO addcir
(
    user_id,
    last_updated_timestamp,
    redis_uuid,
    symbol,
    pauto_num,
    cir_trade_capital,
    cir_trade_num
    )

VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

val = [
    1390695186,
    datetime.datetime.now().timestamp()*10000000,
    str(uuid.uuid4()),
    'BTC',
    2,
    100000,
    0
]

test_client.curr.execute(sql, val)
test_client.conn.commit()
test_client.conn.close()

In [ ]:
# INSERT api_key
test_client = InitDBClient(**local_db_dict)
encryption_key = "13245dh!!"

sql = """
INSERT INTO user_api_key
(user_id, exchange, access_key, secret_key)
VALUES (%s, %s, HEX(AES_ENCRYPT(%s, SHA2('{encryption_key}', 256))), HEX(AES_ENCRYPT(%s, SHA2('{encryption_key}', 256))))
""".format(encryption_key=encryption_key)

val = [1390695186, 'UPBIT', '', '']

test_client.curr.execute(sql, val)
test_client.conn.commit()
test_client.conn.close()

In [5]:
# Descryption
test_client = InitDBClient(**local_db_dict)
encryption_key = "13245dh!!"
sql = """
SELECT id, datetime, user_id, webuser_id, email, exchange,
CONVERT(AES_DECRYPT(UNHEX(access_key), SHA2('{encryption_key}', 256)) USING UTF8) as access_key,
CONVERT(AES_DECRYPT(UNHEX(secret_key), SHA2('{encryption_key}', 256)) USING UTF8) as secret_key,
remark
FROM user_api_key
""".format(encryption_key=encryption_key)

test_client.curr.execute(sql)
test_client.conn.close()
temp = pd.DataFrame(test_client.curr.fetchall())
temp

,id,datetime,user_id,webuser_id,email,exchange,access_key,secret_key,remark
0,3,2022-09-13 06:22:12,1390695186,None,None,BINANCE,prMohuJWkl5e2wfqZscWPf4FPRV9Qd7vk3zuCqt1uKKKBa...,IIBEDf2WIWB1bbIUojCDqJtF9FUjbHmPTihoSQZwIYeuG5...,None
1,4,2022-09-13 06:22:21,1390695186,None,None,UPBIT,CWCjt48ewf6T9nBxHg1zmBxxCQMUNHzgrxTCMt8F,xK0RVf3FNjxpygpLjbd1iwTlSAVZXwgWnIG1Ivzx,None

In [15]:
test_client = InitDBClient(**local_db_dict)
sql = """SELECT * FROM user_api_key WHERE access_key=HEX(AES_ENCRYPT(%s, SHA2('{encryption_key}', 256)))""".format(encryption_key=encryption_key)
val = 'CWCjt48ewf6T9nBxHg1zmBxxCQMUNHzgrxTCMt8F'
test_client.curr.execute(sql, val)
fetched = test_client.curr.fetchall()
test_client.conn.close()