In [1]:
from common_info import InitCommonInfo
import os
import sys
import json

sys.path.append("/home/coin_trading_bot/kimp_bot_core")
from price_websocket.price_websocket import extract_shared_listed_symbols
from etc.register_msg import register

[WARNING] upbit-client is currently a newer version: 1.3.2.0
Please update to the latest version using the pip command:`pip install --upgrade upbit-client`

In [2]:
from okx_plug import InitOkxAdaptor
from upbit_plug import InitUpbitAdaptor
from binance_plug import InitBinanceAdaptor
import pandas as pd

In [29]:
upbit_adaptor = InitUpbitAdaptor()

2023-08-28 11:54:00,063 - upbit_plug - INFO - upbit_plug_logger started.
[INFO] upbit_plug_logger started.

In [34]:
temp = upbit_adaptor.upbit_all_ticker(None, None)
temp.head()

,market,trade_date,trade_time,trade_date_kst,trade_time_kst,trade_timestamp,opening_price,high_price,low_price,trade_price,...,trade_volume,acc_trade_price,acc_trade_price_24h,acc_trade_volume,acc_trade_volume_24h,highest_52_week_price,highest_52_week_date,lowest_52_week_price,lowest_52_week_date,timestamp
0,KRW-BTC,20230828,025503,20230828,115503,1693191303386,35400000.0,35410000.0,35232000.0,35326000.0,...,0.002946,1.123428e+10,3.705502e+10,3.182082e+02,1.046916e+03,41569000.0,2023-06-30,20700000.0,2022-12-30,1693191303414
1,KRW-ETH,20230828,025507,20230828,115507,1693191307578,2247000.0,2251000.0,2231000.0,2236000.0,...,0.015000,3.186369e+09,1.073389e+10,1.423805e+03,4.785606e+03,2795000.0,2023-04-16,1500000.0,2022-12-30,1693191307588
2,KRW-NEO,20230828,025424,20230828,115424,1693191264226,9815.0,9835.0,9650.0,9655.0,...,1.940870,3.562600e+08,4.391321e+09,3.664257e+04,4.457405e+05,20420.0,2023-02-21,7535.0,2022-12-30,1693191300101
3,KRW-MTL,20230828,025507,20230828,115507,1693191307462,1535.0,1570.0,1510.0,1515.0,...,1359.000000,2.437135e+09,3.495345e+09,1.579554e+06,2.271956e+06,3200.0,2023-02-20,800.0,2022-12-17,1693191307492
4,KRW-XRP,20230828,025456,20230828,115456,1693191296920,711.0,711.0,702.0,705.0,...,7.838983,1.205026e+10,5.667909e+10,1.708692e+07,7.957311e+07,1125.0,2023-07-13,408.0,2023-01-02,1693191300110

In [35]:
temp.columns

Index(['market', 'trade_date', 'trade_time', 'trade_date_kst',
       'trade_time_kst', 'trade_timestamp', 'opening_price', 'high_price',
       'low_price', 'trade_price', 'prev_closing_price', 'change',
       'change_price', 'change_rate', 'signed_change_price',
       'signed_change_rate', 'trade_volume', 'acc_trade_price',
       'acc_trade_price_24h', 'acc_trade_volume', 'acc_trade_volume_24h',
       'highest_52_week_price', 'highest_52_week_date', 'lowest_52_week_price',
       'lowest_52_week_date', 'timestamp'],
      dtype='object')

In [4]:
binance_adaptor = InitBinanceAdaptor(None, None)

2023-08-28 11:39:29,923 - binance_plug - INFO - binance_plug_logger started.
[INFO] binance_plug_logger started.

In [15]:
temp = pd.DataFrame(binance_adaptor.pub_bi_client.get_ticker())
temp.head()

,symbol,priceChange,priceChangePercent,weightedAvgPrice,prevClosePrice,lastPrice,lastQty,bidPrice,bidQty,askPrice,...,openPrice,highPrice,lowPrice,volume,quoteVolume,openTime,closeTime,firstId,lastId,count
0,ETHBTC,0.00003000,0.047,0.06339383,0.06335000,0.06338000,5.09290000,0.06337000,56.74870000,0.06338000,...,0.06335000,0.06356000,0.06326000,6257.94100000,396.71481711,1693104333639,1693190733639,422436628,422449914,13287
1,LTCBTC,-0.00000900,-0.360,0.00250055,0.00249700,0.00248900,0.09400000,0.00248800,276.65500000,0.00248900,...,0.00249800,0.00252000,0.00247600,19969.95700000,49.93584685,1693104334348,1693190734348,93298850,93304650,5801
2,BNBBTC,0.00004300,0.517,0.00835129,0.00831900,0.00836300,3.01800000,0.00836300,3.90100000,0.00836400,...,0.00832000,0.00839900,0.00829800,15673.10000000,130.89064885,1693104335413,1693190735413,226530624,226552610,21987
3,NEOBTC,-0.00000330,-1.191,0.00027669,0.00027700,0.00027380,82.59000000,0.00027370,11.66000000,0.00027380,...,0.00027710,0.00028280,0.00027300,50525.32000000,13.97964458,1693104320084,1693190720084,45446333,45451323,4991
4,QTUMETH,-0.00001700,-1.300,0.00130531,0.00131400,0.00129100,29.50000000,0.00129300,46.80000000,0.00129700,...,0.00130800,0.00131100,0.00129100,981.90000000,1.28168160,1693104321167,1693190721167,5400804,5400841,38

In [19]:
temp = binance_adaptor.pub_bi_client.get_exchange_info()
temp

{'timezone': 'UTC',
 'serverTime': 1693190840226,
 'rateLimits': [{'rateLimitType': 'REQUEST_WEIGHT',
   'interval': 'MINUTE',
   'intervalNum': 1,
   'limit': 6000},
  {'rateLimitType': 'ORDERS',
   'interval': 'SECOND',
   'intervalNum': 10,
   'limit': 50},
  {'rateLimitType': 'ORDERS',
   'interval': 'DAY',
   'intervalNum': 1,
   'limit': 160000},
  {'rateLimitType': 'RAW_REQUESTS',
   'interval': 'MINUTE',
   'intervalNum': 5,
   'limit': 61000}],
 'exchangeFilters': [],
 'symbols': [{'symbol': 'ETHBTC',
   'status': 'TRADING',
   'baseAsset': 'ETH',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': True,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00001000',
     'maxPrice': '922327.00000000',
     'tickSize': '0.00001000'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.00010000',
     'maxQty': '100000.00000000',
     'stepSize': '0.00010000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '5904.46394291',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00010000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'MARGIN',
    'TRD_GRP_004',
    'TRD_GRP_005',
    'TRD_GRP_006',
    'TRD_GRP_008',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'LTCBTC',
   'status': 'TRADING',
   'baseAsset': 'LTC',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': True,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000100',
     'maxPrice': '100000.00000000',
     'tickSize': '0.00000100'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.00100000',
     'maxQty': '100000.00000000',
     'stepSize': '0.00100000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '6468.50886666',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00010000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'MARGIN',
    'TRD_GRP_004',
    'TRD_GRP_005',
    'TRD_GRP_006',
    'TRD_GRP_008',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'BNBBTC',
   'status': 'TRADING',
   'baseAsset': 'BNB',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': True,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000100',
     'maxPrice': '100000.00000000',
     'tickSize': '0.00000100'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.00100000',
     'maxQty': '100000.00000000',
     'stepSize': '0.00100000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '3134.42901666',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00010000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'MARGIN',
    'TRD_GRP_004',
    'TRD_GRP_005',
    'TRD_GRP_006',
    'TRD_GRP_008',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'NEOBTC',
   'status': 'TRADING',
   'baseAsset': 'NEO',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': True,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000010',
     'maxPrice': '100000.00000000',
     'tickSize': '0.00000010'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.01000000',
     'maxQty': '100000.00000000',
     'stepSize': '0.01000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '6669.07154166',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00010000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'MARGIN',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'QTUMETH',
   'status': 'TRADING',
   'baseAsset': 'QTUM',
   'baseAssetPrecision': 8,
   'quoteAsset': 'ETH',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': False,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000100',
     'maxPrice': '1000.00000000',
     'tickSize': '0.00000100'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.10000000',
     'maxQty': '90000000.00000000',
     'stepSize': '0.10000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '2708.24875000',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00500000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'TRD_GRP_008',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'EOSETH',
   'status': 'TRADING',
   'baseAsset': 'EOS',
   'baseAssetPrecision': 8,
   'quoteAsset': 'ETH',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': True,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000010',
     'maxPrice': '1000.00000000',
     'tickSize': '0.00000010'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.10000000',
     'maxQty': '92141578.00000000',
     'stepSize': '0.10000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '10803.77250000',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00500000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'MARGIN',
    'TRD_GRP_006',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'SNTETH',
   'status': 'TRADING',
   'baseAsset': 'SNT',
   'baseAssetPrecision': 8,
   'quoteAsset': 'ETH',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': False,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000001',
     'maxPrice': '1000.00000000',
     'tickSize': '0.00000001'},
    {'filterType': 'LOT_SIZE',
     'minQty': '1.00000000',
     'maxQty': '90000000.00000000',
     'stepSize': '1.00000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '3609500.80833333',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00500000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'TRD_GRP_005',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'BNTETH',
   'status': 'TRADING',
   'baseAsset': 'BNT',
   'baseAssetPrecision': 8,
   'quoteAsset': 'ETH',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': False,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000010',
     'maxPrice': '1000.00000000',
     'tickSize': '0.00000010'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.10000000',
     'maxQty': '92141578.00000000',
     'stepSize': '0.10000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '25102.80500000',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00500000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'TRD_GRP_005',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'BCCBTC',
   'status': 'BREAK',
   'baseAsset': 'BCC',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': False,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000100',
     'maxPrice': '1000.00000000',
     'tickSize': '0.00000100'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.00100000',
     'maxQty': '92141578.00000000',
     'stepSize': '0.00100000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,
     'maxTrailingBelowDelta': 2000},
    {'filterType': 'PERCENT_PRICE_BY_SIDE',
     'bidMultiplierUp': '5',
     'bidMultiplierDown': '0.2',
     'askMultiplierUp': '5',
     'askMultiplierDown': '0.2',
     'avgPriceMins': 5},
    {'filterType': 'NOTIONAL',
     'minNotional': '0.00010000',
     'applyMinToMarket': True,
     'maxNotional': '9000000.00000000',
     'applyMaxToMarket': False,
     'avgPriceMins': 5},
    {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200},
    {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}],
   'permissions': ['SPOT',
    'TRD_GRP_009',
    'TRD_GRP_010',
    'TRD_GRP_011',
    'TRD_GRP_012',
    'TRD_GRP_013',
    'TRD_GRP_014'],
   'defaultSelfTradePreventionMode': 'NONE',
   'allowedSelfTradePreventionModes': ['NONE',
    'EXPIRE_TAKER',
    'EXPIRE_MAKER',
    'EXPIRE_BOTH']},
  {'symbol': 'GASBTC',
   'status': 'TRADING',
   'baseAsset': 'GAS',
   'baseAssetPrecision': 8,
   'quoteAsset': 'BTC',
   'quotePrecision': 8,
   'quoteAssetPrecision': 8,
   'baseCommissionPrecision': 8,
   'quoteCommissionPrecision': 8,
   'orderTypes': ['LIMIT',
    'LIMIT_MAKER',
    'MARKET',
    'STOP_LOSS_LIMIT',
    'TAKE_PROFIT_LIMIT'],
   'icebergAllowed': True,
   'ocoAllowed': True,
   'quoteOrderQtyMarketAllowed': True,
   'allowTrailingStop': True,
   'cancelReplaceAllowed': True,
   'isSpotTradingAllowed': True,
   'isMarginTradingAllowed': False,
   'filters': [{'filterType': 'PRICE_FILTER',
     'minPrice': '0.00000010',
     'maxPrice': '1000.00000000',
     'tickSize': '0.00000010'},
    {'filterType': 'LOT_SIZE',
     'minQty': '0.10000000',
     'maxQty': '90000000.00000000',
     'stepSize': '0.10000000'},
    {'filterType': 'ICEBERG_PARTS', 'limit': 10},
    {'filterType': 'MARKET_LOT_SIZE',
     'minQty': '0.00000000',
     'maxQty': '8582.44291666',
     'stepSize': '0.00000000'},
    {'filterType': 'TRAILING_DELTA',
     'minTrailingAboveDelta': 10,
     'maxTrailingAboveDelta': 2000,
     'minTrailingBelowDelta': 10,

In [22]:
pd.DataFrame(temp['symbols'])

,symbol,status,baseAsset,baseAssetPrecision,quoteAsset,quotePrecision,quoteAssetPrecision,baseCommissionPrecision,quoteCommissionPrecision,orderTypes,...,ocoAllowed,quoteOrderQtyMarketAllowed,allowTrailingStop,cancelReplaceAllowed,isSpotTradingAllowed,isMarginTradingAllowed,filters,permissions,defaultSelfTradePreventionMode,allowedSelfTradePreventionModes
0,ETHBTC,TRADING,ETH,8,BTC,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,True,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, MARGIN, TRD_GRP_004, TRD_GRP_005, TRD_G...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
1,LTCBTC,TRADING,LTC,8,BTC,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,True,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, MARGIN, TRD_GRP_004, TRD_GRP_005, TRD_G...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
2,BNBBTC,TRADING,BNB,8,BTC,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,True,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, MARGIN, TRD_GRP_004, TRD_GRP_005, TRD_G...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
3,NEOBTC,TRADING,NEO,8,BTC,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,True,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, MARGIN, TRD_GRP_009, TRD_GRP_010, TRD_G...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
4,QTUMETH,TRADING,QTUM,8,ETH,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,False,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, TRD_GRP_008, TRD_GRP_009, TRD_GRP_010, ...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,CYBERUSDT,TRADING,CYBER,8,USDT,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,True,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, MARGIN, TRD_GRP_005, TRD_GRP_009, TRD_G...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
2283,CYBERTUSD,TRADING,CYBER,8,TUSD,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,False,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, TRD_GRP_005, TRD_GRP_009, TRD_GRP_010, ...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
2284,SEITUSD,TRADING,SEI,8,TUSD,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,False,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, TRD_GRP_005, TRD_GRP_009, TRD_GRP_010, ...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
2285,LPTTRY,TRADING,LPT,8,TRY,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,False,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, ...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"
2286,UNITRY,TRADING,UNI,8,TRY,8,8,8,8,"[LIMIT, LIMIT_MAKER, MARKET, STOP_LOSS_LIMIT, ...",...,True,True,True,True,True,False,"[{'filterType': 'PRICE_FILTER', 'minPrice': '0...","[SPOT, TRD_GRP_009, TRD_GRP_010, TRD_GRP_011, ...",NONE,"[NONE, EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH]"

In [23]:
temp = binance_adaptor.pub_bi_client.futures_coin_exchange_info()

In [28]:
pd.DataFrame(temp['symbols'])

,symbol,pair,contractType,deliveryDate,onboardDate,contractStatus,contractSize,marginAsset,maintMarginPercent,requiredMarginPercent,...,equalQtyPrecision,maxMoveOrderLimit,triggerProtect,underlyingType,underlyingSubType,filters,orderTypes,timeInForce,liquidationFee,marketTakeBound
0,BTCUSD_PERP,BTCUSD,PERPETUAL,4133404800000,1597042800000,TRADING,100,BTC,2.5000,5.0000,...,4,10000,0.0500,COIN,[PoW],"[{'minPrice': '1000', 'maxPrice': '4520958', '...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.015000,0.05
1,BTCUSD_230929,BTCUSD,CURRENT_QUARTER,1695974400000,1680249600000,TRADING,100,BTC,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '1000', 'maxPrice': '4671848', '...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
2,BTCUSD_231229,BTCUSD,NEXT_QUARTER,1703836800000,1688112000000,TRADING,100,BTC,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '1000', 'maxPrice': '4671848', '...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
3,ETHUSD_PERP,ETHUSD,PERPETUAL,4133404800000,1597734000000,TRADING,10,ETH,2.5000,5.0000,...,4,10000,0.0500,COIN,[Layer-1],"[{'minPrice': '50', 'maxPrice': '306159', 'fil...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.015000,0.05
4,ETHUSD_230929,ETHUSD,CURRENT_QUARTER,1695974400000,1680249600000,TRADING,10,ETH,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '50', 'maxPrice': '316265', 'fil...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,BCHUSD_231229,BCHUSD,NEXT_QUARTER,1703836800000,1688112000000,TRADING,10,BCH,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '14.40', 'maxPrice': '66208', 'f...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
58,DOTUSD_231229,DOTUSD,NEXT_QUARTER,1703836800000,1688112000000,TRADING,10,DOT,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '0.400', 'maxPrice': '3000', 'fi...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
59,XRPUSD_231229,XRPUSD,NEXT_QUARTER,1703836800000,1688112000000,TRADING,10,XRP,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '0.0150', 'maxPrice': '115', 'fi...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
60,LTCUSD_231229,LTCUSD,NEXT_QUARTER,1703836800000,1688112000000,TRADING,10,LTC,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '3.80', 'maxPrice': '17562', 'fi...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05
61,BNBUSD_231229,BNBUSD,NEXT_QUARTER,1703836800000,1688112000000,TRADING,10,BNB,2.5000,5.0000,...,4,10000,0.0500,COIN,[],"[{'minPrice': '7', 'maxPrice': '41461', 'filte...","[LIMIT, MARKET, STOP, STOP_MARKET, TAKE_PROFIT...","[GTC, IOC, FOK, GTX]",0.010000,0.05

In [2]:
okx_client = InitOkxAdaptor("fcb66a6e-0443-4743-8d9b-61caf7eab662", "0029E09874B38F5AC7E68E9DFC348667")
upbit_client = InitUpbitAdaptor()

2023-06-03 15:56:41,067 - okx_plug - INFO - okx_plug_logger started.
[INFO] okx_plug_logger started.
2023-06-03 15:56:41,481 - upbit_plug - INFO - upbit_plug_logger started.
[INFO] upbit_plug_logger started.

In [3]:
okx_all_tickers = pd.DataFrame(okx_client.pub_okx_client.MarketAPI.get_tickers('SWAP')['data'])
okx_all_tickers[okx_all_tickers['instId'].str.contains('ARB')]

,instType,instId,last,lastSz,askPx,askSz,bidPx,bidSz,open24h,high24h,low24h,volCcy24h,vol24h,ts,sodUtc0,sodUtc8
53,SWAP,ARB-USDT-SWAP,1.2377,18,1.2382,350,1.2381,210,1.1997,1.2588,1.188,132336980,13228215,1685775403009,1.2408,1.2469

In [4]:
okx_all_tickers

,instType,instId,last,lastSz,askPx,askSz,bidPx,bidSz,open24h,high24h,low24h,volCcy24h,vol24h,ts,sodUtc0,sodUtc8
0,SWAP,ETC-USDT-SWAP,18.153,2,18.153,9,18.152,1,18.004,18.192,17.93,591050,58854,1685775402709,18.148,18.071
1,SWAP,CETUS-USDT-SWAP,0.05793,170,0.05794,3,0.05792,200,0.05583,0.06037,0.05547,129868510,12974905,1685775401606,0.05834,0.05685
2,SWAP,CRV-USDT-SWAP,0.8544,307,0.8545,2171,0.8543,1779,0.828,0.8596,0.8234,20655901,20642286,1685775402112,0.8533,0.8478
3,SWAP,SUSHI-USDT-SWAP,0.855,3,0.855,8637,0.854,39132,0.847,0.859,0.841,5579320,5577882,1685775402912,0.855,0.851
4,SWAP,XLM-USDT-SWAP,0.09297,1,0.09298,96,0.09297,84,0.09213,0.093,0.09148,17157100,170815,1685775398306,0.09199,0.09201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,SWAP,ANT-USDT-SWAP,3.524,16,3.524,301,3.523,543,3.575,3.611,3.504,1401026,1399397,1685775402509,3.561,3.582
163,SWAP,MAGIC-USDT-SWAP,1.05,175,1.0504,369,1.0502,143,0.9851,1.0775,0.9779,14255594,14247457,1685775401506,1.0585,0.9917
164,SWAP,ORDI-USDT-SWAP,8.442,9,8.443,47660,8.442,710,8.843,8.882,8.202,8357718.5,83459904,1685775399912,8.529,8.64
165,SWAP,XMR-USDT-SWAP,146.99,1,147,63,146.99,46,145.98,147.49,145.26,21791.1,217686,1685775401010,146.05,145.6
166,SWAP,AXS-USDT-SWAP,7.17,1,7.17,6804,7.16,65747,7.05,7.18,6.98,1167439.6,11664862,1685775402313,7.13,7.05

In [5]:
okx_all_tickers = pd.DataFrame(okx_client.pub_okx_client.MarketAPI.get_tickers('SWAP')['data'])
okx_all_tickers = okx_all_tickers[okx_all_tickers['instId'].str.endswith('-USDT-SWAP')]
okx_all_tickers.loc[:, ['last', 'volCcy24h', 'vol24h']] = okx_all_tickers.loc[:, ['last', 'volCcy24h', 'vol24h']].astype(float)
okx_all_tickers['24h_turnover'] = okx_all_tickers['volCcy24h'] * okx_all_tickers['last']
okx_all_tickers = okx_all_tickers.sort_values('24h_turnover', ascending=False).reset_index(drop=True)[['instId','last','24h_turnover']]

okx_all_tickers['symbol'] = okx_all_tickers['instId'].apply(lambda x: x.split('-')[0])
upbit_ticker_df = upbit_client.upbit_all_ticker(None, None)
upbit_ticker_df['symbol'] = upbit_ticker_df['market'].apply(lambda x: x.split('-')[1])
both_listed_symbol_df = pd.merge(okx_all_tickers, upbit_ticker_df, on='symbol', how='inner')
both_listed_okx_symbols = both_listed_symbol_df.sort_values('24h_turnover', ascending=False)['instId'].tolist()
both_listed_upbit_symbols = both_listed_symbol_df.sort_values('acc_trade_price_24h', ascending=False)['market'].tolist()

In [7]:
both_listed_upbit_symbols

['KRW-JST',
 'KRW-XRP',
 'KRW-BTC',
 'KRW-NEO',
 'KRW-MASK',
 'KRW-SUI',
 'KRW-TRX',
 'KRW-SAND',
 'KRW-CELO',
 'KRW-ETH',
 'KRW-ARB',
 'KRW-APT',
 'KRW-AXS',
 'KRW-BSV',
 'KRW-GRT',
 'KRW-DOGE',
 'KRW-1INCH',
 'KRW-SOL',
 'KRW-STX',
 'KRW-ETC',
 'KRW-GMT',
 'KRW-ONT',
 'KRW-WAVES',
 'KRW-EOS',
 'KRW-ADA',
 'KRW-MANA',
 'KRW-MATIC',
 'KRW-ALGO',
 'KRW-IOTA',
 'KRW-ATOM',
 'KRW-ZRX',
 'KRW-ZIL',
 'KRW-XLM',
 'KRW-QTUM',
 'KRW-STORJ',
 'KRW-CHZ',
 'KRW-DOT',
 'KRW-NEAR',
 'KRW-EGLD',
 'KRW-ENJ',
 'KRW-SHIB',
 'KRW-LINK',
 'KRW-BCH',
 'KRW-AVAX',
 'KRW-KNC',
 'KRW-CRO',
 'KRW-THETA',
 'KRW-TON',
 'KRW-AAVE',
 'KRW-IOST',
 'KRW-CVC',
 'KRW-BAT',
 'KRW-XTZ']

In [23]:
upbit_ticker_df.head()

,market,trade_date,trade_time,trade_date_kst,trade_time_kst,trade_timestamp,opening_price,high_price,low_price,trade_price,...,acc_trade_price,acc_trade_price_24h,acc_trade_volume,acc_trade_volume_24h,highest_52_week_price,highest_52_week_date,lowest_52_week_price,lowest_52_week_date,timestamp,symbol
0,KRW-BTC,20230603,061520,20230603,151520,1685772920636,36089000.0,36099000.0,35885000.0,35940000.0,...,3.169432e+10,9.549596e+10,8.813816e+02,2.654323e+03,40610000.0,2023-04-12,20700000.0,2022-12-30,1685772930035,BTC
1,KRW-ETH,20230603,061539,20230603,151539,1685772939374,2524000.0,2528000.0,2513000.0,2518000.0,...,3.474490e+09,1.651859e+10,1.379051e+03,6.569845e+03,2795000.0,2023-04-16,1201500.0,2022-06-18,1685772939399,ETH
2,KRW-NEO,20230603,061510,20230603,151510,1685772910571,13580.0,14030.0,13500.0,13780.0,...,1.388720e+10,2.614283e+10,1.003994e+06,1.893952e+06,20420.0,2023-02-21,7535.0,2022-12-30,1685772930062,NEO
3,KRW-MTL,20230603,061503,20230603,151503,1685772903532,1330.0,1390.0,1320.0,1380.0,...,3.686220e+09,4.370430e+09,2.700755e+06,3.216552e+06,3200.0,2023-02-20,800.0,2022-12-17,1685772930065,MTL
4,KRW-XRP,20230603,061536,20230603,151536,1685772936919,695.0,696.0,690.0,694.0,...,2.339431e+10,9.029481e+10,3.374471e+07,1.309556e+08,795.0,2022-09-23,384.0,2022-06-14,1685772936951,XRP

In [25]:
both_listed_symbol_df = pd.merge(okx_instrument_df, upbit_ticker_df, on='symbol', how='inner')# inner join with okx_instrument_df and upbit_ticker_df on symbol

both_listed_symbol_df.columns

Index(['instId', 'ctVal', 'lever', 'maxMktSz', 'minSz', 'state', 'tickSz',
       'minQty', 'maxQty', 'symbol', 'market', 'trade_date', 'trade_time',
       'trade_date_kst', 'trade_time_kst', 'trade_timestamp', 'opening_price',
       'high_price', 'low_price', 'trade_price', 'prev_closing_price',
       'change', 'change_price', 'change_rate', 'signed_change_price',
       'signed_change_rate', 'trade_volume', 'acc_trade_price',
       'acc_trade_price_24h', 'acc_trade_volume', 'acc_trade_volume_24h',
       'highest_52_week_price', 'highest_52_week_date', 'lowest_52_week_price',
       'lowest_52_week_date', 'timestamp'],
      dtype='object')

In [2]:
both_listed_binance_symbols = extract_shared_listed_symbols()['both_listed_binance_symbols']

In [3]:
monitor_bot_token = "5556345865:AAFJy8wdyTjKxDBOb89bTRFsNs6UFMn4twY"
monitor_bot_api_url = "http://222.106.173.213:22180/api/master_v1/monitorbot/"

In [4]:
local_db_dict = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',
    'passwd': '13245dh',
    'database': 'test_coin_trade'
}

remote_db_dict = {
    'host': '203.210.53.251',
    'port': 3306,
    'user': 'root',
    'passwd': '13245dh',
    'database': 'test_coin_trade'
}

common_info = InitCommonInfo(local_db_dict, remote_db_dict, monitor_bot_token, monitor_bot_api_url, both_listed_binance_symbols, logging_dir="/home/coin_trading_bot/kimp_bot_core/exchange_plugin/")

2022-09-12 17:45:17,314 - common_info_logger - INFO - start_monitor_kimp_kline1|start_monitor_kimp_kline1 started.
[INFO] start_monitor_kimp_kline1|start_monitor_kimp_kline1 started.
2022-09-12 17:45:17,331 - common_info_logger - INFO - while_kimp_kline1|while_kimp_kline1 started.
[INFO] while_kimp_kline1|while_kimp_kline1 started.
2022-09-12 17:45:18,821 - common_info_logger - INFO - start_monitor_kimp_kline2|start_monitor_kimp_kline2 started.
[INFO] start_monitor_kimp_kline2|start_monitor_kimp_kline2 started.
2022-09-12 17:45:18,828 - common_info_logger - INFO - start_monitor_funding_info|start_monitor_funding_info started.
[INFO] start_monitor_funding_info|start_monitor_funding_info started.
2022-09-12 17:45:18,841 - common_info_logger - INFO - while_kimp_kline2|while_kimp_kline2 started.
[INFO] while_kimp_kline2|while_kimp_kline2 started.
2022-09-12 17:45:18,847 - common_info_logger - INFO - update_funding_info|update_funding_info started.

:

In [3]:
my_upbit_access_key = "CWCjt48ewf6T9nBxHg1zmBxxCQMUNHzgrxTCMt8F"
my_upbit_secret_key = "xK0RVf3FNjxpygpLjbd1iwTlSAVZXwgWnIG1Ivzx"

upbit_client = Upbit(my_upbit_access_key, my_upbit_secret_key)

In [4]:
import uuid
import requests
import jwt
import pandas as pd

class UpbitCustom:
    def __init__(self, upbit_access_key, upbit_secret_key):
        self.server_url = 'https://api.upbit.com'
        self.payload = {
            'access_key': upbit_access_key,
            'nonce': str(uuid.uuid4()),
        }
        self.jwt_token = jwt.encode(self.payload, upbit_secret_key)
        self.authorize_token = 'Bearer {}'.format(self.jwt_token)
        self.headers = {"Authorization": self.authorize_token}

    def market_symbols(self):
        url = self.server_url+'/v1/market/all'
        res = requests.request("GET", url)
        return pd.DataFrame(res.json())

    def all_ticker(self):
        url = self.server_url+'/v1/ticker'
        querystring = {'markets':','.join(list(self.market_symbols()['market']))}
        res = requests.request("GET", url, params=querystring)
        return pd.DataFrame(res.json())

    def candles(self, coin_name, period, count=200):
        if period in ['days', 'weeks', 'months']:
            url = self.server_url+f"/v1/candles/{period}/"
        else:
            url = self.server_url+f'/v1/candles/minutes/{period}'
        querystring = {'market':coin_name, 'count':count}
        res = requests.request("GET", url, params=querystring)
        btc_200days = pd.DataFrame(res.json())
        btc_200days = btc_200days.drop('candle_date_time_utc', axis=1)
        btc_200days['candle_date_time_kst'] = btc_200days['candle_date_time_kst'].apply(lambda x:datetime.datetime.strptime(x, "%Y-%m-%dT%H:%M:%S"))
        btc_200days = btc_200days.sort_values(by='candle_date_time_kst', ascending=True).reset_index(drop=True)
        return btc_200days

    def withdraw_stat(self):
        url = self.server_url + '/v1/status/wallet'
        res = requests.get(url, headers=self.headers)
        return pd.DataFrame(res.json())

    def account_balance(self):
        url = self.server_url + '/v1/accounts'
        res = requests.get(url, headers=self.headers)
        result_df = pd.DataFrame(res.json())
        try:
            result_df.loc[:, ['balance','locked','avg_buy_price']] = result_df[['balance','locked','avg_buy_price']].astype(float)
        except:
            pass
        return result_df

# Deprecated
def get_upbit_spot_balance(upbit_access_key, upbit_secret_key, return_dict=None):
    if return_dict == None:
        upbit_custom_client = UpbitCustom(upbit_access_key, upbit_secret_key)
        return upbit_custom_client.account_balance()
    else:
        upbit_custom_client = UpbitCustom(upbit_access_key, upbit_secret_key)
        return_dict['res'] = upbit_custom_client.account_balance()



test_res = get_upbit_spot_balance(my_upbit_access_key, my_upbit_secret_key)

In [18]:
def test_func():
    result_df = pd.DataFrame(upbit_client.Account.Account_info()['result'])
    result_df.loc[:, ['balance','locked','avg_buy_price']] = result_df[['balance','locked','avg_buy_price']].astype(float)
    return result_df

In [13]:
temp = pd.DataFrame(upbit_client.Account.Account_info()['result'])
temp

,currency,balance,locked,avg_buy_price,avg_buy_price_modified,unit_currency
0,BTC,0.754,0,26350000,False,KRW
1,KRW,7948431.76747874,0,0,True,KRW
2,ETH,15.00314493,0,2371594.0567,False,KRW
3,ETC,100.38573618,0,49580,False,KRW
4,USDT,0.05839856,0,1079.3595,False,KRW
5,EOS,5024.2,0,1721.4138,False,KRW
6,ZIL,105308.88794926,0,47.3,False,KRW
7,NEAR,770.37955073,0,6455,False,KRW
8,APENFT,516.50802691,0,0,False,KRW
9,QI,1.62935972,0,0,False,KRW

In [5]:
test_res

,currency,balance,locked,avg_buy_price,avg_buy_price_modified,unit_currency
0,BTC,7.540000e-01,0.0,2.635000e+07,False,KRW
1,KRW,7.948432e+06,0.0,0.000000e+00,True,KRW
2,ETH,1.500314e+01,0.0,2.371594e+06,False,KRW
3,ETC,1.003857e+02,0.0,4.958000e+04,False,KRW
4,USDT,5.839856e-02,0.0,1.079360e+03,False,KRW
5,EOS,5.024200e+03,0.0,1.721414e+03,False,KRW
6,ZIL,1.053089e+05,0.0,4.730000e+01,False,KRW
7,NEAR,7.703796e+02,0.0,6.455000e+03,False,KRW
8,APENFT,5.165080e+02,0.0,0.000000e+00,False,KRW
9,QI,1.629360e+00,0.0,0.000000e+00,False,KRW