In [1]:
from okx_plug import InitOkxAdaptor
from upbit_plug import InitUpbitAdaptor
from binance_plug import InitBinanceAdaptor
from bithumb_plug import InitBithumbAdaptor
from bybit_plug import InitBybitAdaptor
import pandas as pd
import json
import time
import datetime
from threading import Thread
import numpy as np

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [12]:
wallet_status_df

           0        1     2   3   4     5     6     7
0        BTC  Mainnet     1  정상  정상  None  None  None
1        ETH  Mainnet     1  정상  정상  None  None  None
2        ETC  Mainnet  1000  정상  정상  None  None  None
3        XRP  Mainnet     1  정상  정상  None  None  None
4        BCH  Mainnet    60  정상  정상  None  None  None
..       ...      ...   ...  ..  ..   ...   ...   ...
267     HIFI   ERC-20     1  정상  정상  None  None  None
268  BIGTIME   ERC-20     1  정상  정상  None  None  None
269     STMX   ERC-20     1  정상  정상  None  None  None
270     USDT    TRC20     1  정상  정상  None  None  None
271     USDC   ERC-20     1  정상  정상  None  None  None

[272 rows x 8 columns]

In [2]:
info_dict = {}
info_thread_dict = {}

okx_adaptor = InitOkxAdaptor("fcb66a6e-0443-4743-8d9b-61caf7eab662", "0029E09874B38F5AC7E68E9DFC348667", "121431Rn!!")
upbit_adaptor = InitUpbitAdaptor("x2AKLfsRtAgRxFjQ7p9TZTAg6E1SveoqfNfD8MK8", "svEran52QdsUyJdxAPYoTgFT2MXsHc5ZiKsKPxTL", info_dict, None)
binance_adaptor = InitBinanceAdaptor("4PFfYsObYyUaMlk7m6tT9qIl8X8P3WCUsyu1lEyZ4h50VfTMPIQCNdL9eOJCl3Lb", "011Z1W9p4425AZgtCNbs5L1d77ehZFNmBIwT0pz1SJGP7EiOlPILfWBglbVsxMcK", info_dict, None)
bithumb_adaptor = InitBithumbAdaptor()
bybit_adaptor = InitBybitAdaptor()

# UPBIT SPOT (KRW, BTC Market)
# UPBIT wallet status
# BINANCE SPOT, USD-M Futures, COIN-M Futures
data_name_list = [
        "upbit_spot_info_df",
        "upbit_spot_ticker_df",
        # "upbit_wallet_status_df",
        "binance_spot_ticker_df",
        "binance_spot_info_df",
        "binance_usd_m_ticker_df",
        "binance_usd_m_info_df",
        "binance_coin_m_ticker_df",
        "binance_coin_m_info_df",
        "okx_spot_ticker_df",
        "okx_spot_info_df",
        "okx_usd_m_ticker_df",
        "okx_usd_m_info_df",
        "okx_coin_m_ticker_df",
        "okx_coin_m_info_df",
        "bithumb_spot_info_df",
        "bithumb_spot_ticker_df",
        # "bithumb_wallet_status_df",
        "bybit_spot_info_df",
        "bybit_spot_ticker_df",
        "bybit_usd_m_info_df",
        "bybit_usd_m_ticker_df",
        "bybit_coin_m_info_df",
        "bybit_coin_m_ticker_df"
    ]

def update_exchange_info_as_df(data_name, loop_time_secs=15):
    if data_name == "upbit_spot_ticker_df":
        info_dict[data_name] = upbit_adaptor.spot_all_tickers()
    elif data_name == "upbit_wallet_status_df":
        info_dict[data_name] = upbit_adaptor.wallet_status()
    elif data_name == "upbit_spot_info_df":
        info_dict[data_name] = upbit_adaptor.spot_exchange_info()
    elif data_name == "binance_spot_ticker_df":
        info_dict[data_name] = binance_adaptor.spot_all_tickers()
    elif data_name == "binance_spot_info_df":
        info_dict[data_name] = binance_adaptor.spot_exchange_info()
    elif data_name == "binance_usd_m_ticker_df":
        info_dict[data_name] = binance_adaptor.usd_m_all_tickers()
    elif data_name == "binance_usd_m_info_df":
        info_dict[data_name] = binance_adaptor.usd_m_exchange_info()
    elif data_name == "binance_coin_m_ticker_df":
        info_dict[data_name] = binance_adaptor.coin_m_all_tickers()
    elif data_name == "binance_coin_m_info_df":
        info_dict[data_name] = binance_adaptor.coin_m_exchange_info()
    elif data_name == "okx_spot_ticker_df":
        info_dict[data_name] = okx_adaptor.spot_all_tickers()
    elif data_name == "okx_spot_info_df":
        info_dict[data_name] = okx_adaptor.spot_exchange_info()
    elif data_name == "okx_usd_m_ticker_df":
        info_dict[data_name] = okx_adaptor.usd_m_all_tickers()
    elif data_name == "okx_usd_m_info_df":
        info_dict[data_name] = okx_adaptor.usd_m_exchange_info()
    elif data_name == "okx_coin_m_ticker_df":
        info_dict[data_name] = okx_adaptor.coin_m_all_tickers()
    elif data_name == "okx_coin_m_info_df":
        info_dict[data_name] = okx_adaptor.coin_m_exchange_info()
    elif data_name == "bithumb_spot_info_df":
        info_dict[data_name] = bithumb_adaptor.spot_exchange_info()
    elif data_name == "bithumb_spot_ticker_df":
        info_dict[data_name] = bithumb_adaptor.spot_all_tickers()
    elif data_name == "bithumb_wallet_status_df":
        info_dict[data_name] = bithumb_adaptor.wallet_status()
    elif data_name == "bybit_spot_info_df":
        info_dict[data_name] = bybit_adaptor.spot_exchange_info()
    elif data_name == "bybit_spot_ticker_df":
        info_dict[data_name] = bybit_adaptor.spot_all_tickers()
    elif data_name == "bybit_usd_m_info_df":
        info_dict[data_name] = bybit_adaptor.usd_m_exchange_info()
    elif data_name == "bybit_usd_m_ticker_df":
        info_dict[data_name] = bybit_adaptor.usd_m_all_tickers()
    elif data_name == "bybit_coin_m_info_df":
        info_dict[data_name] = bybit_adaptor.coin_m_exchange_info()
    elif data_name == "bybit_coin_m_ticker_df":
        info_dict[data_name] = bybit_adaptor.coin_m_all_tickers()
    else:
        print(f"update_exchange_info_as_df|name:{data_name} is not valid.")

for data_name in data_name_list:
    info_thread_dict[f"update_{data_name}"] = Thread(target=update_exchange_info_as_df, args=(data_name,), daemon=True)
    info_thread_dict[f"update_{data_name}"].start()
    print(f"InitCore|update_{data_name} thread has started.")

2024-01-05 12:23:56,980 - okx_plug - INFO - okx_plug_logger started.
2024-01-05 12:23:57,336 - upbit_plug - INFO - upbit_plug_logger started.
2024-01-05 12:23:57,485 - binance_plug - INFO - binance_plug_logger started.
2024-01-05 12:23:57,486 - bithumb_plug - INFO - bithumb_plug_logger started.
2024-01-05 12:23:57,488 - bybit_plug - INFO - bybit_plug_logger started.

InitCore|update_upbit_spot_info_df thread has started.
InitCore|update_upbit_spot_ticker_df thread has started.
InitCore|update_binance_spot_ticker_df thread has started.
InitCore|update_binance_spot_info_df thread has started.
InitCore|update_binance_usd_m_ticker_df thread has started.
InitCore|update_binance_usd_m_info_df thread has started.
InitCore|update_binance_coin_m_ticker_df thread has started.
InitCore|update_binance_coin_m_info_df thread has started.
InitCore|update_okx_spot_ticker_df thread has started.
InitCore|update_okx_spot_info_df thread has started.
InitCore|update_okx_usd_m_ticker_df thread has started.
InitCore|update_okx_usd_m_info_df thread has started.
InitCore|update_okx_coin_m_ticker_df thread has started.
InitCore|update_okx_coin_m_info_df thread has started.
InitCore|update_bithumb_spot_info_df thread has started.
InitCore|update_bithumb_spot_ticker_df thread has started.
InitCore|update_bybit_spot_info_df thread has started.
InitCore|update_bybit_spot_ticker_df thread has started.
InitCore|update_bybit_usd_m_info_df thread has started.
InitCore|update_bybit_usd_m_ticker_df thread has started.
InitCore|update_bybit_coin_m_info_df thread has started.
InitCore|update_bybit_coin_m_ticker_df thread has started.

2024-01-05 12:23:58,447 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_coin_m_info_df') is None, Fetched from API
2024-01-05 12:23:59,251 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API

In [3]:


futures_type = 'USD_M'

if futures_type == "COIN_M":
    symbol_list = [x['instId'] for x in okx_adaptor.pub_client.PublicAPI.get_instruments(instType='SWAP')['data'] if x['instId'].split("-")[1] == "USD"]
elif futures_type == "USD_M":
    symbol_list = [x['instId'] for x in okx_adaptor.pub_client.PublicAPI.get_instruments(instType='SWAP')['data'] if x['instId'].split("-")[1] != "USD"]
else:
    print(f"get_okx_fundingrate|futures_type:{futures_type} is not valid.")

funding_data_list = []
for each_symbol in symbol_list:
    funding_data_list.append(okx_adaptor.pub_client.PublicAPI.get_funding_rate(each_symbol)['data'][0])
    time.sleep(0.25)

funding_df = pd.DataFrame(funding_data_list)

2024-01-05 12:23:59,547 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_spot_info_df') is None, Fetched from API

2024-01-05 12:24:00,040 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API
2024-01-05 12:24:00,601 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2024-01-05 12:24:00,882 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API

In [8]:
funding_df.head()

,fundingRate,fundingTime,instId,instType,maxFundingRate,method,minFundingRate,nextFundingRate,nextFundingTime,settFundingRate,settState,ts
0,0.0000161946813798,1704470400000,BTC-USDT-SWAP,SWAP,0.00375,next_period,-0.00375,-0.0000659440342575,1704499200000,-0.0000164075951846,settled,1704457389426
1,0.0000051167638481,1704470400000,ETH-USDT-SWAP,SWAP,0.0075,next_period,-0.0075,-0.0000051632079658,1704499200000,0.0000583489375588,settled,1704457389453
2,0.0001934894893152,1704470400000,MATIC-USDT-SWAP,SWAP,0.015,next_period,-0.015,-0.0000013167367552,1704499200000,-0.0000658729122316,settled,1704457389131
3,0.0000897588651794,1704470400000,XRP-USDT-SWAP,SWAP,0.0075,next_period,-0.0075,0.0000404058210393,1704499200000,0.0000308316835941,settled,1704457389045
4,0.0000604540875843,1704470400000,SOL-USDT-SWAP,SWAP,0.015,next_period,-0.015,-0.0000618323235179,1704499200000,0.0001145881620822,settled,1704457389203

In [10]:
mask = (funding_df["fundingRate"] == '') | (funding_df["fundingTime"] == '') | \
       (funding_df["nextFundingRate"] == '') | (funding_df["nextFundingTime"] == '')

funding_df[mask].replace('', np.nan, inplace=True)

In [14]:
funding_df.replace('', np.nan, inplace=True)

In [16]:
funding_df[mask]

,fundingRate,fundingTime,instId,instType,maxFundingRate,method,minFundingRate,nextFundingRate,nextFundingTime,settFundingRate,settState,ts
63,0.0000379478611466,1704470400000,FLOW-USDT-SWAP,SWAP,0.015,current_period,-0.015,NaN,1704499200000,0.0002169388939514,settled,1704457456455

In [15]:
funding_df[["fundingRate", "fundingTime", "nextFundingRate", "nextFundingTime"]].astype(float)

     fundingRate   fundingTime  nextFundingRate  nextFundingTime
0       0.000016  1.704470e+12        -0.000066     1.704499e+12
1       0.000005  1.704470e+12        -0.000005     1.704499e+12
2       0.000193  1.704470e+12        -0.000001     1.704499e+12
3       0.000090  1.704470e+12         0.000040     1.704499e+12
4       0.000060  1.704470e+12        -0.000062     1.704499e+12
..           ...           ...              ...              ...
150     0.000287  1.704470e+12         0.000566     1.704499e+12
151     0.000004  1.704470e+12         0.000157     1.704499e+12
152     0.000107  1.704470e+12         0.000116     1.704499e+12
153    -0.000133  1.704470e+12        -0.000115     1.704499e+12
154     0.000048  1.704470e+12         0.000079     1.704499e+12

[155 rows x 4 columns]