In [1]:
from okx_plug import InitOkxAdaptor
from upbit_plug import InitUpbitAdaptor
from binance_plug import InitBinanceAdaptor
import pandas as pd
import json
import time
import datetime
from threading import Thread

In [2]:
upbit_adaptor = InitUpbitAdaptor()
binance_adaptor = InitBinanceAdaptor(info_dict={})
okx_adaptor = InitOkxAdaptor()

2023-10-31 19:14:53,399 - upbit_plug - INFO - upbit_plug_logger started.
2023-10-31 19:14:53,509 - binance_plug - INFO - binance_plug_logger started.
2023-10-31 19:14:53,613 - okx_plug - INFO - okx_plug_logger started.

In [3]:
upbit_adaptor.all_tickers()

,market,trade_date,trade_time,trade_date_kst,trade_time_kst,trade_timestamp,opening_price,high_price,low_price,lastPrice,...,acc_trade_volume,acc_trade_volume_24h,highest_52_week_price,highest_52_week_date,lowest_52_week_price,lowest_52_week_date,timestamp,base_asset,quote_asset,acc_trade_price_24h_krw
0,KRW-BTC,20231031,101452,20231031,191452,1698747292645,4.673400e+07,4.690000e+07,4.630200e+07,4.675300e+07,...,1.768811e+03,3.834457e+03,4.745900e+07,2023-10-24,2.070000e+07,2022-12-30,1698747292671,BTC,KRW,1.792591e+11
1,KRW-ETH,20231031,101419,20231031,191419,1698747259177,2.450000e+06,2.464000e+06,2.427000e+06,2.450000e+06,...,5.367174e+03,1.198438e+04,2.795000e+06,2023-04-16,1.500000e+06,2022-12-30,1698747270042,ETH,KRW,2.938367e+10
2,BTC-ETH,20231031,100941,20231031,190941,1698746981214,5.215954e-02,5.271930e-02,5.215954e-02,5.230387e-02,...,8.672697e+00,1.036133e+01,7.890000e-02,2022-11-04,5.144385e-02,2023-10-26,1698747270043,ETH,BTC,2.532972e+07
3,BTC-XRP,20231031,101253,20231031,191253,1698747173289,1.667000e-05,1.689000e-05,1.661000e-05,1.670000e-05,...,3.200543e+04,2.448115e+05,2.888000e-05,2023-07-19,1.273000e-05,2023-05-16,1698747270046,XRP,BTC,1.910784e+08
4,BTC-ETC,20231031,91300,20231031,181300,1698743580598,4.870700e-04,4.915100e-04,4.853400e-04,4.894600e-04,...,4.805129e+02,7.147475e+02,1.303570e-03,2022-11-06,4.625500e-04,2023-10-30,1698747270048,ETC,BTC,1.623573e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,BTC-SEI,20231031,73705,20231031,163705,1698737825400,3.340000e-06,3.340000e-06,3.250000e-06,3.250000e-06,...,7.968364e+03,2.361766e+04,2.187000e-05,2023-08-16,3.090000e-06,2023-10-27,1698747270632,SEI,BTC,3.639185e+06
295,KRW-SEI,20231031,101422,20231031,191422,1698747262562,1.530000e+02,1.570000e+02,1.500000e+02,1.540000e+02,...,5.231893e+07,8.305936e+07,8.560000e+02,2023-08-16,1.290000e+02,2023-10-19,1698747270636,SEI,KRW,1.277275e+10
296,BTC-CYBER,20231031,101449,20231031,191449,1698747289310,1.859800e-04,2.038700e-04,1.814500e-04,2.012600e-04,...,3.083076e+05,4.297674e+05,1.393730e-03,2023-09-02,1.300400e-04,2023-10-23,1698747289347,CYBER,BTC,3.790577e+09
297,BTC-GLMR,20231031,100700,20231031,190700,1698746820710,6.100000e-06,6.270000e-06,5.950000e-06,6.050000e-06,...,1.512210e+06,2.247904e+06,1.070000e-05,2023-09-27,5.180000e-06,2023-10-24,1698747270641,GLMR,BTC,6.406437e+08
298,KRW-MINA,20231031,101440,20231031,191440,1698747280324,8.580000e+02,8.660000e+02,8.250000e+02,8.410000e+02,...,1.119909e+07,2.765501e+07,4.425000e+03,2023-10-24,5.550000e+02,2023-10-24,1698747280366,MINA,KRW,2.364676e+10

In [4]:
binance_adaptor.spot_all_tickers()

2023-10-31 19:14:54,812 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

,symbol,priceChange,priceChangePercent,weightedAvgPrice,prevClosePrice,lastPrice,lastQty,bidPrice,bidQty,askPrice,...,quoteVolume,openTime,closeTime,firstId,lastId,count,base_asset,quote_asset,quote_symbol,volume_usdt
0,ETHBTC,-0.000220,-0.418,0.052446,0.052580,0.052360,36.774,0.052360,16.5578,0.052370,...,1.191338e+03,1698660892805,1698747292805,424743635,424780180,36546,ETH,BTC,BTCUSDT,4.095914e+07
1,LTCBTC,0.000032,1.606,0.002009,0.001992,0.002025,0.092,0.002023,0.6700,0.002024,...,9.022542e+01,1698660893843,1698747293843,93943219,93952869,9651,LTC,BTC,BTCUSDT,3.102022e+06
2,BNBBTC,0.000011,0.167,0.006610,0.006596,0.006607,0.103,0.006607,736.0840,0.006608,...,1.762975e+02,1698660888773,1698747288773,228269605,228296219,26615,BNB,BTC,BTCUSDT,6.061249e+06
3,NEOBTC,-0.000003,-1.108,0.000263,0.000261,0.000259,17.690,0.000259,22.4300,0.000259,...,1.151883e+01,1698660888248,1698747288248,45615708,45619455,3748,NEO,BTC,BTCUSDT,3.960265e+05
4,QTUMETH,-0.000004,-0.241,0.001679,0.001646,0.001657,2.100,0.001659,122.1000,0.001666,...,8.269740e+00,1698660893396,1698747293396,5406209,5406358,150,QTUM,ETH,ETHUSDT,1.488818e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2320,DOTFDUSD,0.145000,3.368,4.446395,4.328000,4.450000,200.000,4.448000,22.4800,4.462000,...,1.931136e+04,1698660877818,1698747277818,553,753,201,DOT,FDUSD,FDUSDUSDT,1.931908e+04
2321,FTMFDUSD,-0.007300,-2.972,0.242248,0.244900,0.238300,559.000,0.242100,413.0000,0.243000,...,9.305489e+03,1698660886353,1698747286353,464,556,93,FTM,FDUSD,FDUSDUSDT,9.309211e+03
2322,LINKFDUSD,0.271000,2.399,11.479407,11.312000,11.565000,0.550,11.519000,11.9000,11.546000,...,1.254340e+05,1698660888003,1698747288003,4136,4740,605,LINK,FDUSD,FDUSDUSDT,1.254842e+05
2323,NEARFDUSD,0.018000,1.395,1.303202,1.280000,1.308000,16.700,1.294000,988.8000,1.300000,...,1.100241e+04,1698660857032,1698747257032,365,456,92,NEAR,FDUSD,FDUSDUSDT,1.100681e+04
2324,STRAXTRY,5.550000,22.699,28.802785,24.450000,30.000000,750.200,30.000000,2767.6000,30.020000,...,2.521012e+08,1698660893060,1698747293060,100562,131062,30501,STRAX,TRY,TRYUSDT,NaN

In [7]:
binance_adaptor.usd_m_all_tickers()

2023-10-31 19:15:03,392 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-10-31 19:15:04,248 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-10-31 19:15:04,265 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API

,symbol,priceChange,priceChangePercent,weightedAvgPrice,lastPrice,lastQty,openPrice,highPrice,lowPrice,volume,quoteVolume,openTime,closeTime,firstId,lastId,count,base_asset,quote_asset,quote_symbol,volume_usdt
0,HBARUSDT,-0.00013,-0.246,0.052980,0.05278,3789.0,0.05291,0.05403,0.05183,3.124423e+08,1.655358e+07,1698660840000,1698747294042,163866864,163981815,114952,HBAR,USDT,USDTUSDT,1.655358e+07
1,RENUSDT,0.00043,0.832,0.051650,0.05212,10130.0,0.05169,0.05282,0.04965,2.897646e+08,1.496620e+07,1698660840000,1698747286003,206343026,206452403,109377,REN,USDT,USDTUSDT,1.496620e+07
2,FILUSDT,0.00500,0.131,3.842000,3.83500,13.0,3.83000,3.95000,3.72600,2.993273e+07,1.149984e+08,1698660840000,1698747295149,503182052,503445723,263670,FIL,USDT,USDTUSDT,1.149984e+08
3,AUDIOUSDT,0.00200,1.172,0.171400,0.17270,407.0,0.17070,0.17650,0.16550,5.165741e+07,8.856647e+06,1698660840000,1698747277045,153511030,153587651,76622,AUDIO,USDT,USDTUSDT,8.856647e+06
4,DUSKUSDT,-0.00047,-0.362,0.129540,0.12945,102.0,0.12992,0.13266,0.12581,5.078983e+07,6.579523e+06,1698660840000,1698747294565,97171000,97216035,45035,DUSK,USDT,USDTUSDT,6.579523e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,DOTUSDT,0.13700,3.175,4.440000,4.45200,12.7,4.31500,4.60000,4.26200,5.921371e+07,2.629293e+08,1698660840000,1698747299311,701738127,702192003,453869,DOT,USDT,USDTUSDT,2.629293e+08
246,FLOWUSDT,-0.01400,-2.578,0.536000,0.52900,57.0,0.54300,0.55000,0.51600,4.762509e+07,2.551330e+07,1698660840000,1698747299118,69636522,69703003,66482,FLOW,USDT,USDTUSDT,2.551330e+07
247,ARKUSDT,0.10580,12.312,0.966708,0.96510,96.0,0.85930,1.11000,0.82880,1.655783e+09,1.600658e+09,1698660840000,1698747298667,21769695,27462267,5691914,ARK,USDT,USDTUSDT,1.600658e+09
248,NMRUSDT,-0.06000,-0.423,14.104967,14.13000,9.0,14.19000,14.51000,13.63000,5.576852e+05,7.866131e+06,1698660840000,1698747298176,20435052,20505522,70471,NMR,USDT,USDTUSDT,7.866131e+06
249,C98USDT,0.00490,2.683,0.186500,0.18750,39.0,0.18260,0.19240,0.17910,1.482692e+08,2.765774e+07,1698660840000,1698747289356,170746250,170889202,142953,C98,USDT,USDTUSDT,2.765774e+07

In [6]:
spot_tickers_df = pd.DataFrame(okx_adaptor.pub_client.MarketAPI.get_tickers(instType="SPOT")['data']).drop(columns=['instType'])
spot_tickers_df['base_asset'] = spot_tickers_df['instId'].apply(lambda x: x.split('-')[0])
spot_tickers_df['quote_asset'] = spot_tickers_df['instId'].apply(lambda x: x.split('-')[1])
spot_tickers_df.loc[:, 'last':'sodUtc0'] = spot_tickers_df.loc[:, 'last':'sodUtc0'].apply(pd.to_numeric)
spot_tickers_df = spot_tickers_df.rename(columns={"last": "lastPrice"})
spot_tickers_df['volume_usdt'] = spot_tickers_df.apply\
    (lambda x: x['volCcy24h'] if x['quote_asset'] == "USDT" else x['volCcy24h'] * spot_tickers_df[spot_tickers_df['instId']==f"{x['quote_asset']}-USDT"]['lastPrice'].iloc[0], axis=1)
spot_tickers_df

,instId,lastPrice,lastSz,askPx,askSz,bidPx,bidSz,open24h,high24h,low24h,volCcy24h,vol24h,ts,sodUtc0,sodUtc8,base_asset,quote_asset,volume_usdt
0,MDT-USDT,0.04857,1598.081531,0.04855,4049.982261,0.04841,55356.123408,0.04697,0.04885,0.04588,120064.229964,2537294.172518,1698747288411,0.04758,0.04666,MDT,USDT,1.200642e+05
1,LUNA-USDC,0.4736,1.01,0.4739,286.3241,0.473,200.0,0.4854,0.4867,0.4633,28099.517519,58968.3478,1698747294509,0.475,0.4756,LUNA,USDC,2.809109e+04
2,OAS-USDT,0.045267,498.74,0.045271,889.62,0.045267,261.39,0.046285,0.046378,0.044384,170092.106454,3738571.23,1698747240010,0.045424,0.04537,OAS,USDT,1.700921e+05
3,LINK-BTC,0.000336,57.533,0.000336,25.96,0.000335,132.039,0.000328,0.00035,0.000322,44.75888,133768.749,1698747294209,0.000325,0.0003282,LINK,BTC,1.538578e+06
4,KNC-USDT,0.7809,1.277791,0.7811,5185.740489,0.7799,100.0,0.7557,0.7841,0.7364,635683.897421,834912.54732,1698747295210,0.7645,0.7519,KNC,USDT,6.356839e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,SKEB-USDT,0.001646,6111.42,0.001646,5692.14,0.001628,16661.59,0.001645,0.001669,0.001624,723.88555,438795.68,1698747240013,0.00166,0.0016453,SKEB,USDT,7.238856e+02
474,GLMR-USDT,0.2092,56.432217,0.2094,1237.363319,0.2092,1652.827242,0.2101,0.2144,0.2043,152954.171004,729063.050898,1698747294708,0.2114,0.2084,GLMR,USDT,1.529542e+05
475,XRP-BTC,0.000017,75.0,0.000017,162.61,0.000017,20832.295,0.000016,0.000017,0.000016,66.315198,3987240.503,1698747295309,0.000017,0.00001668,XRP,BTC,2.279572e+06
476,WIFI-USDT,0.036,942.0,0.03609,13.109,0.03598,1027.04,0.03531,0.03696,0.03504,5779.627326,161219.104,1698747290308,0.03553,0.03595,WIFI,USDT,5.779627e+03
477,STX-USDT,0.6358,18.7946,0.6359,275.0,0.6357,730.400461,0.6336,0.6444,0.6151,1728344.158031,2742466.347034,1698747295212,0.6315,0.633,STX,USDT,1.728344e+06

In [44]:
usd_m_tickers_df = pd.DataFrame(okx_adaptor.pub_client.MarketAPI.get_tickers(instType="SWAP")['data']).drop(columns=['instType'])
usd_m_tickers_df['base_asset'] = usd_m_tickers_df['instId'].apply(lambda x: x.split('-')[0])
usd_m_tickers_df['quote_asset'] = usd_m_tickers_df['instId'].apply(lambda x: x.split('-')[1])
usd_m_tickers_df.loc[:, 'last':'sodUtc0'] = usd_m_tickers_df.loc[:, 'last':'sodUtc0'].apply(pd.to_numeric)
usd_m_tickers_df = usd_m_tickers_df.rename(columns={"last": "lastPrice"})
usd_m_tickers_df['volume_usdt'] = usd_m_tickers_df['lastPrice'] * usd_m_tickers_df['volCcy24h']
usd_m_tickers_df = usd_m_tickers_df[usd_m_tickers_df['quote_asset'] == "USD"]
usd_m_tickers_df = usd_m_tickers_df.reset_index(drop=True)
usd_m_tickers_df

,instId,lastPrice,lastSz,askPx,askSz,bidPx,bidSz,open24h,high24h,low24h,volCcy24h,vol24h,ts,sodUtc0,sodUtc8,base_asset,quote_asset,volume_usdt
0,XMR-USD-SWAP,172.84,23,172.92,25,172.75,34,169.72,175.14,169.39,1567.0653,26994,1698744735910,173.47,172.85,XMR,USD,270851.566452
1,SAND-USD-SWAP,0.3522,22,0.3524,45,0.3522,49,0.3582,0.3621,0.3455,1349092.3674,47890,1698744735710,0.3567,0.3553,SAND,USD,475150.331798
2,ZEC-USD-SWAP,28.16,1,28.22,47,28.18,49,28.62,28.95,27.66,18452.5565,52269,1698744734212,28.5,28.42,ZEC,USD,519623.99104
3,XLM-USD-SWAP,0.11725,3,0.11741,113,0.11731,25,0.11669,0.1201,0.11554,3289547.9453,38944,1698744733709,0.11904,0.11885,XLM,USD,385699.496586
4,YFI-USD-SWAP,5810.0,25,5793.0,22,5787.0,28,5981.0,6040.0,5663.0,20.3456,11970,1698744729709,5915.0,5903,YFI,USD,118207.936
5,UNI-USD-SWAP,4.166,3,4.172,130,4.17,68,4.201,4.257,4.073,596169.0999,248657,1698744735709,4.184,4.192,UNI,USD,2483640.470183
6,SOL-USD-SWAP,36.272,15,36.248,25,36.23,60,34.994,36.66,34.279,408485.7816,1441776,1698744735806,34.967,35.076,SOL,USD,14816596.270195
7,THETA-USD-SWAP,0.6903,26,0.6913,182,0.6904,42,0.6894,0.7011,0.6723,268474.9449,18511,1698744735911,0.6936,0.688,THETA,USD,185328.254464
8,AVAX-USD-SWAP,11.528,25,11.533,25,11.528,25,11.603,11.785,11.311,271079.7163,314618,1698744735408,11.465,11.612,AVAX,USD,3125006.969506
9,DOT-USD-SWAP,4.471,1,4.47,351,4.469,60,4.34,4.607,4.268,919717.0086,407806,1698744735412,4.522,4.357,DOT,USD,4112054.745451
10,FIL-USD-SWAP,3.837,1,3.836,100,3.835,126,3.86,3.948,3.731,3792324.588,1454562,1698744735012,3.857,3.85,FIL,USD,14551149.444156
11,CRV-USD-SWAP,0.4842,21,0.4846,31,0.4842,181,0.5013,0.5027,0.4767,1841350.6286,90331,1698744734412,0.4883,0.4946,CRV,USD,891581.974368
12,SUSHI-USD-SWAP,0.6883,82,0.6902,25,0.6898,20,0.6459,0.6943,0.6314,929935.857,61476,1698744735906,0.6471,0.6477,SUSHI,USD,640074.850373
13,LTC-USD-SWAP,70.1,2,70.1,548,70.09,314,69.56,70.6,67.87,300338.0176,2075874,1698744735209,69.24,69.6,LTC,USD,21053695.03376
14,TRX-USD-SWAP,0.09616,3,0.09617,117,0.09616,25,0.09512,0.09655,0.0945,3604770.8263,34425,1698744735309,0.09569,0.09512,TRX,USD,346634.762657
15,XRP-USD-SWAP,0.57247,1,0.57248,55,0.57247,170,0.5613,0.58444,0.5571,37099375.1531,2127622,1698744735412,0.57838,0.57824,XRP,USD,21238279.293895
16,ADA-USD-SWAP,0.29692,6,0.29697,453,0.29689,25,0.29913,0.30499,0.29404,7395111.423,221422,1698744734610,0.30341,0.30182,ADA,USD,2195756.483717
17,MANA-USD-SWAP,0.3716,74,0.3713,38,0.3709,144,0.3782,0.3802,0.3634,522342.7674,19519,1698744735508,0.378,0.375,MANA,USD,194102.572366
18,ETC-USD-SWAP,16.832,1,16.824,50,16.816,29,16.827,17.022,16.439,171263.8798,286770,1698744734410,16.785,16.822,ETC,USD,2882713.624794
19,BTC-USD-SWAP,34398.4,7,34398.5,1804,34398.4,11,34681.9,34888.0,34040.9,13651.6264,4704091,1698744735709,34500.1,34674.9,BTC,USD,469594105.55776
20,EOS-USD-SWAP,0.6243,25,0.624,184,0.6239,68,0.6253,0.6407,0.611,10087963.6924,631240,1698744734406,0.6279,0.6252,EOS,USD,6297915.733165
21,1INCH-USD-SWAP,0.2933,10,0.2957,179,0.295,148,0.2973,0.3005,0.2884,479155.1255,14167,1698744734509,0.2999,0.2957,1INCH,USD,140536.198309
22,GRT-USD-SWAP,0.10649,31,0.10653,25,0.1065,50,0.10905,0.11083,0.10451,4038144.487,43740,1698744733711,0.1097,0.10761,GRT,USD,430022.006421
23,DASH-USD-SWAP,29.96,8,30.01,24,29.98,43,28.99,30.99,28.75,25181.7039,74729,1698744734409,29.5,29.37,DASH,USD,754443.848844
24,ETH-USD-SWAP,1800.29,1,1800.63,6955,1800.62,699,1828.46,1832.47,1777.54,145845.129,26335326,1698744735008,1809.81,1820.98,ETH,USD,262563527.28741
25,ATOM-USD-SWAP,7.947,28,7.935,25,7.931,25,7.4,8.166,7.359,281254.282,220809,1698744734609,8.105,7.562,ATOM,USD,2235127.779054
26,NEO-USD-SWAP,8.88,53,8.893,21,8.882,62,9.103,9.275,8.717,33364.6539,30046,1698744734509,9.03,9.135,NEO,USD,296278.126632
27,DOGE-USD-SWAP,0.06885,5,0.06886,90,0.06884,475,0.06961,0.07041,0.0677,163753385.1116,1133278,1698744733812,0.06963,0.06985,DOGE,USD,11274420.564934
28,LINK-USD-SWAP,11.502,20,11.506,26,11.5,62,11.422,12.03,11.045,1151872.8974,1325871,1698744735906,11.236,11.392,LINK,USD,13248842.065895
29,ALGO-USD-SWAP,0.10943,21,0.10943,50,0.10935,76,0.10843,0.11387,0.10671,3135847.0974,34524,1698744732410,0.112,0.10914,ALGO,USD,343155.747868
30,KSM-USD-SWAP,21.83,7,21.81,57,21.77,54,21.95,22.75,20.7,18624.7508,40541,1698744733711,22.07,21.74,KSM,USD,406578.309964
31,BCH-USD-SWAP,244.23,14,244.29,94,244.26,58,248.16,251.32,241.02,22636.2738,556872,1698744735610,246.09,246.45,BCH,USD,5528457.150174
32,BSV-USD-SWAP,49.13,23,49.12,50,49.09,90,50.22,51.16,48.02,44275.0551,219784,1698744734107,50.29,49.89,BSV,USD,2175233.457063

In [38]:
usd_m_tickers_df.sort_values('volume_usdt', ascending=False).head(10)

,instId,lastPrice,lastSz,askPx,askSz,bidPx,bidSz,open24h,high24h,low24h,volCcy24h,vol24h,ts,sodUtc0,sodUtc8,base_asset,quote_asset,volume_usdt
18,BTC-USDT-SWAP,34419.9,2,34420.0,43,34419.9,2568,34504.1,34882.2,34004.7,124053.33,12405333,1698743497408,34476.6,34660.4,BTC,USDT,4269903213.267
51,ETH-USDT-SWAP,1802.77,7,1802.78,899,1802.77,1212,1823.88,1832.73,1775.16,1863988.3,18639883,1698743497413,1809.01,1819.92,ETH,USDT,3360342187.591
145,TRB-USDT-SWAP,116.522,8,116.522,22,116.518,44,115.432,125.426,109.858,8355625.4,83556254,1698743497498,117.912,123.501,TRB,USDT,973614182.8588
126,SOL-USDT-SWAP,36.401,10,36.404,28,36.403,22,34.69,36.654,34.225,13871431.0,13871431,1698743497407,34.944,35.042,SOL,USDT,504933959.831
104,BTC-USD-SWAP,34441.9,31,34443.3,586,34443.2,6,34520.4,34888.0,34040.9,13961.9346,4811618,1698743497403,34500.1,34674.9,BTC,USD,480875555.29974
33,LINK-USDT-SWAP,11.59,2,11.59,863,11.589,11425,11.378,12.033,11.041,31173706.0,31173706,1698743497406,11.221,11.389,LINK,USDT,361303252.54
128,ETH-USD-SWAP,1803.0,1,1803.54,86,1803.53,15441,1825.15,1832.47,1777.54,148248.3129,26775592,1698743497107,1809.81,1820.98,ETH,USD,267291708.1587
166,XRP-USDT-SWAP,0.57288,1,0.57296,7,0.57295,150,0.55638,0.58431,0.55598,342684400.0,3426844,1698743497413,0.57801,0.57767,XRP,USDT,196317039.072
34,DOGE-USDT-SWAP,0.06899,1,0.06899,107,0.06898,216,0.06947,0.07042,0.06762,2150648000.0,2150648,1698743496512,0.06962,0.06976,DOGE,USDT,148373205.52
141,WLD-USDT-SWAP,1.9604,22,1.9613,271,1.9612,611,1.8916,1.97,1.8402,70371387.0,70371387,1698743497413,1.8874,1.8794,WLD,USDT,137956067.0748

In [10]:
total_df = pd.DataFrame()
# upbit_ticker_df = self.info_dict['upbit_spot_ticker_df'][['market','acc_trade_price_24h_krw']].copy()
upbit_ticker_df = upbit_adaptor.all_tickers() # TEMP
upbit_ticker_df['base_symbol'] = upbit_ticker_df['market'].apply(lambda x: x.split('-')[1])
# for upbit_market in self.enabled_markets_dict['UPBIT']['SPOT']:
for upbit_market in ["KRW-", "BTC-"]: # TEMP
    each_upbit_ticker_df = upbit_ticker_df[upbit_ticker_df['market'].str.startswith(upbit_market)].copy()
    
    # for binance_spot_market in self.enabled_markets_dict['BINANCE']['SPOT']:
    for binance_spot_market in ["USDT", "BTC"]: # TEMP
        # each_binance_spot_info_df = self.info_dict['binance_spot_info_df'][self.info_dict['binance_spot_info_df']['symbol'].str.endswith(binance_spot_market)].copy()
        temp_df = binance_adaptor.spot_exchange_info() # TEMP
        each_binance_spot_info_df = temp_df[temp_df['symbol'].str.endswith(binance_spot_market)].copy() # TEMP
        each_binance_spot_info_df['base_symbol'] = each_binance_spot_info_df['symbol'].apply(lambda x: x[:-len(binance_spot_market)])
        merged_df = each_upbit_ticker_df.merge(each_binance_spot_info_df[['symbol','base_symbol']], on='base_symbol', how='inner')
        total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

    # for binance_usd_m_market in self.enabled_markets_dict['BINANCE']['USD_M_FUTURES']: # ["USDT_PERPETUAL", "BUSD_PERPETUAL"]
    for binance_usd_m_market in ["USDT_PERPETUAL"]: # TEMP
        # Check PERPETUAL
        quote_asset, contract_type = binance_usd_m_market.split('_')
        # each_binance_usd_m_info_df = self.info_dict['binance_usd_m_info_df'][(self.info_dict['binance_usd_m_info_df']['quoteAsset']==quote_asset)&(self.info_dict['binance_usd_m_info_df']['contractType']==contract_type)].copy()        
        temp_df = binance_adaptor.usd_m_exchange_info() # TEMP
        each_binance_usd_m_info_df = temp_df[(temp_df['quoteAsset']==quote_asset)&(temp_df['contractType']==contract_type)].copy()        
        merged_df = each_upbit_ticker_df.merge(each_binance_usd_m_info_df[['symbol','baseAsset']], left_on='base_symbol', right_on='baseAsset' ,how='inner')
        total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

    # for binance_coin_m_market in self.enabled_markets_dict['BINANCE']['COIN_M_FUTURES']: # ["PERPETUAL"]
    for binance_coin_m_market in ["PERPETUAL"]: # TEMP
        # Check PERPETUAL
        contract_type = binance_coin_m_market
        # each_binance_coin_m_info_df = self.info_dict['binance_coin_m_info_df'][self.info_dict['binance_coin_m_info_df']['contractType']==contract_type].copy()
        temp_df = binance_adaptor.coin_m_exchange_info()
        each_binance_coin_m_info_df = temp_df[temp_df['contractType']==contract_type].copy() # TEMP
        merged_df = each_upbit_ticker_df.merge(each_binance_coin_m_info_df[['symbol','baseAsset']], left_on='base_symbol', right_on='baseAsset' ,how='inner')
        total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

    # for okx_spot_quote_asset in self.enabled_market_dict['OKX']['SPOT']:
    for okx_spot_quote_asset in ["USDT", "BTC"]: # TEMP
        # each_okx_spot_ticker_df = self.info_dict['okx_spot_ticker_df'][self.info_dict['okx_spot_ticker_df']['quote_asset']==okx_spot_market].copy()
        temp_df = okx_adaptor.spot_all_tickers()
        each_okx_spot_ticker_df = temp_df[temp_df['quote_asset']==okx_spot_market].copy() # TEMP

In [20]:
binance_adaptor.spot_all_tickers()

2023-10-31 19:30:53,864 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

,symbol,priceChange,priceChangePercent,weightedAvgPrice,prevClosePrice,lastPrice,lastQty,bidPrice,bidQty,askPrice,...,quoteVolume,openTime,closeTime,firstId,lastId,count,base_asset,quote_asset,quote_symbol,volume_usdt
0,ETHBTC,-0.000180,-0.342,0.052444,0.052550,0.052380,4.3188,0.052380,59.1619,0.052390,...,1.178577e+03,1698661852139,1698748252139,424744255,424780386,36132,ETH,BTC,BTCUSDT,4.051826e+07
1,LTCBTC,0.000014,0.700,0.002009,0.001999,0.002015,37.1060,0.002016,82.0290,0.002017,...,9.264934e+01,1698661849319,1698748249319,93943320,93953192,9873,LTC,BTC,BTCUSDT,3.185189e+06
2,BNBBTC,0.000008,0.121,0.006610,0.006602,0.006609,0.9980,0.006609,34.2670,0.006610,...,1.770400e+02,1698661851636,1698748251636,228269878,228296459,26582,BNB,BTC,BTCUSDT,6.086452e+06
3,NEOBTC,-0.000007,-2.663,0.000263,0.000266,0.000260,0.2000,0.000260,36.7100,0.000260,...,1.119476e+01,1698661848635,1698748248635,45615865,45619499,3635,NEO,BTC,BTCUSDT,3.848644e+05
4,QTUMETH,-0.000013,-0.778,0.001680,0.001661,0.001657,2.1000,0.001663,2.9000,0.001672,...,7.937540e+00,1698661850019,1698748250019,5406211,5406358,148,QTUM,ETH,ETHUSDT,1.429702e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2320,DOTFDUSD,0.122000,2.819,4.446445,4.305000,4.450000,200.0000,4.454000,22.4500,4.464000,...,1.930473e+04,1698661847420,1698748247420,554,753,200,DOT,FDUSD,FDUSDUSDT,1.931052e+04
2321,FTMFDUSD,-0.007300,-2.972,0.242248,0.244900,0.238300,559.0000,0.242700,4246.0000,0.243200,...,9.305489e+03,1698661852901,1698748252901,464,556,93,FTM,FDUSD,FDUSDUSDT,9.308281e+03
2322,LINKFDUSD,0.208000,1.842,11.479628,11.312000,11.502000,4.8600,11.510000,5.8600,11.532000,...,1.262516e+05,1698661849977,1698748249977,4136,4745,610,LINK,FDUSD,FDUSDUSDT,1.262894e+05
2323,NEARFDUSD,0.018000,1.395,1.303202,1.280000,1.308000,16.7000,1.293000,500.7000,1.299000,...,1.100241e+04,1698661851602,1698748251602,365,456,92,NEAR,FDUSD,FDUSDUSDT,1.100571e+04
2324,STRAXTRY,5.640000,23.039,28.843463,24.440000,30.120000,40.8000,30.170000,374.5000,30.200000,...,2.582866e+08,1698661851987,1698748251987,100645,132060,31416,STRAX,TRY,TRYUSDT,NaN

In [21]:
total_df = pd.DataFrame()
# upbit_ticker_df = self.info_dict['upbit_spot_ticker_df'][['market','acc_trade_price_24h_krw']].copy()
upbit_ticker_df = upbit_adaptor.all_tickers() # TEMP
# for upbit_market in self.enabled_markets_dict['UPBIT']['SPOT']:
for upbit_spot_quote_asset in ["KRW", "BTC"]: # TEMP
    each_upbit_ticker_df = upbit_ticker_df[upbit_ticker_df['quote_asset']==upbit_spot_quote_asset].copy()
    
    # for binance_spot_market in self.enabled_markets_dict['BINANCE']['SPOT']:
    for binance_spot_quote_asset in ["USDT", "BTC"]: # TEMP
        # each_binance_spot_info_df = self.info_dict['binance_spot_info_df'][self.info_dict['binance_spot_info_df']['symbol'].str.endswith(binance_spot_market)].copy()
        temp_df = binance_adaptor.spot_all_tickers() # TEMP
        each_binance_spot_ticker_df = temp_df[temp_df['quote_asset']==binance_spot_quote_asset].copy() # TEMP
        merged_df = each_upbit_ticker_df.merge(each_binance_spot_ticker_df[['symbol','base_asset']], on='base_asset', how='inner')
        total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

    # # for binance_usd_m_market in self.enabled_markets_dict['BINANCE']['USD_M_FUTURES']: # ["USDT_PERPETUAL", "BUSD_PERPETUAL"]
    # for binance_usd_m_market in ["USDT_PERPETUAL"]: # TEMP
    #     # Check PERPETUAL
    #     quote_asset, contract_type = binance_usd_m_market.split('_')
    #     # each_binance_usd_m_info_df = self.info_dict['binance_usd_m_info_df'][(self.info_dict['binance_usd_m_info_df']['quoteAsset']==quote_asset)&(self.info_dict['binance_usd_m_info_df']['contractType']==contract_type)].copy()        
    #     temp_df = binance_adaptor.usd_m_exchange_info() # TEMP
    #     each_binance_usd_m_info_df = temp_df[(temp_df['quoteAsset']==quote_asset)&(temp_df['contractType']==contract_type)].copy()        
    #     merged_df = each_upbit_ticker_df.merge(each_binance_usd_m_info_df[['symbol','baseAsset']], left_on='base_symbol', right_on='baseAsset' ,how='inner')
    #     total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

    # # for binance_coin_m_market in self.enabled_markets_dict['BINANCE']['COIN_M_FUTURES']: # ["PERPETUAL"]
    # for binance_coin_m_market in ["PERPETUAL"]: # TEMP
    #     # Check PERPETUAL
    #     contract_type = binance_coin_m_market
    #     # each_binance_coin_m_info_df = self.info_dict['binance_coin_m_info_df'][self.info_dict['binance_coin_m_info_df']['contractType']==contract_type].copy()
    #     temp_df = binance_adaptor.coin_m_exchange_info()
    #     each_binance_coin_m_info_df = temp_df[temp_df['contractType']==contract_type].copy() # TEMP
    #     merged_df = each_upbit_ticker_df.merge(each_binance_coin_m_info_df[['symbol','baseAsset']], left_on='base_symbol', right_on='baseAsset' ,how='inner')
    #     total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

    # # for okx_spot_quote_asset in self.enabled_market_dict['OKX']['SPOT']:
    # for okx_spot_quote_asset in ["USDT", "BTC"]: # TEMP
    #     # each_okx_spot_ticker_df = self.info_dict['okx_spot_ticker_df'][self.info_dict['okx_spot_ticker_df']['quote_asset']==okx_spot_market].copy()
    #     temp_df = okx_adaptor.spot_all_tickers()
    #     each_okx_spot_ticker_df = temp_df[temp_df['quote_asset']==okx_spot_market].copy() # TEMP

2023-10-31 23:15:13,860 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-10-31 23:15:14,827 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-10-31 23:15:15,798 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API
2023-10-31 23:15:16,738 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API