In [1]:
from okx_plug import InitOkxAdaptor
from upbit_plug import InitUpbitAdaptor
from binance_plug import InitBinanceAdaptor
import pandas as pd
import json
import time
import datetime
from threading import Thread
import numpy as np

In [2]:
info_dict = {}
info_thread_dict = {}

okx_adaptor = InitOkxAdaptor(None)
upbit_adaptor = InitUpbitAdaptor("x2AKLfsRtAgRxFjQ7p9TZTAg6E1SveoqfNfD8MK8", "svEran52QdsUyJdxAPYoTgFT2MXsHc5ZiKsKPxTL", info_dict, None)
binance_adaptor = InitBinanceAdaptor(None, None, info_dict, None)

# UPBIT SPOT (KRW, BTC Market)
# UPBIT wallet status
# BINANCE SPOT, USD-M Futures, COIN-M Futures
data_name_list = [
    "upbit_spot_ticker_df",
    "upbit_wallet_status_df",
    "upbit_spot_info_df",
    "binance_spot_ticker_df",
    "binance_spot_info_df",
    "binance_usd_m_ticker_df",
    "binance_usd_m_info_df",
    "binance_coin_m_ticker_df",
    "binance_coin_m_info_df",
    "okx_spot_ticker_df",
    "okx_spot_info_df",
    "okx_usd_m_ticker_df",
    "okx_usd_m_info_df",
    "okx_coin_m_ticker_df",
    "okx_coin_m_info_df"
]

def update_exchange_info_as_df(data_name, loop_time_secs=15):
    if data_name == "upbit_spot_ticker_df":
        info_dict[data_name] = upbit_adaptor.spot_all_tickers()
    elif data_name == "upbit_wallet_status_df":
        info_dict[data_name] = upbit_adaptor.wallet_status()
    elif data_name == "upbit_spot_info_df":
        info_dict[data_name] = upbit_adaptor.spot_exchange_info()
    elif data_name == "binance_spot_ticker_df":
        info_dict[data_name] = binance_adaptor.spot_all_tickers()
    elif data_name == "binance_spot_info_df":
        info_dict[data_name] = binance_adaptor.spot_exchange_info()
    elif data_name == "binance_usd_m_ticker_df":
        info_dict[data_name] = binance_adaptor.usd_m_all_tickers()
    elif data_name == "binance_usd_m_info_df":
        info_dict[data_name] = binance_adaptor.usd_m_exchange_info()
    elif data_name == "binance_coin_m_ticker_df":
        info_dict[data_name] = binance_adaptor.coin_m_all_tickers()
    elif data_name == "binance_coin_m_info_df":
        info_dict[data_name] = binance_adaptor.coin_m_exchange_info()
    elif data_name == "okx_spot_ticker_df":
        info_dict[data_name] = okx_adaptor.spot_all_tickers()
    elif data_name == "okx_spot_info_df":
        info_dict[data_name] = okx_adaptor.spot_exchange_info()
    elif data_name == "okx_usd_m_ticker_df":
        info_dict[data_name] = okx_adaptor.usd_m_all_tickers()
    elif data_name == "okx_usd_m_info_df":
        info_dict[data_name] = okx_adaptor.usd_m_exchange_info()
    elif data_name == "okx_coin_m_ticker_df":
        info_dict[data_name] = okx_adaptor.coin_m_all_tickers()
    elif data_name == "okx_coin_m_info_df":
        info_dict[data_name] = okx_adaptor.coin_m_exchange_info()
    else:
        print(f"update_exchange_info_as_df|name:{data_name} is not valid.")

for data_name in data_name_list:
    info_thread_dict[f"update_{data_name}"] = Thread(target=update_exchange_info_as_df, args=(data_name,), daemon=True)
    info_thread_dict[f"update_{data_name}"].start()
    print(f"InitCore|update_{data_name} thread has started.")

2023-11-02 14:12:34,114 - okx_plug - INFO - okx_plug_logger started.
2023-11-02 14:12:34,609 - upbit_plug - INFO - upbit_plug_logger started.
2023-11-02 14:12:34,723 - binance_plug - INFO - binance_plug_logger started.

InitCore|update_upbit_spot_ticker_df thread has started.
InitCore|update_upbit_wallet_status_df thread has started.
InitCore|update_upbit_spot_info_df thread has started.
InitCore|update_binance_spot_ticker_df thread has started.
InitCore|update_binance_spot_info_df thread has started.
InitCore|update_binance_usd_m_ticker_df thread has started.
InitCore|update_binance_usd_m_info_df thread has started.
InitCore|update_binance_coin_m_ticker_df thread has started.
InitCore|update_binance_coin_m_info_df thread has started.
InitCore|update_okx_spot_ticker_df thread has started.
InitCore|update_okx_spot_info_df thread has started.
InitCore|update_okx_usd_m_ticker_df thread has started.
InitCore|update_okx_usd_m_info_df thread has started.
InitCore|update_okx_coin_m_ticker_df thread has started.
InitCore|update_okx_coin_m_info_df thread has started.

2023-11-02 14:12:35,617 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-11-02 14:12:36,866 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-11-02 14:12:37,101 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [8]:
binance_funding_df = binance_adaptor.get_fundingrate()
binance_funding_df.head()

,symbol,funding_rate,funding_time,base_asset,quote_asset,perpetual
0,LEVERBUSD,0.0001,2023-11-02 08:00:00,LEVER,BUSD,True
1,AVAXUSDT,0.000347,2023-11-02 08:00:00,AVAX,USDT,True
2,ORBSUSDT,0.000308,2023-11-02 08:00:00,ORBS,USDT,True
3,FLMUSDT,0.00029,2023-11-02 08:00:00,FLM,USDT,True
4,MATICBUSD,0.0001,2023-11-02 08:00:00,MATIC,BUSD,True

In [10]:
binance_funding_df[binance_funding_df["quote_asset"].isnull()]

,symbol,funding_rate,funding_time,base_asset,quote_asset,perpetual
94,BNBBTC,0.0,2023-11-02 08:00:00,NaN,NaN,True
187,SNTUSDT,0.0001,2023-11-02 08:00:00,NaN,NaN,True

In [76]:
futures_type = "USD_M"
if futures_type == "COIN_M":
    symbol_list = [x['instId'] for x in okx_adaptor.pub_client.PublicAPI.get_instruments(instType='SWAP')['data'] if x['instId'].split("-")[1] == "USD"]
elif futures_type == "USD_M":
    symbol_list = [x['instId'] for x in okx_adaptor.pub_client.PublicAPI.get_instruments(instType='SWAP')['data'] if x['instId'].split("-")[1] != "USD"]
else:
    print(f"get_okx_fundingrate|futures_type:{futures_type} is not valid.")

funding_data_list = []
for each_symbol in symbol_list[:3]:
    funding_data_list.append(okx_adaptor.pub_client.PublicAPI.get_funding_rate(each_symbol)['data'][0])

funding_df = pd.DataFrame(funding_data_list)
funding_df.loc[:, ["fundingRate", "fundingTime", "nextFundingRate", "nextFundingTime"]] = funding_df[["fundingRate", "fundingTime", "nextFundingRate", "nextFundingTime"]].astype(float)
# funding_df.loc[:, ["fundingTime", "nextFundingTime"]] = funding_df.loc[:, ["fundingTime", "nextFundingTime"]].applymap(lambda x: pd.to_datetime(x, unit='ms', utc=True))
funding_df.loc[:, "fundingTime"] = pd.to_datetime(funding_df['fundingTime'], unit='ms', utc=False)
# # funding_df.loc[:, "fundingTime"] = funding_df["fundingTime"].dt.tz_localize(None)
# funding_df['base_asset'] = funding_df['instId'].apply(lambda x: x.split("-")[0])
# funding_df['quote_asset'] = funding_df['instId'].apply(lambda x: x.split("-")[1])
# funding_df['perpetual'] = True
# funding_df = funding_df.rename(columns={"fundingRate": "funding_rate", "fundingTime": "funding_time", "nextFundingRate": "next_funding_rate", "nextFundingTime": "next_funding_time"})
funding_df

,fundingRate,fundingTime,instId,instType,nextFundingRate,nextFundingTime
0,0.000176,2023-11-02 08:00:00,BTC-USDT-SWAP,SWAP,0.000023,1698940800000.0
1,0.000266,2023-11-02 08:00:00,ETH-USDT-SWAP,SWAP,0.000046,1698940800000.0
2,0.000205,2023-11-02 08:00:00,LTC-USDT-SWAP,SWAP,0.000353,1698940800000.0

In [77]:
funding_df['fundingTime'].dtype

dtype('O')

In [70]:
pd.to_datetime(funding_df['fundingTime'], unit='ms', utc=True)

KeyError: 'fundingTime'

In [69]:
funding_df['funding_time'].dtype

dtype('O')

In [67]:
funding_df['funding_time'].dt.tz_localize(None)

AttributeError: Can only use .dt accessor with datetimelike values

In [5]:
enabled_markets = \
    {
        "UPBIT": 
        {
            "SPOT": ["KRW","BTC"]
        },
        "BINANCE":
        {
            "SPOT": ["USDT", "BTC"],
            "USD_M": {
                "PERPETUAL": ["USDT"],
                "FUTURES": []
            },
            "COIN_M": {
                "PERPETUAL": ["USD"],
                "FUTURES": []
            }
        },
        "OKX":
        {
            "SPOT": ["USDT", "BTC"],
            "USD_M": {
                "PERPETUAL": ["USDT"],
                "FUTURES": []
            },
            "COIN_M": {
                "PERPETUAL": ["USD"],
                "FUTURES": []
            }
        }
    }