In [1]:
from okx_plug import InitOkxAdaptor
from upbit_plug import InitUpbitAdaptor
from binance_plug import InitBinanceAdaptor
from bithumb_plug import InitBithumbAdaptor
from bybit_plug import InitBybitAdaptor
import pandas as pd
import json
import time
import datetime
from threading import Thread
import numpy as np

In [2]:
info_dict = {}
info_thread_dict = {}

okx_adaptor = InitOkxAdaptor("fcb66a6e-0443-4743-8d9b-61caf7eab662", "0029E09874B38F5AC7E68E9DFC348667", "121431Rn!!")
upbit_adaptor = InitUpbitAdaptor("x2AKLfsRtAgRxFjQ7p9TZTAg6E1SveoqfNfD8MK8", "svEran52QdsUyJdxAPYoTgFT2MXsHc5ZiKsKPxTL", info_dict, None)
binance_adaptor = InitBinanceAdaptor("4PFfYsObYyUaMlk7m6tT9qIl8X8P3WCUsyu1lEyZ4h50VfTMPIQCNdL9eOJCl3Lb", "011Z1W9p4425AZgtCNbs5L1d77ehZFNmBIwT0pz1SJGP7EiOlPILfWBglbVsxMcK", info_dict, None)
bithumb_adaptor = InitBithumbAdaptor()
bybit_adaptor = InitBybitAdaptor()

# UPBIT SPOT (KRW, BTC Market)
# UPBIT wallet status
# BINANCE SPOT, USD-M Futures, COIN-M Futures
data_name_list = [
        "upbit_spot_info_df",
        "upbit_spot_ticker_df",
        # "upbit_wallet_status_df",
        "binance_spot_ticker_df",
        "binance_spot_info_df",
        "binance_usd_m_ticker_df",
        "binance_usd_m_info_df",
        "binance_coin_m_ticker_df",
        "binance_coin_m_info_df",
        "okx_spot_ticker_df",
        "okx_spot_info_df",
        "okx_usd_m_ticker_df",
        "okx_usd_m_info_df",
        "okx_coin_m_ticker_df",
        "okx_coin_m_info_df",
        "bithumb_spot_info_df",
        "bithumb_spot_ticker_df",
        # "bithumb_wallet_status_df",
        "bybit_spot_info_df",
        "bybit_spot_ticker_df",
        "bybit_usd_m_info_df",
        "bybit_usd_m_ticker_df",
        "bybit_coin_m_info_df",
        "bybit_coin_m_ticker_df"
    ]

def update_exchange_info_as_df(data_name, loop_time_secs=15):
    if data_name == "upbit_spot_ticker_df":
        info_dict[data_name] = upbit_adaptor.spot_all_tickers()
    elif data_name == "upbit_wallet_status_df":
        info_dict[data_name] = upbit_adaptor.wallet_status()
    elif data_name == "upbit_spot_info_df":
        info_dict[data_name] = upbit_adaptor.spot_exchange_info()
    elif data_name == "binance_spot_ticker_df":
        info_dict[data_name] = binance_adaptor.spot_all_tickers()
    elif data_name == "binance_spot_info_df":
        info_dict[data_name] = binance_adaptor.spot_exchange_info()
    elif data_name == "binance_usd_m_ticker_df":
        info_dict[data_name] = binance_adaptor.usd_m_all_tickers()
    elif data_name == "binance_usd_m_info_df":
        info_dict[data_name] = binance_adaptor.usd_m_exchange_info()
    elif data_name == "binance_coin_m_ticker_df":
        info_dict[data_name] = binance_adaptor.coin_m_all_tickers()
    elif data_name == "binance_coin_m_info_df":
        info_dict[data_name] = binance_adaptor.coin_m_exchange_info()
    elif data_name == "okx_spot_ticker_df":
        info_dict[data_name] = okx_adaptor.spot_all_tickers()
    elif data_name == "okx_spot_info_df":
        info_dict[data_name] = okx_adaptor.spot_exchange_info()
    elif data_name == "okx_usd_m_ticker_df":
        info_dict[data_name] = okx_adaptor.usd_m_all_tickers()
    elif data_name == "okx_usd_m_info_df":
        info_dict[data_name] = okx_adaptor.usd_m_exchange_info()
    elif data_name == "okx_coin_m_ticker_df":
        info_dict[data_name] = okx_adaptor.coin_m_all_tickers()
    elif data_name == "okx_coin_m_info_df":
        info_dict[data_name] = okx_adaptor.coin_m_exchange_info()
    elif data_name == "bithumb_spot_info_df":
        info_dict[data_name] = bithumb_adaptor.spot_exchange_info()
    elif data_name == "bithumb_spot_ticker_df":
        info_dict[data_name] = bithumb_adaptor.spot_all_tickers()
    elif data_name == "bithumb_wallet_status_df":
        info_dict[data_name] = bithumb_adaptor.wallet_status()
    elif data_name == "bybit_spot_info_df":
        info_dict[data_name] = bybit_adaptor.spot_exchange_info()
    elif data_name == "bybit_spot_ticker_df":
        info_dict[data_name] = bybit_adaptor.spot_all_tickers()
    elif data_name == "bybit_usd_m_info_df":
        info_dict[data_name] = bybit_adaptor.usd_m_exchange_info()
    elif data_name == "bybit_usd_m_ticker_df":
        info_dict[data_name] = bybit_adaptor.usd_m_all_tickers()
    elif data_name == "bybit_coin_m_info_df":
        info_dict[data_name] = bybit_adaptor.coin_m_exchange_info()
    elif data_name == "bybit_coin_m_ticker_df":
        info_dict[data_name] = bybit_adaptor.coin_m_all_tickers()
    else:
        print(f"update_exchange_info_as_df|name:{data_name} is not valid.")

for data_name in data_name_list:
    info_thread_dict[f"update_{data_name}"] = Thread(target=update_exchange_info_as_df, args=(data_name,), daemon=True)
    info_thread_dict[f"update_{data_name}"].start()
    print(f"InitCore|update_{data_name} thread has started.")

2023-11-10 13:58:47,838 - okx_plug - INFO - okx_plug_logger started.
2023-11-10 13:58:48,269 - upbit_plug - INFO - upbit_plug_logger started.
2023-11-10 13:58:48,396 - binance_plug - INFO - binance_plug_logger started.
2023-11-10 13:58:48,398 - bithumb_plug - INFO - bithumb_plug_logger started.
2023-11-10 13:58:48,399 - bybit_plug - INFO - bybit_plug_logger started.

In [13]:
info_dict.keys()

dict_keys(['upbit_spot_info_df', 'bybit_coin_m_info_df', 'bithumb_spot_ticker_df', 'binance_coin_m_ticker_df', 'upbit_spot_ticker_df', 'binance_coin_m_info_df', 'bithumb_spot_info_df', 'okx_spot_info_df', 'bybit_coin_m_ticker_df', 'binance_usd_m_info_df', 'bybit_spot_info_df', 'okx_usd_m_info_df', 'okx_coin_m_info_df', 'bybit_usd_m_info_df', 'okx_spot_ticker_df', 'okx_coin_m_ticker_df', 'binance_spot_info_df', 'okx_usd_m_ticker_df', 'bybit_spot_ticker_df', 'bybit_usd_m_ticker_df', 'binance_spot_ticker_df', 'binance_usd_m_ticker_df'])

In [3]:
enabled_markets = \
    {
        "UPBIT": 
        {
            "SPOT": ["KRW","BTC"]
        },
        "BITHUMB":
        {
            "SPOT": ["KRW"]
        },
        "BINANCE":
        {
            "SPOT": ["USDT", "BTC"],
            "USD_M": {
                "PERPETUAL": ["USDT"],
                "FUTURES": []
            },
            "COIN_M": {
                "PERPETUAL": ["USD"],
                "FUTURES": []
            }
        },
        "OKX":
        {
            "SPOT": ["USDT", "BTC"],
            "USD_M": {
                "PERPETUAL": ["USDT"],
                "FUTURES": []
            },
            "COIN_M": {
                "PERPETUAL": ["USD"],
                "FUTURES": []
            }
        },
        "BYBIT":
        {
            "SPOT": ["USDT"],
            "USD_M": {
                "PERPETUAL": ["USDT"],
                "FUTURES": []
            },
            "COIN_M": {
                "PERPETUAL": ["USD"],
                "FUTURES": []
            }
        }
    }

In [4]:
class Test:
    def __init__(self, info_dict, enabled_markets):
        self.info_dict = info_dict
        self.enabled_markets_dict = enabled_markets

    def get_symbol_list(self, target_market): # E.g) UPBIT_SPOT, BINANCE_SPOT, BINANCE_USD_M, BINANCE_COIN_M
        target_exchange = target_market.split('_')[0]
        target_market_type = '_'.join(target_market.split('_')[1:])

        comparing_exchanges = self.enabled_markets_dict.keys()
        comparison_list = []
        total_df = pd.DataFrame()
        for exchange in comparing_exchanges:
            for market_type in self.enabled_markets_dict[exchange]:
                if market_type == "SPOT":
                    for quote_asset in self.enabled_markets_dict[exchange][market_type]:
                        comparison_list.append({"exchange": exchange, "market_type": market_type, "contract_type":None, "quote_asset": quote_asset})
                else:
                    for contract_type in self.enabled_markets_dict[exchange][market_type]:
                        for quote_asset in self.enabled_markets_dict[exchange][market_type][contract_type]:
                            comparison_list.append({"exchange": exchange, "market_type": market_type, "contract_type":contract_type, "quote_asset": quote_asset})

        for i, comparison_dict in enumerate(comparison_list):
            if comparison_dict['exchange'] == target_exchange and comparison_dict['market_type'] == target_market_type:
                target_market_dict = comparison_list.pop(i)
                break

        # Start compare and concat
        target_market_ticker_df = self.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_ticker_df"]
        # check if it's spot or not
        if target_market_dict['market_type'] != "SPOT":
            target_market_info_df = self.info_dict[f"{target_market_dict['exchange'].lower()}_{target_market_dict['market_type'].lower()}_info_df"][['symbol','perpetual']]
            target_market_ticker_df = target_market_ticker_df.merge(target_market_info_df, on='symbol', how='inner')
            if target_market_dict['contract_type'] == "PERPETUAL":
                target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['perpetual'] == True]
            else: # FUTURES
                target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['perpetual'] == False]
        target_market_ticker_df = target_market_ticker_df[target_market_ticker_df['quote_asset']==target_market_dict['quote_asset']][['symbol','lastPrice','atp24h','base_asset','quote_asset']]
        for each_comparison_dict in comparison_list:
            each_market_info_df = self.info_dict[f"{each_comparison_dict['exchange'].lower()}_{each_comparison_dict['market_type'].lower()}_info_df"]
            if each_comparison_dict['contract_type'] is None:
                each_market_info_df = each_market_info_df[each_market_info_df['quote_asset']==each_comparison_dict['quote_asset']]
            else: # contract_type is PERPETUAL or FUTURES
                if each_comparison_dict['contract_type'] == "PERPETUAL":
                    each_market_info_df = each_market_info_df[(each_market_info_df['quote_asset']==each_comparison_dict['quote_asset'])&(each_market_info_df['perpetual'] == True)]
                else: # FUTURES
                    each_market_info_df = each_market_info_df[(each_market_info_df['quote_asset']==each_comparison_dict['quote_asset'])&(each_market_info_df['perpetual'] == False)]
            comparison_market_code = f"{each_comparison_dict['exchange'].lower()}_{each_comparison_dict['market_type'].lower()}"
            new_symbol = f"symbol_{comparison_market_code}"
            new_quote_asset = f"quote_asset_{comparison_market_code}"
            each_market_info_df = each_market_info_df.rename(columns={"symbol":new_symbol, "quote_asset": new_quote_asset})
            merged_df = target_market_ticker_df.merge(each_market_info_df[[new_symbol, "base_asset", new_quote_asset]], on='base_asset', how='inner')
            total_df = pd.concat([total_df, merged_df], axis=0, ignore_index=True)

        total_df.drop_duplicates(['symbol'], inplace=True)
        total_df.sort_values('atp24h', ascending=False)
        total_df.reset_index(drop=True, inplace=True)
        return total_df['symbol'].to_list()

2023-11-09 17:12:43,798 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API

2023-11-09 17:12:44,461 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_usd_m_info_df') is None, Fetched from API
2023-11-09 17:12:44,504 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_spot_info_df') is None, Fetched from API
2023-11-09 17:12:44,955 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_ticker_df') is None, Fetched from API
2023-11-09 17:12:45,278 - binance_plug - INFO - self.info_dict is None or self.info_dict.get('binance_spot_info_df') is None, Fetched from API

In [3]:
binance_adaptor.get_fundingrate()

,symbol,funding_rate,funding_time,base_asset,quote_asset,perpetual
0,BELUSDT,0.000387,2023-11-09 16:00:00,BEL,USDT,True
1,OMGUSDT,0.000382,2023-11-09 16:00:00,OMG,USDT,True
2,RVNUSDT,0.000111,2023-11-09 16:00:00,RVN,USDT,True
3,ANTUSDT,0.000315,2023-11-09 16:00:00,ANT,USDT,True
4,CHZUSDT,0.000248,2023-11-09 16:00:00,CHZ,USDT,True
...,...,...,...,...,...,...
276,OPUSDT,0.000294,2023-11-09 16:00:00,OP,USDT,True
277,AMBBUSD,0.0001,2023-11-09 16:00:00,AMB,BUSD,True
278,JOEUSDT,0.0001,2023-11-09 16:00:00,JOE,USDT,True
279,AGIXBUSD,0.0001,2023-11-09 16:00:00,AGIX,BUSD,True
280,KNCUSDT,0.000211,2023-11-09 16:00:00,KNC,USDT,True

In [6]:
bybit_adaptor.usd_m_all_tickers()[['symbol','base_asset','quote_asset','fundingRate','nextFundingTime']]

2023-11-09 17:16:03,248 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API

             symbol  base_asset quote_asset fundingRate nextFundingTime
0    10000LADYSUSDT  10000LADYS        USDT    0.000246   1699545600000
1      10000NFTUSDT    10000NFT        USDT      0.0001   1699545600000
2    10000STARLUSDT  10000STARL        USDT    0.002001   1699545600000
3      1000BONKUSDT    1000BONK        USDT   -0.012632   1699545600000
4       1000BTTUSDT     1000BTT        USDT    0.003003   1699545600000
..              ...         ...         ...         ...             ...
289         YGGUSDT         YGG        USDT    0.000176   1699545600000
290         ZECUSDT         ZEC        USDT      0.0001   1699545600000
291         ZENUSDT         ZEN        USDT    0.000414   1699545600000
292         ZILUSDT         ZIL        USDT     0.00078   1699545600000
293         ZRXUSDT         ZRX        USDT    0.000588   1699545600000

[294 rows x 5 columns]

In [17]:
futures_type = "USD_M"

if futures_type == "USD_M":
    ticker_df = bybit_adaptor.usd_m_all_tickers()
else:
    ticker_df = bybit_adaptor.coin_m_all_tickers()
funding_df = ticker_df[['symbol','base_asset','quote_asset','fundingRate','nextFundingTime']]
funding_df['perpetual'] = funding_df['fundingRate'].apply(lambda x: True if x != '' else False)
funding_df.loc[:, ['fundingRate','nextFundingTime']] = funding_df.loc[:, ['fundingRate','nextFundingTime']].apply(pd.to_numeric, errors='coerce')
funding_df['nextFundingTime'] = funding_df['nextFundingTime'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000, tz=datetime.timezone.utc))
funding_df['nextFundingTime'] = funding_df['nextFundingTime'].dt.tz_localize(None)
funding_df

2023-11-09 17:35:14,389 - bybit_plug - INFO - self.info_dict is None or self.info_dict.get('bybit_usd_m_info_df') is None, Fetched from API

,symbol,base_asset,quote_asset,fundingRate,nextFundingTime,perpetual
0,10000LADYSUSDT,10000LADYS,USDT,0.000839,2023-11-09 16:00:00,True
1,10000NFTUSDT,10000NFT,USDT,0.0001,2023-11-09 16:00:00,True
2,10000STARLUSDT,10000STARL,USDT,0.001516,2023-11-09 16:00:00,True
3,1000BONKUSDT,1000BONK,USDT,-0.004175,2023-11-09 16:00:00,True
4,1000BTTUSDT,1000BTT,USDT,0.002024,2023-11-09 16:00:00,True
...,...,...,...,...,...,...
289,YGGUSDT,YGG,USDT,0.000212,2023-11-09 16:00:00,True
290,ZECUSDT,ZEC,USDT,0.0001,2023-11-09 16:00:00,True
291,ZENUSDT,ZEN,USDT,0.000177,2023-11-09 16:00:00,True
292,ZILUSDT,ZIL,USDT,0.000559,2023-11-09 16:00:00,True
293,ZRXUSDT,ZRX,USDT,0.000505,2023-11-09 16:00:00,True

In [ ]:
binance_fund.loc[:,'funding_time'] = binance_fund.loc[:,'funding_time'].apply(lambda x: datetime.datetime.fromtimestamp(x/1000, tz=datetime.timezone.utc))
            binance_fund.loc[:,'funding_time'] = binance_fund.loc[:,'funding_time'].dt.tz_localize(None)